### ISSUE TITLE
Install link not work

### ISSUE THREAD

**Issue by renat2985** [kalcaddle/kodbox#1]
<img width="1011" alt="изображение" src="https://user-images.githubusercontent.com/1230815/114068520-ab3fa480-98a6-11eb-8e2b-4b34fba9bed4.png">
Console:
<img width="859" alt="изображение" src="https://user-images.githubusercontent.com/1230815/114068612-c7dbdc80-98a6-11eb-9b45-05b93bed74c4.png">

**Comment by kalcaddle** [comment]
changed
