### ISSUE TITLE
突然打不开了

### ISSUE THREAD

**Issue by lya0** [kalcaddle/kodbox#10]
{
    "code": false,
    "timeUse": "5.1767",
    "timeNow": "1621926369.6511",
    "data": null,
    "memory": "2.422M",
    "call": [
        "index.php[6] {a36}#Application->run()",
        "app\/autoload.php[2] {a36}#Application->autorun()",
        "app\/autoload.php[2] {a36}#Application->appRun(\"user.index.init\")",
        "app\/autoload.php[2] ActionCall(\"user.index.init\")",
        "app\/autoload.php[2] ActionApply(\"user.index.init\",[])",
        "app\/autoload.php[2] {466}#userIndex->init()",
        "app\/controller\/user\/index.class.php[24] ActionCall(\"install.index.check\")",
        "app\/autoload.php[2] ActionApply(\"install.index.check\",[])",
        "app\/autoload.php[2] {f57}#installIndex->check()",
        "app\/controller\/install\/index.class.php[67] ActionCall(\"install.index.save\")",
        "app\/autoload.php[2] ActionApply(\"install.index.save\",[])",
        "app\/autoload.php[2] {f57}#installIndex->save()",
        "app\/controller\/install\/index.class.php[215] {f57}#installIndex->saveDb()",
        "app\/controller\/install\/index.class.php[225] Cache::get(\"dbWasSet\")",
        "app\/autoload.php[2] CacheLock::lock(\"dbWasSet\")",
        "app\/autoload.php[2] show_json(args)"
    ],
    "trace": []
}

这是什么问题？autoload.php加密无法查看

**Comment by kalcaddle** [comment]
有调用栈就知道问题了, 并发读写加锁失败; 可能的原因:
1. 有加锁某个key的任务还没执行完成, 操作比较耗时的情况会出现(这种情况无解,需要自己注意)
2. 使用的缓存写入异常了,如果是redis,尝试清空缓存,再重启redis; 如果是文件缓存则手动删除data/temp文件夹即可.


代码如下,看了也是上述说明的问题.




 原始邮件 
发件人: ***@***.***>
收件人: ***@***.***>
抄送: ***@***.***>
发送时间: 2021年5月25日(周二) 15:16
主题: [kalcaddle/kodbox] 突然打不开了 (#10)


{
 "code": false,
 "timeUse": "5.1767",
 "timeNow": "1621926369.6511",
 "data": null,
 "memory": "2.422M",
 "call": [
 "index.php[6] {a36}#Application->run()",
 "app/autoload.php[2] {a36}#Application->autorun()",
 "app/autoload.php[2] {a36}#Application->appRun("user.index.init")",
 "app/autoload.php[2] ActionCall("user.index.init")",
 "app/autoload.php[2] ActionApply("user.index.init",[])",
 "app/autoload.php[2] {466}#userIndex->init()",
 "app/controller/user/index.class.php[24] ActionCall("install.index.check")",
 "app/autoload.php[2] ActionApply("install.index.check",[])",
 "app/autoload.php[2] {f57}#installIndex->check()",
 "app/controller/install/index.class.php[67] ActionCall("install.index.save")",
 "app/autoload.php[2] ActionApply("install.index.save",[])",
 "app/autoload.php[2] {f57}#installIndex->save()",
 "app/controller/install/index.class.php[215] {f57}#installIndex->saveDb()",
 "app/controller/install/index.class.php[225] Cache::get("dbWasSet")",
 "app/autoload.php[2] CacheLock::lock("dbWasSet")",
 "app/autoload.php[2] show_json(args)"
 ],
 "trace": []
 }
这是什么问题？autoload.php加密无法查看

**Comment by kalcaddle** [comment]
有调用栈就知道问题了, 原因是并发读写加锁失败;
可能导致加锁失败的原因:
1. 有加锁某个key的任务还没执行完成, 操作比较耗时的情况会出现(这种情况无解,需要自己注意)
2. 使用的缓存写入异常了,如果是redis,尝试清空缓存,再重启redis; 如果是文件缓存则手动删除data/temp文件夹即可.


代码如下,看了也是上述说明的问题.

``` php
public static function lock($lockKey,$timeout=false,$global=false){
	$handle  = self::init();
	$key 	 = self::key($lockKey);
	$timeout = $timeout ? $timeout : self::$timeout;
	$result = $handle->lock($key,$timeout);
	// write_log("lock:$lockKey,$key;$result".get_caller_msg(),'lock');
	if(!$result){
		$errorLog  = "lock error;time=".$timeout.';'.self::$errorMsg.';'.get_caller_msg();
		$errorTips = "Lock action: {$key} timeout,over {$timeout} s";
		$errorTips = self::$errorMsg? self::$errorMsg:$errorTips;

		write_log($errorLog,'lock');
		show_json($errorTips,false);
	}
	if(!$global){ // 全局锁
		self::$lockItem[$key] = true;
	}
	return $result;
}
```
