### ISSUE TITLE
Filenames split

### ISSUE THREAD

**Issue by RallyTuning** [kalcaddle/kodbox#101]
The name of the files still split wrong. Please split it for " " (space) and not for max char.
_Because if you split by char, it is HARD to understand what is the name of the file._

### **Example:**

**Wrong:**
```
This is a lo
ng filenam
e.txt
```

**Correct:**
```
This is a
long
filename.txt
```

**Comment by kalcaddle** [comment]
Auto wrap depends on browser rendering.
We have used 'word break: break word;' To deal with this situation, but it is still not good enough. You can put forward rendering optimization suggestions to chrome

**Comment by RallyTuning** [comment]
Tell me the file and the code line where is the function that controls names, i will take a look
