### ISSUE TITLE
无法分享网络挂载中的文件

### ISSUE THREAD

**Issue by xzqiaochu** [kalcaddle/kodbox#109]
似乎只能分享可道云虚拟目录下的文件，例如可以分享个人空间、企业网盘下的文件，
但无法分享真实目录下的文件，例如管理员无法分享网络挂载里的文件，也无法分享其他主机其他目录下的文件。如果点分享或者协作的话，会弹出下面这样的报错：
![image](https://user-images.githubusercontent.com/41484968/173610982-a9ec40e9-adee-4ff4-91fa-3fb51b7cdf38.png)

在旧版可道云（kodexplorer），是可以这样做的，新版的kodbox不知道砍掉了，还是忘记适配了。
感觉这个功能还是有点用处的，我是在群晖里装的kodbox，已经在群晖的文件系统里整理了一整套团队共同访问的文件。因为觉得可道云在文件分享协作功能上做的很好，想把群晖里的文件挂载可道云里进行分享。但可道云却不支持分享网络挂载的文件。如果把群晖里的文件导入可道云的企业网盘，不仅会带来额外的储存开销，而且可道云对储存进行了重映射，不方便进行管理。

希望在后续的版本上能加上这个功能，支持可道云团队！

**Comment by kalcaddle** [comment]
功能时支持的,服务器兼容问题(应该是opcache / php8.x).
我们下个版本兼容优化一下.
