### ISSUE TITLE
Does not work after 1.20 update

### ISSUE THREAD

**Issue by devenbj** [kalcaddle/kodbox#11]
My KodBox updated to 1.20, and now I get the error below:
出错了! (warning!)
../app/autoload.php[2]; UserOptionModel->cacheKey();
Undefined constant "USER_ID"

I tried installing a new copy and had the same error.

**Comment by kalcaddle** [comment]
not support php8 now



发自我的iPhone


------------------ Original ------------------
From: Brian Devendorf ***@***.***&gt;
Date: Wed,May 26,2021 1:17 AM
To: kalcaddle/kodbox ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [kalcaddle/kodbox] Does not work after 1.20 update (#11)

**Comment by devenbj** [comment]
1.19 works with PHP 8. Will php8 be supported in a future version?

**Comment by kalcaddle** [comment]
we will adaptation soon.
suggest &nbsp;php 7.4



发自我的iPhone


------------------ Original ------------------
From: Brian Devendorf ***@***.***&gt;
Date: Wed,May 26,2021 2:26 AM
To: kalcaddle/kodbox ***@***.***&gt;
Cc: warlee ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [kalcaddle/kodbox] Does not work after 1.20 update (#11)

**Comment by devenbj** [comment]
I confirm that php7.4 works. Thanks!

**Comment by dhtoan** [comment]
How to customize theme? I want it to look like MacOS 11

**Comment by kalcaddle** [comment]
> How to customize theme? I want it to look like MacOS 11

customize css ,
