### ISSUE TITLE
webdav 确定能够通过raildriver挂载吗 ？为何一直报401 错误？

### ISSUE THREAD

**Issue by wadeLouis** [kalcaddle/kodbox#113]
1. 自用的群晖，可以通过raildriver挂载webdav，kodbox的却不行。可以明确挂载选项没有填错。
rclone和gnome的davfs我都尝试过，都是kodbox不行。
报错永远的401 未认证的错误。
2. 帐号密码是否错误，我能登录web端，难道不是这个帐号密码？

请求协助，不知道什么搞了。

**Comment by kalcaddle** [comment]
windows,mac, raildriver 挂载都是正常的.
请确定地址是否填写错误. 个人设置-webdav 复制webdav的地址是根目录.  看看挂载的地方是否要填写子目录.
