### ISSUE TITLE
data.bin 文件在阿里云服务器会报病毒

### ISSUE THREAD

**Issue by fyzhu** [kalcaddle/kodbox#115]
<img width="772" alt="image" src="https://user-images.githubusercontent.com/5175751/182117537-8830611d-7958-4683-8e1a-ab403c9aa0b6.png">

**Comment by kalcaddle** [comment]
误报，忽略即可



杭州可道云网络有限公司


------------------ 原始邮件 ------------------
发件人: Yvan Zhu ***@***.***&gt;
发送时间: 2022年8月1日 17:25
收件人: kalcaddle/kodbox ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [kalcaddle/kodbox] data.bin 文件在阿里云服务器会报病毒 (Issue #115)

**Comment by fyzhu** [comment]
> 误报，忽略即可 杭州可道云网络有限公司
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Yvan Zhu ***@***.***&gt; 发送时间: 2022年8月1日 17:25 收件人: kalcaddle/kodbox ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [kalcaddle/kodbox] data.bin 文件在阿里云服务器会报病毒 (Issue #115) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

这个文件是干啥用的？

**Comment by kalcaddle** [comment]
这个文件是干啥用的: 部分因为逻辑处理.

**Comment by mrx47329** [comment]
I didn't trust this project because some files are encrypted and no one knows what they do.

**Comment by kalcaddle** [comment]
> I didn't trust this project because some files are encrypted and no one knows what they do.

Some codes are compressed just to prevent easy cracking to get the professional version. 
You know, the obfuscation of PHP code is similar to the obfuscation of JS code, and it is easy to get the source code.

If you need to use it for secondary development, here are all the codes: 
https://demo.kodcloud.com/#s/90zCPzDQ

**Comment by mrx47329** [comment]
Thank you. You have created a very good product.

**Comment by mrx47329** [comment]
If I use the professional version, will the code be encrypted? Unfortunately, I have little experience. I am very suspicious of anything encrypted.
