### ISSUE TITLE
使用宝塔面板一键安装，配置管理员账号时出错

### ISSUE THREAD

**Issue by Highsunlight** [kalcaddle/kodbox#116]
<img width="832" alt="屏幕截图 2022-08-02 004637" src="https://user-images.githubusercontent.com/69392777/182201014-1b326cb4-a68b-4ea2-950e-fc777546fd86.png">

打开配置好的网站地址，即显示账号设置

环境为Ubuntu20.04.4+nginx1.21.0+php8.0+mysql5.6.50+redis7.0

**Comment by kalcaddle** [comment]
看提示信息,数据库连接报错了;
检查下数据库填写是否正常, 服务器/用户名/密码  是否错误.

**Comment by Highsunlight** [comment]
用宝塔面板一键布署，进网站就是设置管理员账号，理应不应该出问题啊

麻烦您再看下，谢谢

**Comment by kalcaddle** [comment]
我们再次在几个系统的宝塔面板上测试(CentOS 7.3; Ubuntu20), 未出现你提出的问题. 
可能是你数据库设置了白名单或者访问限制. 
可以尝试用数据库管理工具链接一下新建站点的数据库用户名密码.

还不行的话,如果方便可以提供一下套他面板地址和账号我们看看.  发送邮件到  warlee#kodcloud.com
