### ISSUE TITLE
功能建议：编辑器能设置默认格式且文件后缀位相应后缀

### ISSUE THREAD

**Issue by DeathAndLife** [kalcaddle/kodbox#117]
![image](https://user-images.githubusercontent.com/51323917/182416382-e65985f8-986d-49f5-936d-772fb1649fef.png)
最常用的就是Markdown了，但是看了一下数据库保存的参数没有格式的选项
希望出一个这个功能！！

**Comment by kalcaddle** [comment]
不支持设置默认保存格式,  有两种方法解决这个问: 
1. 可以右键新建文件时选择md,后续就都是自动为md格式
2. 临时添加文件, 保存时修改下文件名即可, 例如将"newfile.txt" 改为"newfile.md" 即可.

![image](https://user-images.githubusercontent.com/3761968/182545650-e1575937-17ca-4fb5-9d3f-41c3416284e1.png)
