### ISSUE TITLE
UTF-8 encoding

### ISSUE THREAD

**Issue by anh-ai** [kalcaddle/kodbox#118]
How can I save content of files with UTF-8 coding?
Now, when I code Vietnamese character like: `Xin chào, tôi là Tuấn Anh` in to a PHP, HTML, MD,... files, after I saved, closed, reopen, it become: `Xin ch?o, t?i l? Tu?n Anh` (not correct)

Please allow to config save/open file in UTF-8 mode

My system: Windows 11, install WAMP package to run PHP server

**Comment by kalcaddle** [comment]
We didn't find the problem in our test;

The code is automatically recognized by default.
You can customize the display with the specified code or save with the specified code.


Please try on: https://demo.kodcloud.com/   demo/demo

![image](https://user-images.githubusercontent.com/3761968/183413127-d4c02bfd-45e6-4cc9-84a3-80b40ace4121.png)
