### ISSUE TITLE
FTP 挂载：无法连接到指定存储

### ISSUE THREAD

**Issue by DeathAndLife** [kalcaddle/kodbox#119]
![image](https://user-images.githubusercontent.com/51323917/183491569-dd8005d8-0a33-4b8c-bfd7-6444961de385.png)
Windows挂载没问题
![image](https://user-images.githubusercontent.com/51323917/183491798-51dd7aba-b05d-4e6b-84a6-1f6a168d8dcb.png)

**Comment by kalcaddle** [comment]
没遇到过该问题;   
连接失败, 检查网络连接性.
