### ISSUE TITLE
Can't copy file

### ISSUE THREAD

**Issue by vadlike** [kalcaddle/kodbox#12]
Can't copy file always get error.
https://raw.githubusercontent.com/vadlike/baberedition/main/chrome_2021-05-27_22-53-23.png

**Comment by vadlike** [comment]
If I copy the file and paste ctrl + v or right-click and paste, an error occurs. If I pinch on a file and drag it then it works or the "copy to" function

**Comment by kalcaddle** [comment]
image error!
