### ISSUE TITLE
webdav 不支持 super-productivity 同步

### ISSUE THREAD

**Issue by GalensGan** [kalcaddle/kodbox#123]
在 [super-productivity](https://github.com/johannesjo/super-productivity/releases) 中使用 kodbox 提供的 webdav 进行同步时，会报错，错误如下：
```
web-dav-sync.service.ts:55 Error: Not able to get rev for WebDAV
at n._getRevFromMeta (web-dav-sync.service.ts:117)
at n.<anonymous> (web-dav-sync.service.ts:48)
at Generator.next (<anonymous>)
at h (web-dav-api.service.ts:18)
at T.invoke (zone.js:372)
at Object.onInvoke (core.mjs:25476)
at T.invoke (zone.js:371)
at I.run (zone.js:134)
at zone.js:1276
at T.invokeTask (zone.js:406)
```
而我使用坚果云的 webdav 则没有这个问题。
同时希望 kodbox 可以提供跨域设置，这样方便 super-productivity 进行安卓同步，谢谢！

**Comment by kalcaddle** [comment]
已做兼容支持, 插件中心更新一下webdav插件即可.
同时网页端或pc端跨域问题也已处理;

测试: https://app.super-productivity.com/#/config
https://demo.kodcloud.com/index.php/plugin/webdav/kodbox/my/
demo/demo 
同步路径: /sync/super-productivity-backup.json   
 (须手动在个人空间新建 sync文件夹,再在下面新建空文件super-productivity-backup.json)
然后就可以同步了.

**Comment by GalensGan** [comment]
太速度了，谢谢！

**Comment by GalensGan** [comment]
测试了下，网页可以同步，但是用 super-productivity windows 版本时，只能向服务器发送数据，无法拉取服务器数据。提示找不到远程数据，如下图：
![image](https://user-images.githubusercontent.com/45629076/186897215-20e592c1-c34b-463a-95c0-865b54b05206.png)

**Comment by kalcaddle** [comment]
ok,后面再看下.
