### ISSUE TITLE
登陆超时

### ISSUE THREAD

**Issue by Gingmzmzx** [kalcaddle/kodbox#124]
有时候在编辑器编辑完之后没有关编辑器，过段时间之后再编辑保存就提示登陆超时。但是再登陆不要紧，刚刚撸的代码不就白撸了。
希望大佬能够解决一下谢谢

**Comment by kalcaddle** [comment]
默认session会话有效期是四小时，连续该时间内没有任何操作才会需要重新登录，正常来说是足够的。


解决方法有2：
1.登陆时勾选自动登录
2.修改session超时时间，参考config/setting.php 变量覆盖写在setting_user.php中

杭州可道云网络有限公司


------------------ 原始邮件 ------------------
发件人: xzystudio ***@***.***&gt;
发送时间: 2022年8月28日 06:56
收件人: kalcaddle/kodbox ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [kalcaddle/kodbox] 登陆超时 (Issue #124)





 
有时候在编辑器编辑完之后没有关编辑器，过段时间之后再编辑保存就提示登陆超时。但是再登陆不要紧，刚刚撸的代码不就白撸了。
 希望大佬能够解决一下谢谢
