### ISSUE TITLE
Text editor encoding problem

### ISSUE THREAD

**Issue by RallyTuning** [kalcaddle/kodbox#127]
The text editor keep open any file with encoding `CP932` instead of `UTF-8` or in the `actually file encoding`.

**Comment by kalcaddle** [comment]
Code recognition cannot ensure complete correctness. When the code conforms to a certain code, the code will be returned. Maybe a piece of text itself conforms to multiple coding rules.




At this time, you can customize the identification priority order according to your needs. /config / config.php
`$config['checkCharset'] = '';`
Write the modified content to `config/setting_ In user.php`

**Comment by RallyTuning** [comment]
But in this way, the next update will replace this page. Every update i need to edit again the page?
I suggest you to put `UTF-8` as standard, considering is worldwide. `CP932` is used only in China.
This issue will affect every other country in the world.

Anyway, i tried with many text file, also by open an empty one. It open EVER with `CP932`.

**Comment by kalcaddle** [comment]
`config/setting_user.php`  won't be replaced.

Can you provide some test files? Let's optimize them

**Comment by RallyTuning** [comment]
Solved in this way:

1. open the file and change the encoding to utf-8
2. fix all wrong characters
3. save
4. convert to utf-8 using the function in the text editor (anyway, this is bugged too because the mouse hover make disappear the menu in the convert section when the mouse hit the scrollbar)

After that, i have tested on 3 different installations and this happens just one more time by just copy paste the content of the original file. Then never happen again in more than 10 test. I will update you in case i found more info.

In case i need, i have to write `$config['checkCharset'] = 'UTF-8';` in `config/setting_user.php`, that's right?

**Comment by kalcaddle** [comment]
that's right
