### ISSUE TITLE
Excel Plugin

### ISSUE THREAD

**Issue by vincentpricex** [kalcaddle/kodbox#129]
After update 1.34 excel plugin won't let me edit xsls files. Givin me save fuction is off error

**Comment by kalcaddle** [comment]
Please provide more error and server information.
Screenshots of errors, etc

**Comment by vincentpricex** [comment]
![Screen Shot 2022-09-13 at 09 07 58](https://user-images.githubusercontent.com/49900792/189822743-319acd76-353f-4d79-8c64-4bd7b652f88c.png)

**Comment by kalcaddle** [comment]
Currently, saving is not supported, and the function is not perfect
This has been the case since the release of the plug-in, and the save function will be supported in the future

**Comment by vincentpricex** [comment]
Its was working perfectly fine 1.33. i used almost a month without problem or any bug.. I guess you guys just take off that from free version.. not fair.

**Comment by kalcaddle** [comment]
We confirm that the office preview plug-in has not yet added the save function.
You may use other ways to open it, or you may use a PC client to open it through local office software



The recommended PC client can edit and save almost all file formats through local software, as long as you have corresponding editing software locally.


https://github.com/kalcaddle/kodbox/releases/tag/1.33.01

**Comment by vincentpricex** [comment]
What you mean PC client?

**Comment by kalcaddle** [comment]
https://kodcloud.com/download/

here: 
win:  https://static.kodcloud.com/update/client/kodcloud/kodcloud%20Setup%200.4.8.exe
mac: https://static.kodcloud.com/update/client/kodcloud/kodcloud-0.4.8.dmg

**Comment by vincentpricex** [comment]
Let me try and let you know i turn down all reader plugin. One more question. How to add OCR on this?

**Comment by kalcaddle** [comment]
OCR is not spport now.

**Comment by vincentpricex** [comment]
I seen that OCR plugin i guess for enterprise. Do you have any idea i can buy that plugin ?

**Comment by vincentpricex** [comment]
> https://kodcloud.com/download/
> 
> here: win: https://static.kodcloud.com/update/client/kodcloud/kodcloud%20Setup%200.4.8.exe mac: https://static.kodcloud.com/update/client/kodcloud/kodcloud-0.4.8.dmg
with the app works fine.

**Comment by vincentpricex** [comment]
One more question about the app. Those app's open source? how to reach source of code for apps ?

**Comment by vincentpricex** [comment]
Thanks. I planned to buy this script extended version or you name it version. Couldn't find connection or price for it.

**Comment by kalcaddle** [comment]
> Thanks. I planned to buy this script extended version or you name it version. Couldn't find connection or price for it.
contact us: support@kodcloud.com

**Comment by vincentpricex** [comment]
> > Thanks. I planned to buy this script extended version or you name it version. Couldn't find connection or price for it.
> > contact us: [support@kodcloud.com](mailto:support@kodcloud.com)

| did 2 weeks ago, no respond. I will send one more email.

**Comment by kalcaddle** [comment]
also can contact: tony@kodcloud.com

**Comment by vincentpricex** [comment]
sent 2 of the e-mail. Thanks much
