### ISSUE TITLE
部署在32位armv7的路由器上，如果打开某个文件夹里面有大于2GB的文件会直接报错，以前kodexplorer没这个问题

### ISSUE THREAD

**Issue by yinzhefuyun** [kalcaddle/kodbox#13]
出错了! (warning!)
../getid3/getid3.lib.php[1758]; getid3_lib->getFileSizeSyscall();
Call to undefined function ctype_digit()

**Comment by kalcaddle** [comment]
php 缺少ctype扩展; 安装一下即可.
