### ISSUE TITLE
Cache for preview images

### ISSUE THREAD

**Issue by RallyTuning** [kalcaddle/kodbox#131]
Every time i enter in a folder with many images, the app keep download the preview of them. Causing lag and long loading time. There is a way to use a cache for image previews? At least 1 hour cache

**Comment by kalcaddle** [comment]
Browser: At present, image thumbnails and open previews will be cached, and new images will be obtained only when the image content changes. Unless the cache is cleared manually, image thumbnails are always available in other cases

IOS App: Same as above.
Android App: under reconstruction, some functions need to be optimized.


What device are you accessing through, if it is a browser, you can compare and test the demo.
http://demo.kodcloud.com   demo/demo

**Comment by RallyTuning** [comment]
I am using Chrome on Windows PC and Chrome on Android. But on both i get the same result. Every images are downloaded again every time i enter in the folder. (also the app backgroud is downloaded every time). What i can do?
