### ISSUE TITLE
反馈bug 移动端 打开自动备份的时候 app 崩溃

### ISSUE THREAD

**Issue by happyi** [kalcaddle/kodbox#132]
如题
软件版本：v1.2.2.1354
手机品牌 ：小米11
android 版本 12

另外再问下 移动端源码开放吗，这个bug我也可以帮忙修复

**Comment by kalcaddle** [comment]
已转交给App同学,
目前安卓版本App正在原生重构中,近期发布(之前是用的RN架构). iOS版原生已发布.
App暂未开源,后续会考虑.
