### ISSUE TITLE
文件夹名称显示错误

### ISSUE THREAD

**Issue by timongh** [kalcaddle/kodbox#134]
### 复现

1. 创建一个阿里云 OSS 存储，名为 “oss-0”，设为默认
    <img src="https://user-images.githubusercontent.com/46739861/192579817-fe2cfd26-1bc8-47fc-9c47-902c93a4e728.png" width="250"/>

2. 在这个 OSS 里新建文件夹，名为“0”
3. 文件名显示为“oss-0“，实际存储名称为”0“。此时也无法新建名为 “oss-0“ 的新文件夹
    <img src="https://user-images.githubusercontent.com/46739861/192581234-e369948f-c531-419e-ab83-5901e595702d.png" width="250"/>
    <img src="https://user-images.githubusercontent.com/46739861/192581424-3d2e9166-8eec-4545-be2d-843e334f64e3.png" width="250"/>

### 环境

```
程序版本: 1.30 免费版
build: 03
```

**Comment by kalcaddle** [comment]
文件夹名称为0,判断有些异常, 后续兼容一下.
只要不是0,应该都没问题.
