### ISSUE TITLE
无法从安卓客户端登录由阿里云 serveless 部署的服务

### ISSUE THREAD

**Issue by timongh** [kalcaddle/kodbox#135]
我使用的是阿里云的 start-fc-kodbox 模板，在函数计算部署的应用。

我能使用自动生成的网址正常登录网页客户段和 windows 客户端，但将同样的网址填入安卓端的“服务器站点”却只有提示“请输入正确的服务器站点 url“。

自动生成的网址看起来像这样：http://aaa-bbb-ccc.fc-nas-filemgr-abcd.1111111111111111.cn-shengzhen.fc.devsapp.net

kodbox 版本：1.30.03
安卓客户端版本：2.0.1

**Comment by kalcaddle** [comment]
可能是url校验或者获取站点配置接口异常了.
Android App正在全面重构中,近期发布
