### ISSUE TITLE
手机web页面，文件列表无法上下滑动

### ISSUE THREAD

**Issue by jameszhang023** [kalcaddle/kodbox#14]
服务器系统: Windows NT ACCOUNTING-PC 6.1 build 7601 (Windows 7 Professional Edition Service Pack 1) i586
服务器软件: Apache/2.4.37
PHP版本: PHP/5.5.30
数据库: MySQL/5.5.54-log

手机端浏览器：Chrome，Edge
Kodbox V1.20.0528

**Comment by kalcaddle** [comment]
没测试出该情况.
对比测试下官网demo.  

提供一下手机操作系统及版本, 浏览器类型及版本.

**Comment by jameszhang023** [comment]
手机操作系统版本:
![Screenshot_2021-06-07-20-37-48-780_com android settings](https://user-images.githubusercontent.com/22817906/121019002-9a8dab00-c7d1-11eb-935f-6ffff98e020a.jpg)

手机浏览器版本:
![Screenshot_2021-06-07-20-39-34-438_com microsoft emmx](https://user-images.githubusercontent.com/22817906/121019038-a4afa980-c7d1-11eb-8973-265536017f78.jpg)
![Screenshot_2021-06-07-20-40-23-671_com google android gms](https://user-images.githubusercontent.com/22817906/121019060-aaa58a80-c7d1-11eb-9fc4-acf8cc0bcbd4.jpg)

**Comment by nemohsia** [comment]
浏览器兼容问题，已做调整，下个版本更新。
