### ISSUE TITLE
windows server 环境下由于 convert 冲突导致无法配置文件封面生成功能

### ISSUE THREAD

**Issue by GalensGan** [kalcaddle/kodbox#141]
由于 windows server 中自带的 convert.exe 与 imageMagick 中的 convert.exe 冲突，在进行文件封面生成设置时，连接测试时会提示 `convert 调用失败`。即使输入 imageMagick 的全路径也无效。
请问该如何处理呢？

**Comment by kalcaddle** [comment]
https://bbs.kodcloud.com/d/2892-windows
可以自行配置一下环境变量.
