### ISSUE TITLE
IIS 下部署webdav要怎么配置？

### ISSUE THREAD

**Issue by sillycat3** [kalcaddle/kodbox#142]
Kodbox界面能打开webdav功能，且通过raidrive能登录账号，但数据没法和服务器传输，文件夹都是空。
iis 下还需要配置那些选项？

**Comment by kalcaddle** [comment]
IIS 需要自行配置允许http头(会过滤删除掉部分需要用到的http头)
或者推荐使用nginx+php组合,性能更好;  宝塔面板一键搭建比较方便.
