### ISSUE TITLE
可以文件直接mv后同步么？

### ISSUE THREAD

**Issue by dingiso** [kalcaddle/kodbox#143]
社区的各位大佬好，想求助一下，我现在有一个文件夹不想使用网络上传而是直接mv到可道云的内部存储中，我之前使用 nextcloud 是有 filescan 的功能，请问可道云支持这样的功能么

**Comment by kalcaddle** [comment]
可以在地址栏进入磁盘物理路径, 添加收藏,后续可以直接管理物理磁盘(类似于kodexplorer的功能)
导入的话: 复制文件夹粘贴到个人空间或kod下的文件夹就等于导入.
