### ISSUE TITLE
obsidian使用可道云的webdav同步会出错

### ISSUE THREAD

**Issue by 1912377458** [kalcaddle/kodbox#144]
obsidian使用`remote save`插件通过可道云的webdav同步会出错，第一次同步正常，第二次同步就会出错
<img width="251" alt="image" src="https://user-images.githubusercontent.com/73117213/202226575-ae5ee4e4-fc7c-4866-aaa5-9295a165ad5d.png">
揣测可能是文件重复的情况下，上传会出错？

**Comment by kalcaddle** [comment]
![image](https://user-images.githubusercontent.com/3761968/206139494-cb5c9c43-75ad-4e4a-947a-5d5f13662b4b.png)

没测试出该问题. 将webdav更新到最新版看看.

**Comment by 1912377458** [comment]
> ![image](https://user-images.githubusercontent.com/3761968/206139494-cb5c9c43-75ad-4e4a-947a-5d5f13662b4b.png)
> 
> 没测试出该问题. 将webdav更新到最新版看看.

我刚测试了一下，新建一个仓库，将其他仓库的文件复制到当前文件，然后使用`Remote Save`插件进行同步，第一次同步是正常的，但是第一次同步后再点击同步就会出错
