### ISSUE TITLE
删除图片时，没有删除缩略图

### ISSUE THREAD

**Issue by fanxin92** [kalcaddle/kodbox#145]
删除图片时，没有删除图片所在目录下的缩略图，建议优化一下。

或者把缩略图存放在专用文件夹，方便辨识。

**Comment by kalcaddle** [comment]
缓存文件目前没加入自动删除; 可以手动清理
地址栏输入{source:0}; 进入到系统目录,然后进入systemPath/systemTemp/thumb/, 这下面都是图片缩略图.
