### ISSUE TITLE
设置不能保存，分享链接图片全部是一张

### ISSUE THREAD

**Issue by uwings** [kalcaddle/kodbox#147]
已知两个错误：
1. 程序覆盖一次后短暂修复了设置不能保存问题， 表现为在不同 tab 保存时会全部跳转到安全页面，并且不保存设置
2. 分享的图片目录，通过外部分享链接分享后，访问显示所有图片预览和大图都是一张。  但文件名和文件大小是对的

**Comment by kalcaddle** [comment]
1. 已解决, 更新到最新版即可.
2. 只有图片本身尺寸大小比较小时,才会预览图和大图是一张. 具体如何测试可以详细描述一下.
