### ISSUE TITLE
批量下载文件时，压缩包中只有一个文件是完整的

### ISSUE THREAD

**Issue by GalensGan** [kalcaddle/kodbox#149]
当选择多个 pdf 文件后，点击下载，kodbox 会将选择的文件打包，然后开始下载，但是下载的结果中只有一个文件是完整的，其它文件都是 0 k，如下图所示
![image](https://user-images.githubusercontent.com/45629076/216215779-c8becafe-7a3f-4d3f-af2d-da4026aade52.png)

**Comment by kalcaddle** [comment]
没遇到过该问题, 方便的话提供个站点和账号我们测试一下.warlee#kodcloud.com
