### ISSUE TITLE
视频下载完毕才能打开，不是边下载边预览

### ISSUE THREAD

**Issue by tangjiahao2001** [kalcaddle/kodbox#151]
前几天更新了kodbox的docker版本之后，今天打开一个500M的视频用了好久的时间，貌似需要把文件下载完毕之后才能够查看。但是在之前的版本并没有遇到这个问题

**Comment by kalcaddle** [comment]
web端应该不会,mp4,flv,mov等格式浏览器支持的都是变下边播的. 
pc客户端打开的话会先缓存到本地再播放.
