### ISSUE TITLE
开源版 V1.37.03 在部分文件夹下载的时候会出现报错。

### ISSUE THREAD

**Issue by Double517** [kalcaddle/kodbox#152]
![image](https://user-images.githubusercontent.com/11642282/223310156-85a2c6b6-d2d4-421c-bd0c-4ce4083f4580.png)
点击下载的时候会出现如下报错
![image](https://user-images.githubusercontent.com/11642282/223310243-96fef439-2a12-421e-9cae-32dcd26069b5.png)

**Comment by Double517** [comment]
![image](https://user-images.githubusercontent.com/11642282/223310470-3885cd9b-7651-4549-a3bb-3be1efea2d44.png)
不知道为什么升级的版本比官网的版本还要高

**Comment by kalcaddle** [comment]
客户端压缩下载,下载失败,很可能请求下载服务器返回异常了
