### ISSUE TITLE
大量高清图片上传之后进入文件夹访问，内存会直接吃满，是否支持设置同时最大缩略图生成数量？

### ISSUE THREAD

**Issue by javed119** [kalcaddle/kodbox#153]
![1680704055-759271-image](https://user-images.githubusercontent.com/35559286/230274811-54840016-5c22-4320-b66f-4288eb30b7e6.png)
如上图，当进入一个高清图片文件夹时（单张图片约8M，均为首次上传，没有缩略图），生成缩略图会导致内存满载100%（上图仅表示内存占用多），生成完成后会降低，但中途可能应用可能会卡死无法恢复，需要重启docker容器。
是否能支持设置缩略图并发？

**Comment by kalcaddle** [comment]
缩略图首次生成后会缓存起来,后续访问不需要再生成;
界面已经做了优化的: 图片懒加载, 在界面内的图片才会请求缩略图.
