### ISSUE TITLE
can't open file after updating to the lastest version

### ISSUE THREAD

**Issue by Rico556** [kalcaddle/kodbox#154]
![image](https://user-images.githubusercontent.com/57744340/230608865-23f3b51a-9b40-4557-ba37-f9a0ca77db69.png)

**Comment by Rico556** [comment]
Hi,
I update to the latest version today. After that, I can't open any file in kodbox.

**Comment by Rico556** [comment]
![image](https://user-images.githubusercontent.com/57744340/230609229-69cea0c7-0e17-479f-898e-b9658ad700d8.png)

**Comment by kalcaddle** [comment]
We have never encountered this situation, it may be a server compatibility problem, or the program code is incomplete. Download the update package, manually decompress it and cover it in the program directory to try.

https://static.kodcloud.com/update/update/update-1.38.zip
