### ISSUE TITLE
把日期格式改成YYYY.MM.DD后系统会一直请求数据库进行REPLACE操作

### ISSUE THREAD

**Issue by L-Bigbig** [kalcaddle/kodbox#156]
最近看系统监控数据发现磁盘每秒写入一直是几百Kb，持续好几天，就开始查是什么程序在持续写入数据。发现是mysql的进程在持续写入。再往下差就发现是可道云在进行REPLACE操作，更新频率非常高，几乎1秒1次；

以下是查询到的操作日志文件：
SELECT * FROM `system_option` WHERE ( `type` = 'System.autoTask' );
SELECT * FROM `system_option` WHERE ( `type` = 'System.taskList' );
REPLACE INTO `system_option` (`type`,`key`,`value`,`modifyTime`,`createTime`) VALUES ('System.autoTask','lastRun',1681781701,1681781701,1681781701);
REPLACE INTO `system_option` (`type`,`key`,`value`,`modifyTime`,`createTime`) VALUES ('System.autoTask','running','1',1681781701,1681781701);

我并没有设置任何自动任务，可道云系统也是刚安装的。更改时间格式后发现【服务器管理页面】-【服务器信息】-【服务器时间】时间格式一直在YYYY.MM.DD与YYYY-MM-DD之间频繁跳动。
更改回默认格式再“数据库异常数据清理”后恢复正常

**Comment by kalcaddle** [comment]
正常现象, 和日期格式无关.
是后台运行计划任务每个周期更新运行状态用的.  后台计划任务每检测一次sleep 2s
