### ISSUE TITLE
更新至 v1.38.06 后，WebDav 突然不支持 super-productivity 同步了

### ISSUE THREAD

**Issue by GalensGan** [kalcaddle/kodbox#157]
在更新至 v1.38.06 后，WebDav 突然不支持 super-productivity 同步了，原因和 #123 一样

复现：
super-productivity 网页版：https://app.super-productivity.com/#/config
webDa：https://demo.kodcloud.com/index.php/plugin/webdav/kodbox/my/
账号密码：demo/demo
同步路径：/sync/super-productivity-backup.json

**Comment by kalcaddle** [comment]
1.38 调整window10 office文件编辑失败问题, 和这个productivity 部分检测互斥了.;
已做兼容. 两种情况都支持了

**Comment by imysl0** [comment]
谢谢你们，我的super-productivity也可以同步啦
