### ISSUE TITLE
更新1.9以后使用goodsync同步出错

### ISSUE THREAD

**Issue by lthwk** [kalcaddle/kodbox#158]
更新1.9以后使用**goodsync**同步出错

1. 可以正常读出目录及文件，但同步工程中会报无法找到文件，发现服务器**目录名**被修改的乱七八糟。
2. **1.7-1.8版本可以正常同步。**

**Comment by kalcaddle** [comment]
没发现该问题, window10/mac; goodsync <=> kod的目录;同步正常;

尝试升级到最新版再测试看看.还有问题的话:
麻烦提供一下服务端: php版本/kod版本/webdav插件版本;  客户端:操作系统及版本/goodsync版本/报错详情.
方便外网访问的话,麻烦提供个服务器地址及账号我们测试一下; 可以发送到 warlee#kodcloud.com
