### ISSUE TITLE
app外链建议

### ISSUE THREAD

**Issue by gundamf6** [kalcaddle/kodbox#160]
在最新版app中，数据库中的文件可以直接选择“分享外链”，但是物理路径下的文件不能直接选择“分享外链”。在web端，无论数据库还是物理路径下的文件都支持直接选择“分享外链”。
希望能够完善app端的分享功能

**Comment by gundamf6** [comment]
![1684009356-538436-screenshot-2023-05-14-04-21-42-37-7bd30d668d4a2dc0086b219f01a8d72e](https://github.com/kalcaddle/kodbox/assets/47359398/fed73af1-8399-489e-be86-200c7b7a56ab)
![1684009365-882575-screenshot-2023-05-14-04-22-08-78-7bd30d668d4a2dc0086b219f01a8d72e](https://github.com/kalcaddle/kodbox/assets/47359398/d27dd998-7b0e-4c5c-9efd-c2c9b48f0f36)
![1684009595-156452-img-20230514-042610](https://github.com/kalcaddle/kodbox/assets/47359398/1fddce31-303b-4d89-9b64-f42bceefafad)

**Comment by kalcaddle** [comment]
iOS 已支持,Android 下个版本支持.
