### ISSUE TITLE
功能需求：pdf 阅读插件支持缓存

### ISSUE THREAD

**Issue by GalensGan** [kalcaddle/kodbox#162]
我发现每打开一次 PDF，都会重新请求数据，对于有些比较大的 PDF，比较费时间。希望在线打开后，可以缓存它，这样下次就直接打开了。

**Comment by kalcaddle** [comment]
目前就是支持的. 看看浏览器是不是关闭了缓存.或者看看服务器做了相关header处理.
可以对比官网demo.
