### ISSUE TITLE
文件封面生成 psd 文件无效

### ISSUE THREAD

**Issue by 93Alliance** [kalcaddle/kodbox#163]
![image](https://github.com/kalcaddle/kodbox/assets/33192459/1c54f7c8-3f08-4a24-ac14-5a6c341dd672)

测试pdf是有效的，但是psd文件无效。

已经检查系统 ffmpeg和convert是有效的。

**Comment by kalcaddle** [comment]
1. 可能是文件有特殊功能,转换组件不支持部分特性
2. convert看看是否为最新版.

可以在命令行手动转换试试看.
