### ISSUE TITLE
很多文件被写入MD5、Content-Disposition、Content-Type，导致文件无法打开。

### ISSUE THREAD

**Issue by Vincent-LvZY** [kalcaddle/kodbox#164]
如题，很多文件只能用Notepad打开后删除前3行和最后一行的值文件才能正常使用，当前的系统版本为：1.40.03
这应该如何解决？
![1](https://github.com/kalcaddle/kodbox/assets/45941480/8b8e3d12-7f5d-4a30-8b76-885ec58ba8f3)
![2](https://github.com/kalcaddle/kodbox/assets/45941480/f229f970-56d5-4c9c-810c-d02135f82891)

**Comment by kalcaddle** [comment]
没遇到过该问题。文件来源是什么，浏览器上传，PC端上传还是APP，还是其他情况。描述一下产生出错文件的详细步骤，同时可以对比测试一下官网demo看看。



杭州可道云网络有限公司


------------------ 原始邮件 ------------------
发件人: Vincent-LvZY ***@***.***&gt;
发送时间: 2023年5月26日 23:05
收件人: kalcaddle/kodbox ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [kalcaddle/kodbox] 很多文件被写入MD5、Content-Disposition、Content-Type，导致文件无法打卡。 (Issue #164)





 
如题，很多文件只能用Notepad打开后删除前3行和最后一行的值文件才能正常使用，当前的系统版本为：1.40.03
 这应该如何解决？

**Comment by Vincent-LvZY** [comment]
目前用的是PC端的傲游7.0上传的，有的文件没有被修改，有的文件就多出来。
我也是昨天发现有的STL模型文件出错，当时没有在意就删除了重新导出一个新的STL，今天发现照片也没法打开，然后用NotePad发现前后都多出来4行代码。
我现在只能把文件压缩打包上传。

**Comment by kalcaddle** [comment]
OK，我们看一下。
提供一下操作系统及版本，浏览器详细版本，可能是浏览器兼容问题导致。可以对比测试一下Chrome，edge。


麻烦再提供一个上传会出错的文件。





杭州可道云网络有限公司


------------------ 原始邮件 ------------------
发件人: Vincent-LvZY ***@***.***&gt;
发送时间: 2023年5月26日 23:35
收件人: kalcaddle/kodbox ***@***.***&gt;
抄送: warlee ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [kalcaddle/kodbox] 很多文件被写入MD5、Content-Disposition、Content-Type，导致文件无法打开。 (Issue #164)





 
目前用的是PC端的傲游7.0上传的，有的文件没有被修改，有的文件就多出来。
 我也是昨天发现有的STL模型文件出错，当时没有在意就删除了重新导出一个新的STL，今天发现照片也没法打开，然后用NotePad发现前后都多出来4行代码。
 我现在只能把文件压缩打包上传。

**Comment by Vincent-LvZY** [comment]
![KOD Version](https://github.com/kalcaddle/kodbox/assets/45941480/3d9a650d-d40b-432d-a187-c6d3a7261ec3)
![System Version](https://github.com/kalcaddle/kodbox/assets/45941480/8c6fb59c-4bb6-47b1-8c8a-447dea00ecaf)
![Maxthon Version](https://github.com/kalcaddle/kodbox/assets/45941480/df1a1510-5814-407c-bf38-b5f521d92711)
![SLDPRT修复前](https://github.com/kalcaddle/kodbox/assets/45941480/9d212a64-46dc-4e13-b63d-803921ec5ea0)
![SLDPRT修复后](https://github.com/kalcaddle/kodbox/assets/45941480/657ff24a-d812-4b3a-a116-5dc7191f9538)
![STL修复前](https://github.com/kalcaddle/kodbox/assets/45941480/4b1512bf-58cf-4e59-b9f3-d16078906418)
![STL修复后](https://github.com/kalcaddle/kodbox/assets/45941480/90e5eb69-1aac-4c26-b21a-4637c94ca7f4)

**Comment by Vincent-LvZY** [comment]
这个是我能找到的有问题的文件，之前出现问题的一些文件我现在都做了压缩打包处理。
目前发现出现问题的类型有:txt、cfg、png、jpg、svg、ini等.
[STL.zip](https://github.com/kalcaddle/kodbox/files/11576922/STL.zip)

**Comment by kalcaddle** [comment]
> 这个是我能找到的有问题的文件，之前出现问题的一些文件我现在都做了压缩打包处理。 目前发现出现问题的类型有:txt、cfg、png、jpg、svg、ini等. [STL.zip](https://github.com/kalcaddle/kodbox/files/11576922/STL.zip)



你给的压缩包中几个文件,本身文件就有问题, 包含了下载时返回的header头部分.
```
--------------------------d72104941613a88b
Content-Disposition: form-data; name="UPLOAD_FILE"; filename="V0.2_Handle_B_x2.STL"
Content-Type: application/vnd.ms-pkistl
```
<img width="1133" alt="image" src="https://github.com/kalcaddle/kodbox/assets/3761968/0aa13da5-f9b0-4406-9854-02fdeeb754da">


提供几个上传会出问题,但文件本身是好的文件.

**Comment by kalcaddle** [comment]
> 这个是我能找到的有问题的文件，之前出现问题的一些文件我现在都做了压缩打包处理。 目前发现出现问题的类型有:txt、cfg、png、jpg、svg、ini等. [STL.zip](https://github.com/kalcaddle/kodbox/files/11576922/STL.zip)

你好,收到麻烦回复一下.谢谢.

**Comment by Vincent-LvZY** [comment]
是的，只能每次删除前几行文字和最后几行，然后保存之后就可以用了。今天又发生了一个诡异的情况，就是上传的TXT文件不显示中文了，换过浏览器，都一样。
![屏幕截图 2023-06-01 220448](https://github.com/kalcaddle/kodbox/assets/45941480/4da9c12b-c98a-4c3a-a083-41de4852cf90)

**Comment by Vincent-LvZY** [comment]
以前的老文件没有问题。。。
![屏幕截图 2023-06-01 220622](https://github.com/kalcaddle/kodbox/assets/45941480/f2c1566b-8178-4c7a-a4a3-e4297fdaf588)

**Comment by Vincent-LvZY** [comment]
昨天已经跟你们电话联系了，确认就是挂在WebDAV导致的。重新把存储换成本机就没事了。

**Comment by kalcaddle** [comment]
> 昨天已经跟你们电话联系了，确认就是挂在WebDAV导致的。重新把存储换成本机就没事了。

感谢您的协助排查。问题已经定位，是挂载的威联通webda服务器对上传为form方式处理有点问题(文件内容识别异常，多出了部分header)，目前已经处理为流方式上传。已兼容了这种情况，插件中心更新下webdav插件即可。可以继续使用这种模式。

**Comment by Vincent-LvZY** [comment]
目前看到的是1.59，需要等推送么吧。
![屏幕截图 2023-06-03 210954](https://github.com/kalcaddle/kodbox/assets/45941480/71c094df-664a-4a29-bc50-3bc2a977b970)

**Comment by kalcaddle** [comment]
昨天推送了，1.59已经是兼容的了。可以测试一下看看

**Comment by Vincent-LvZY** [comment]
好的，我先试试把系统备份一下。然后试试看，如果没有问题了我就不继续反馈了。
辛苦了。

**Comment by kalcaddle** [comment]
好的，感谢。
非常抱歉该兼容性问题给您带来的困惑。已出问题的文件还需要你手动清理或覆盖一下。
