### ISSUE TITLE
默认编辑器查找替换功能无法正常使用

### ISSUE THREAD

**Issue by Rico556** [kalcaddle/kodbox#165]
![image](https://github.com/kalcaddle/kodbox/assets/57744340/2c232212-1660-4683-9790-03d5f08120c6)

版本 1.40.03

查找栏里会出现删不完的"**"

**Comment by kalcaddle** [comment]
默认替换时,会将选中内容放置在replaceFrom中, 那些**应该就是选中的文字内容.
ctrl+a全选,delete即可.
