### ISSUE TITLE
加载太多图片文件导致卡死

### ISSUE THREAD

**Issue by jdysya** [kalcaddle/kodbox#167]
当打开一个有很多图片文件的文件夹时，整个服务器都会直接卡死，导致部署在服务器上的其他服务也无法使用

**Comment by kalcaddle** [comment]
https://doc.kodcloud.com/v2/#/help/qa

Q: 文件夹很多图片时加载慢,服务器资源占用很高怎么办
A: 针对该问题kod本身是做了很多优化的.
缓存处理: 生成缓存+浏览器缓存; 首次访问时服务器会自动生成缩略图(后续不再生成),访问时浏览器会缓存(url不变,就不会再请求),所以正常来说只是首次会慢一点; 后续访问都是比较快的.
按需请求: 浏览器访问时是懒加载的,只有在屏幕显示区域内的图片文件才会请求缩略图展示.页面滚动时自动触发请求.
生成速度取决于服务器硬件配置, 配置较低的会稍微慢一些.如果服务器配置太低,占用资源太多怎么办? 可以关闭缩略图显示: 右键文件区域--更多--显示选项;关闭--开启图片缩略图; 保存即可.
