### ISSUE TITLE
docker安装失败，mysql连接有问题

### ISSUE THREAD

**Issue by hguoguo** [kalcaddle/kodbox#169]
docker启动命令如下：
docker run -d -p 7080:80 --name=kodbox -v /home/huaguoguo/docker/kodbox/data:/var/www/html -e MYSQL_DATABASE=kodbox -e MYSQL_USER=root -e MYSQL_PASSWORD=123456 -e MYSQL_SERVER=192.168.0.105 -e MYSQL_PORT=3806 kodcloud/kodbox
![image](https://github.com/kalcaddle/kodbox/assets/28341993/c923ca42-46c6-4bae-9629-04d8301d2392)

mysql版本为8.0.33，验证方式为mysql_native_password，已确认连接信息无误

**Comment by zbingege** [comment]
near "(": syntax error[ SQL语句 ] :(SELECT sourceID,targetID,size FROM `io_source` where `parentID`=0 and `targetID`=1 and `targetType`=1 limit 1)
系统错误，
我是这个问题不知道你解决了吗？

**Comment by hguoguo** [comment]
> near "(": syntax error[ SQL语句 ] :(SELECT sourceID,targetID,size FROM `io_source` where `parentID`=0 and `targetID`=1 and `targetType`=1 limit 1) 系统错误， 我是这个问题不知道你解决了吗？

docker logs没有发现这种日志，请问容器内部有详细的日志吗

**Comment by hguoguo** [comment]
可能是我误改了配置，恢复后重启容器，现在报错是：
<img width="855" alt="image" src="https://github.com/kalcaddle/kodbox/assets/28341993/1d6ab115-930c-4340-9c57-13ea783ce08d">

**Comment by Otajonov** [comment]
@hguoguo Hi friend. I needed just to reinstall, now it is working. !! But all data will be lost. I think it is database structure conflict which new version is requiring new columns that not existed in your old user row.

**Comment by hguoguo** [comment]
> 

没明白你的意思，我在数据库create schema kodbox collate utf8mb4_bin; 没有其他操作

**Comment by kalcaddle** [comment]
> near "(": syntax error[ SQL语句 ] :(SELECT sourceID,targetID,size FROM `io_source` where `parentID`=0 and `targetID`=1 and `targetType`=1 limit 1) 系统错误， 我是这个问题不知道你解决了吗？

sqlite的一个兼容问题,已兼容处理. 下载最新版安装即可.

**Comment by KodCloud-dev** [comment]
> 
相同步骤无法复现问题，请清空挂载目录，docker run 运行时去掉所有环境变量试下
