### ISSUE TITLE
内网穿透404异常

### ISSUE THREAD

**Issue by gundamf6** [kalcaddle/kodbox#171]
设备为玩客云armv7
系统为armbian
kodbox为最新版，环境为docker 
服务器软件: nginx/1.22.1
PHP版本: PHP/8.1.18
数据库: SQLite3
缓存: File
后台显示内网穿透正常，但是打开外网连接显示404。
是否因为docker环境下，docker容器的内网IP与实际IP不符造成的。

**Comment by gundamf6** [comment]
服务器名: _服务器IP: 172.17.0.3服务器时间: 2023-06-10 02:54:57持续运行时间: 22 天 15 小时 39 分钟 57 秒
服务器系统: Linux bb87ec0e721b 6.3.1-meson #1 SMP Sun Apr 30 23:32:26 UTC 2023 armv7l
服务器软件: nginx/1.22.1PHP版本: PHP/8.1.18
网站路径: /var/www/html/
在docker环境中 服务器IP为172.17.0.3
实际IP为192.168.0.31

**Comment by kalcaddle** [comment]
docker 内部穿透兼容问题. 
目前已兼容, 插件中心升级一下内网访问插件再试试看.
