### ISSUE TITLE
我的电脑中“设备与驱动器”的kodcloud图标能否取消？

### ISSUE THREAD

**Issue by Allenlee521** [kalcaddle/kodbox#172]
尝试了删除注册表，无法解决，软件设置中并无关闭选项
![image](https://github.com/kalcaddle/kodbox/assets/70263724/b8dc5459-3ac0-4d51-b573-49889ad157ed)

**Comment by kalcaddle** [comment]
后续加以一个配置选项关闭.

**Comment by ninggege66** [comment]
一直都没有改
