### ISSUE TITLE
docker部署后，如何访问其他文件夹？

### ISSUE THREAD

**Issue by wangweitung** [kalcaddle/kodbox#173]
docker部署后，如何访问其他文件夹？

**Comment by kalcaddle** [comment]
地址栏输入物理地址即可访问.
前提是没有做防跨站设置.

**Comment by wangweitung** [comment]
> 地址栏输入物理地址即可访问.
> 前提是没有做防跨站设置.

Docker如何取消防跨站设置？找了半天没找到
