### ISSUE TITLE
拖拽上传的时候会显示两个文件

### ISSUE THREAD

**Issue by zJanch** [kalcaddle/kodbox#174]
如图所示
![bug](https://github.com/kalcaddle/kodbox/assets/53729565/05d0ffe5-33d7-40d7-a264-58026a23d33d)

**Comment by kalcaddle** [comment]
你好


什么情况下出现，描述一下详细步骤，并提供一下运行环境信息


kod版本：
浏览器应该及版本：



杭州可道云网络有限公司


------------------ 原始邮件 ------------------
发件人: zJanch ***@***.***&gt;
发送时间: 2023年6月18日 21:19
收件人: kalcaddle/kodbox ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [kalcaddle/kodbox] 拖拽上传的时候会显示两个文件 (Issue #174)





 
如图所示

**Comment by zJanch** [comment]
文件上传使用拖进来会创建两个上传任务，要是点击选择文件按钮上传的就一个
kod版本：Powered by kodbox [V1.41.04]
浏览器应该及版本：谷歌浏览器   版本 114.0.5735.134（正式版本）

**Comment by kalcaddle** [comment]
操作系统及版本也麻烦提供一下.


是每次必现还是偶尔出现?
和文件格式，大小是否有关?
上传完成后是一个文件还是两个文件?
官网demo是否出现?



杭州可道云网络有限公司


------------------ 原始邮件 ------------------
发件人: zJanch ***@***.***&gt;
发送时间: 2023年6月18日 21:23
收件人: kalcaddle/kodbox ***@***.***&gt;
抄送: warlee ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [kalcaddle/kodbox] 拖拽上传的时候会显示两个文件 (Issue #174)





 
文件上传使用拖进来会创建两个上传任务，要是点击选择文件按钮上传的就一个
 kod版本：Powered by kodbox [V1.41.04]
 浏览器应该及版本：谷歌浏览器   版本 114.0.5735.134（正式版本）

**Comment by kalcaddle** [comment]
测试出现了,只有拖拽到上传框松开才会出现(两个区域都响应了拖拽松开事件). 正常拖拽到文件操作区域是正常的
已解决, 下个版本优化.

**Comment by zJanch** [comment]
好的，老板
