### ISSUE TITLE
上传数据流量显示不正确

### ISSUE THREAD

**Issue by iamsunkai** [kalcaddle/kodbox#176]
多个文件上传，每个文件上传的速率是所有文件的总和，不是单独文件的速率
<img width="712" alt="image" src="https://github.com/kalcaddle/kodbox/assets/58293398/62b67ced-b317-46b8-a521-755b8d42510c">

**Comment by iamsunkai** [comment]
版本 v1.42

**Comment by kalcaddle** [comment]
目前是这样的.
多进程上传时,每个文件统计自己的上传速度的;(一段时间内上传字节数/时间间隔);
浏览器根据不同请求进行请求调度处理.
