### ISSUE TITLE
安卓客户端2.1.9“编辑外链”bug反馈

### ISSUE THREAD

**Issue by gundamf6** [kalcaddle/kodbox#177]
首先感谢开发者采纳了之前的建议，在最新版APP中添加了“编辑外链”。但是经测试选择整个文件夹点击外链，会大概率闪退，部分单文件分享外链时也会也会闪退。
客户端版本：2.1.9
测试手机安卓版本：安卓8.0.1   安卓11
运行环境docker   服务器版本1.42.01

**Comment by kalcaddle** [comment]
已确认,后续版本优化.
