### ISSUE TITLE
插件无法升级

### ISSUE THREAD

**Issue by zJanch** [kalcaddle/kodbox#178]
该插件与您的版本不兼容，请先将kodbox升级到最新版再试网络错误，请检查服务器能否访问外网。
need php lib:php curl,php_openssl,file get contents check network:ping api.kodcloud.com
我试了，能ping通

**Comment by kalcaddle** [comment]
需要先将kod升级到最新版后再试.

**Comment by zJanch** [comment]
升级不了，没有升级的地方，哪里有按钮？

**Comment by zJanch** [comment]
在哪个地方？

**Comment by kalcaddle** [comment]
后台: 系统管理--基础设置--程序版本-检测更新.
默认都是自动推送更新的.

**Comment by zJanch** [comment]
![微信图片_20230706164945](https://github.com/kalcaddle/kodbox/assets/53729565/a263c3bd-9ef1-460d-a7d9-dd63367f7118)
没有检查更新得按钮

**Comment by zJanch** [comment]
好像也没默认更新
