### ISSUE TITLE
内网穿透插件不支持https

### ISSUE THREAD

**Issue by lthwk** [kalcaddle/kodbox#180]
全站使用了https，插件不支持https外网访问。![IMG_20230708_084322.jpg](https://github.com/kalcaddle/kodbox/assets/125235014/f2ba3415-8507-41ff-9c25-47cab2858623)

**Comment by kalcaddle** [comment]
暂不支持https 后续支持。可以nginx反向代理处理一下



杭州可道云网络有限公司


------------------ 原始邮件 ------------------
发件人: lthwk ***@***.***&gt;
发送时间: 2023年7月8日 08:44
收件人: kalcaddle/kodbox ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [kalcaddle/kodbox] 内网穿透插件不支持https (Issue #180)





 
全站使用了https，插件不支持https外网访问。
