### ISSUE TITLE
文本编辑器能否扩展功能

### ISSUE THREAD

**Issue by jdysya** [kalcaddle/kodbox#181]
发现自带的文本编辑器是内置的，并不是以`plugin`的形式存在，我现在想扩展功能，只能自己单独开发一个插件吗
<img width="504" alt="image" src="https://github.com/kalcaddle/kodbox/assets/73117213/8c0cc08f-1574-4998-b103-8995648d9c8f">

**Comment by kalcaddle** [comment]
是的可以自行开发插件实现
监听对应事件做相应处理即可,监听全局事件方便调试,Events.bind('all',console.error)
