### ISSUE TITLE
并发锁定超时（20s)

### ISSUE THREAD

**Issue by YTLoudYN** [kalcaddle/kodbox#186]
卡在安装kodbox的最后一步骤：账号设置

报错：
出错了，并发锁定超时（20s)．请稍后再试（可降低请求频率，优化并发相关配置）. Suggest : nginx +php8.1+mysql5.7+ redis .

我该怎么做

**Comment by kalcaddle** [comment]
服务器配置太低或请求太慢引起的.
建议服务器配置: nginx +php8.1+mysql5.7+ redis

**Comment by YTLoudYN** [comment]
我找到了原因,当前容器没有相关的权限导致阻塞，我已切换到一个可以运行的环境
