### ISSUE TITLE
feature：能否添加windows客户端下，对于任意文件夹的同步功能

### ISSUE THREAD

**Issue by langren1353** [kalcaddle/kodbox#187]
功能如图所示
![image](https://github.com/kalcaddle/kodbox/assets/14857127/0c10051b-d673-4f63-8d81-f48c14f30db5)
在论坛发了帖子，但是一直没人回复，于是到git来提一个看看会不会有人跟踪一下

具体实现的话，目前我用软连接尝试实现了一下，使用mklink模拟了一下文件link，但是很可惜的是，软连接文件夹下面的事件推送，无法跟踪，导致kodbox不能及时同步用户的修改

可以尝试方案：软链接 + 原始路径监控

感谢kod，很好的软件（客户端、web端），谢谢开源，感谢你们整个团队（尤其是开发的小姐姐）的无私付出

**Comment by kalcaddle** [comment]
感谢支持:

目前pc客户端支持指定某个文件夹上行同步. 
多个文件夹同步,双向同步在开发计划中,后续支持.
目前要多文件夹双向同步,可以用第三方工具,如goodsync,freesync等通过webdav进行双向同步.
