### ISSUE TITLE
问题反馈：windows上使用客户端进行【无后缀文件】下载会出问题，文件名丢失

### ISSUE THREAD

**Issue by langren1353** [kalcaddle/kodbox#188]
复现环境：windows11
初始步骤：完整上传.ssh目录，客户端或者网页都可以
复现步骤1：web上创建一个文件夹叫：.ssh，然后上传一个无后缀的文件上去，例如known_host。将该文件夹通过客户端下载到了桌面，但是内部的文件名已经发生了变化

-------

现有结果：`.ssh/known_hosts`变成了`.ssh/(1)`

复现步骤2：web上创建一个普通文件夹ceshi，然后上传两个无后缀的文件：.gitignore以及.gitattributes。同样的，通过客户端选中文件夹，并右键下载到桌面
现有结果：`ceshi/.gitignore`和`ceshi/.gitattributes`变成了`ceshi/(1)`和`ceshi/(2)`

**Comment by langren1353** [comment]
好像就是无后缀文件，在pc客户端的下载过程中，文件名发生了丢失
从web端下载正常
当前软件版本：V0.5.0

**Comment by kalcaddle** [comment]
感谢反馈,后续版本会优化这个问题.
