### ISSUE TITLE
上传文件一直等待上传

### ISSUE THREAD

**Issue by NextSeconds** [kalcaddle/kodbox#192]
之前一直可以正常上传，今天突然无法上传，拖进去的文件或者选择的文件都上传不了了，一直卡在上传列表里，显示等待上传。
网络确认正常
下载文件确认正常
编辑kodbox文件正常
复制文件正常
特意操作服务器文件夹权限 777全放开了 还是不行

**Comment by NextSeconds** [comment]
![image](https://github.com/kalcaddle/kodbox/assets/35531612/830d9226-6e1b-46fa-98b7-10f55e791a5c)

**Comment by kalcaddle** [comment]
没遇到过该情况. 方便的话提供个外网地址和临时管理员账号我们看看
(内网的话可以在插件中心: 安装一下内网穿透插件,配置好即可使用)

email: kalcaddle#qq.com

**Comment by NextSeconds** [comment]
账号已发邮箱，十分感谢

**Comment by kalcaddle** [comment]
上传并发数被设置成了0,引起的
<img width="991" alt="image" src="https://github.com/kalcaddle/kodbox/assets/3761968/62b5d8ae-0f28-4e47-99be-71d959de4d28">

后台设置好保存一下即可.

**Comment by NextSeconds** [comment]
好的 感谢！

**Comment by a877429929** [comment]
刚看了我的，默认的是10，也是无法上传和保存文件，重新保存以后就可以了，是否是最近安装的都有这个问题呢

**Comment by kalcaddle** [comment]
> 刚看了我的，默认的是10，也是无法上传和保存文件，重新保存以后就可以了，是否是最近安装的都有这个问题呢

安装的比较早版本，从未保存过系统配置的可能有这个问题（默认配置没有保存到数据库）

下个版本优化兼容一下
