### ISSUE TITLE
mp4视频文件稍微大一点就打不开

### ISSUE THREAD

**Issue by chenenkou** [kalcaddle/kodbox#193]
**原视频文件大小是22M，打不开，一直转圈**
![image](https://github.com/kalcaddle/kodbox/assets/12895813/a2f0b334-125f-4012-b75c-093c086c83a1)
**手机APP上打开，提示加载失败，点击重试**
![image](https://github.com/kalcaddle/kodbox/assets/12895813/b8a10822-29f8-40fe-ae2f-1335cbe694db)
**但是直接在宝塔面板上打开上传到服务器上的文件，可以直接播放**
![image](https://github.com/kalcaddle/kodbox/assets/12895813/d0f0d21d-96ba-4a7b-8d86-13ed97de8a8b)

**后来发现在可道云PC上打开的视频要转圈很久，才可以播放，但是手机app上还是不行，但是实际用宝塔打开文件播放很快**

**Comment by kalcaddle** [comment]
可能是服务器配置问题, 可以对比demo站点看下,几个G的视频播放都是没问题的
方便的话提供个站点和临时管理员账号我们看看.(email: warlee#kodcloud.com)

**Comment by chenenkou** [comment]
> warlee#kodcloud.com

已发邮箱，请求协助，谢谢

**Comment by chenenkou** [comment]
> 可能是服务器配置问题, 可以对比demo站点看下,几个G的视频播放都是没问题的 方便的话提供个站点和临时管理员账号我们看看.(email: warlee#kodcloud.com)

已协助解决，谢谢
原因是开启了nginx反向代理后，未开启206 Partial Content支持，修改服务器配置文件已生效
