### ISSUE TITLE
思维导图以对话框形式开着的时候，浏览器页签切换出去，等一段时间切回来，点击保存思维保存的话，就一直卡在保存中

### ISSUE THREAD

**Issue by a877429929** [kalcaddle/kodbox#194]

**Comment by a877429929** [comment]
这是在官方demo中复现的
![1691739090624.png](http://lsky.ljw666.cn/i/2023/08/11/64d5e3d1150ff.png)

**Comment by kalcaddle** [comment]
测试后未发现该问题, 方便的话提供一下更详细信息,能够必须的操作步骤.
