### ISSUE TITLE
群晖docker安装，顶级目录下无法通过描述说明搜索文件，在当前文件的顶级目录下可以

### ISSUE THREAD

**Issue by Zed97c** [kalcaddle/kodbox#195]
![9c2a595ad13c87b449e18981c7e16786_1692342186-461174-8lo3nj6pgx62nevmak](https://github.com/kalcaddle/kodbox/assets/112675538/3a521491-d1d1-4593-86a9-bb2aad34f0af)
我这个r.7z文件 描述说明为：windows激活工具 顶级目录是：软件
在软件这个目录下搜索 windows激活 可以查到
如果点到个人空间下搜索，则查询不到，只能查询到文件名为windows的文件
![7b6cc1ff8f2c33d23ed1b9e3b8477579_1692342196-225354-e360itlmg-at-bxiryjn3iah](https://github.com/kalcaddle/kodbox/assets/112675538/74dba8fd-3991-48dc-a2fb-3722597b11c1)

**Comment by Zed97c** [comment]
![image](https://github.com/kalcaddle/kodbox/assets/112675538/dbd8ce65-d047-4cd4-9623-de2f24547930)
已经是全部文件夹搜索了 
这是我的挂载文件夹，按照教程来的
![image](https://github.com/kalcaddle/kodbox/assets/112675538/9642c44b-a75e-4dfe-8e8f-2473015fa8e8)

**Comment by Zed97c** [comment]
2023年8月18日16:27:45 更新
![image](https://github.com/kalcaddle/kodbox/assets/112675538/9a994763-f2b3-4a02-9673-ea1fd31e8b7f)
装了一个全新的 套件版本的 然后恢复备份之前的数据库 本来可以搜索到的 现在也搜不到了，难道是数据库问题？索引？

**Comment by Zed97c** [comment]
我问了几个群友 包括淘宝代安装的 他们也有这个问题 就是不搜索下级目录

**Comment by kalcaddle** [comment]
考虑性能问题,数据量大的情况全量搜索会很慢,目前只能搜索当前文件子内容标签.
后续版本优化支持.
