### ISSUE TITLE
Putting App Store into menu bar

### ISSUE THREAD

**Issue by mirtheese** [kalcaddle/kodbox#196]
Hi, I am still new in web-development and would appreciate some help with this. I need help with initializing the app by clicking at the menu so i can have a clean desktop where everything is in the menu bar. I have tried multiple ways such as the standard .html where i just hardcoded the store (where all the functionality and styling is a mess), calling light-app-dialog like http://localhost/#desktop&light-app-dialog=!, and insert javascript like "javascript:doSomething()" for js code and it is not working. Can anyone help with the issue?
![image](https://github.com/kalcaddle/kodbox/assets/143056742/4dc72d8d-6271-4a95-9f12-989eba81c3b3)

**Comment by kalcaddle** [comment]
only support url link now.
for more functions, you can write a plugin.
