### ISSUE TITLE
音乐播放器进度条拉到最左侧有bug

### ISSUE THREAD

**Issue by Fyime** [kalcaddle/kodbox#199]
任意音乐文件（mp3、flac等）打开为默认的“jPlayer播放器”以后，如果手动将播放器的进度条拉到最左侧，进度条的点击动作疑似没有释放，这时，如果移动鼠标指针到进度条的任意位置，即使没有单击鼠标，也会立即更新当前播放进度到鼠标指针的位置。

我是使用触控版的场景下发现的这个问题，不清楚鼠标是不是也有一样的问题
浏览器：Chrome 115.0.5790.170   系统：macOS 13.4.1
<img width="570" alt="QQ20230830-211337@2x" src="https://github.com/kalcaddle/kodbox/assets/46854523/1de4c823-11bb-448c-8432-5d853fc86358">

**Comment by kalcaddle** [comment]
该组件问题, 仅支持在时间进度条上拖拽松开, 在其他位置松开会不响应结束导致.
