### ISSUE TITLE
Firefox 87.0 Menu bug

### ISSUE THREAD

**Issue by renat2985** [kalcaddle/kodbox#2]
<img width="1244" alt="изображение" src="https://user-images.githubusercontent.com/1230815/114073300-d082e180-98ab-11eb-8468-30544bd6d79c.png">

<img width="1228" alt="изображение" src="https://user-images.githubusercontent.com/1230815/114073351-dd073a00-98ab-11eb-90e6-e332914ea55c.png">

**Comment by kalcaddle** [comment]
We have tested many times in the same environment, but there is no such situation. Can we provide more information for us to reproduce

![image](https://user-images.githubusercontent.com/3761968/114139665-e93dd680-9941-11eb-892d-d23aecf353ff.png)

![image](https://user-images.githubusercontent.com/3761968/114139694-f064e480-9941-11eb-8083-3e89602ff49e.png)
