### ISSUE TITLE
系统配置表SystemOption数据冗余问题

### ISSUE THREAD

**Issue by jymusic0663** [kalcaddle/kodbox#201]
1. 后台设置每次保存，总会把所有配置都在数据表【SystemOption】里新增一份记录，而不是在之前已有的数据做修改。长期使用下，会造成数据表数据严重冗余，数据表里记录过大。

2. kodbox会把【System.autoTask】这里任务执行记录也写入system_option配置表里，建议单独一个task任务表，不存入配置表。避免配置表里数据混乱，时间久了，难以维护。记录数特别多，读取数据库时性能会受影响

（以上两个问题查看过php代码，因这部分写数据表的代码是加密的，故发此issue）

**Comment by kalcaddle** [comment]
SystemOption 更新配置用的是 replace into; 数据量是不会增大的,只是id会增大.id目前用不到
为减少表数量,保持简洁,  计划任务,插件配置等数据量较小的数据默认写入到system_option(少于1000条,认为是少量数据)
