### ISSUE TITLE
kodbox如何进行迁移？迁移后存在报错。

### ISSUE THREAD

**Issue by Double517** [kalcaddle/kodbox#203]
![image](https://github.com/kalcaddle/kodbox/assets/11642282/d8744897-e71b-481f-89dd-ae68fd1843a8)
kod如何进行迁移，目前需要从A服务器迁移到B服务器，采用docker容器进行部署，迁移的时候将相关的数据迁移过来了，但是上传文件的时候会报错。temp not exist

**Comment by kalcaddle** [comment]
如果站点及存储目录结构不变,直接拷贝站点目录即可. 数据库也需要迁移过来
