### ISSUE TITLE
Initial instal in Chinese?

### ISSUE THREAD

**Issue by Kotva666** [kalcaddle/kodbox#205]
Would it be possible to use English as the default language? I don't understand. Then there are also folders created in Chinese. I have no idea what it is because I can't translate it.

Installed on docker

**Comment by Airfirewall** [comment]
The stuff in the folders is like my music, my documents, etc. I just deleted them all. The one under the personal drop down in the file explorer is enterprise network disk. Basically a share that is shared with all users. I'm still trying to find out how to delete it or change it to English.

**Comment by Airfirewall** [comment]
one thing that is annoying though is that the database that it creates is in Chinese, So that is a issue for me.

**Comment by kalcaddle** [comment]
The first visit is automatically recognized based on the browser's default language
Request Header:   "Accept-Language".  
After installation, create a user default folder that can be set in the administrator background.

All databases are created in English, with only annotations in Chinese,
Annotations can be modified using database management tools, but they can also be completely ignored without affecting any functionality
