### ISSUE TITLE
安卓APP bug反馈。

### ISSUE THREAD

**Issue by gundamf6** [kalcaddle/kodbox#207]
APP版本：2.2.0、2.1.9
kodbox版本：1.43.01
手机型号：坚果pro2s
手机版本：安卓8.1 
使用APP上传照片或者视频时，无法上传，上传列表为空白。APP权限全允许，能够访问手机内部照片。上传普通文件时正常。
在别的品牌手机高安卓版本的情况下正常。
推测：上传照片和视频时，用的是可道云自己的程序上传，上传普通文件时，是调用的第三方app上传。能否让APP像网页版一样调用第三方图库上传照片。
另外在手机web界面下，上传照片仅能一次上传一张。
在安卓APP中，上传照片没有全选这一选项，仅可一个一个点。

**Comment by kalcaddle** [comment]
下个版本优化.近期发布.
