### ISSUE TITLE
建议视频转码调用独显

### ISSUE THREAD

**Issue by ghostzwc** [kalcaddle/kodbox#209]
ffmpeg 程序
-hwaccel cuvid 使用硬件加速
-c:v hevc_cuvid 使用nvidia显卡解码
-i 输入.mp4 输入文件地址
-c:a copy 拷贝流（也就是格式工厂里面那个关闭二次编码好像速度更快）
-c:v h264_nvenc 使用nvidia显卡h264编码
-b:v 0 原始码率好像
-threads 5 线程5
-preset fast 最快模式
输出.mp4 按上面说的输出的地址

**Comment by kalcaddle** [comment]
大部分服务器不支持,而且差异比较大.   推荐自行修改插件代码,加入对应参数.
