### ISSUE TITLE
更新1.44.03后webdav除了/index.php/dav/别的访问不到了

### ISSUE THREAD

**Issue by qinghena** [kalcaddle/kodbox#211]
更新1.44.03后webdav除了/index.php/dav/别的访问不到了，别的报错图1，/index.php/dav/挂载dav后无法进如个人空间等，图2，权限没问题，可道云页面端文件正常图3

**Comment by qinghena** [comment]
![1](https://github.com/kalcaddle/kodbox/assets/59902878/0f84221f-b9c1-40a1-ae7c-bbe04ee7e3dc)
![2](https://github.com/kalcaddle/kodbox/assets/59902878/4c57588b-5e24-475e-b3e1-9df2145ea923)
![3](https://github.com/kalcaddle/kodbox/assets/59902878/f729134e-03ef-4341-9e0f-2c1910564b62)

**Comment by kalcaddle** [comment]
已修复,在线更新一下即可.
