### ISSUE TITLE
是否考虑pc客户端文件同步功能支持双向同步，目前的同步功能不能同步本地删除但是可以同步新增和修改，感觉和文件同步功能名字不符合，

### ISSUE THREAD

**Issue by qinghena** [kalcaddle/kodbox#212]
是否考虑pc客户端文件同步功能支持双向同步，目前的同步功能不能同步本地删除但是可以同步新增和修改，感觉和文件同步功能名字不符合，我看官方社区有人2022年就提交了这个双向同步，官方回答是后续支持，老哥们现在已经一年了，特别需要。

**Comment by kalcaddle** [comment]
功能比较复杂,开发资源有限. 在开发计划中,后续会支持.
目前可以使用goodsync,freesync 等通过wegdav挂载实现双向同步.

**Comment by huangda1982** [comment]
还在开发计划中吗？
