### ISSUE TITLE
外链分享文件夹的内容无法下载/预览

### ISSUE THREAD

**Issue by HNQX** [kalcaddle/kodbox#213]
版本：1.44.05

我想用外链来分享多个视频，把文件夹外链分享出去时，别人下载不了，甚至预览不了，提示【此类型目录不支持该操作】
测试用链接：
分享名称：123
分享链接：https://52152121.xyz:702/#s/9ug5e1Xw
访问密码：123

这几个选项都无法生效
![image](https://github.com/kalcaddle/kodbox/assets/32836634/8ca3e5fd-879b-4871-a9ba-089bbcf6e8c6)

**Comment by kalcaddle** [comment]
已确认，今天会修复，修复好会推送版本升级。



杭州可道云网络有限公司


------------------ 原始邮件 ------------------
发件人: han ***@***.***&gt;
发送时间: 2023年10月8日 11:23
收件人: kalcaddle/kodbox ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [kalcaddle/kodbox] 外链分享文件夹的内容无法下载/预览 (Issue #213)





 
版本：1.44.05
 
我想用外链来分享多个视频，把文件夹外链分享出去时，别人下载不了，甚至预览不了，提示【此类型目录不支持该操作】
 测试用链接：
 分享名称：123
 分享链接：https://52152121.xyz:702/#s/9ug5e1Xw
 访问密码：123
 
这几个选项都无法生效

**Comment by kalcaddle** [comment]
已修复,在线升级一下即可.

**Comment by HNQX** [comment]
升级了，已解决，感谢开发组
