### ISSUE TITLE
关于 rclone mount 和 下载

### ISSUE THREAD

**Issue by 7revor** [kalcaddle/kodbox#214]
使用 rclone mount 将 google drive 挂载到本地，并且在kodbox中设置为本地存储。rclone 开启了 --vfs-cache-mode full
下载文件时，如果目标文件没有被 rclone vfs 缓存，会先等待服务端将整个文件缓存（下载）完毕后，浏览器才开始下载传输。rclone分快传输没有生效。希望能在rclone开始下载（缓存）gd的同时，kodbox进行下载传输。

**Comment by kalcaddle** [comment]
场景比较特殊. 可以自行通过开发插件实现.
