### ISSUE TITLE
苹果手机生成缩略图和封面有一个非常影响性能的BUG

### ISSUE THREAD

**Issue by SDerssd** [kalcaddle/kodbox#221]
苹果手机的部分MOV视频和HEIC图片，会有一部分播放和生成不了缩略图，这样会导致，每次进入这个文件夹时，后台形成非常多的ffmpeg进程，导致CPU整个拉满，持续很长一段时间
这个策略也会影响到其他，假如说有视频或者照片损坏的情况下，每次进去都会调用一遍无意义的ffmpeg策略，会非常非常卡，特别是一个很大的文件夹
是否应该对缩略图做一个生成一次失败以后就不生成了，显示一个其他的图标，等用户点击查看它的时候，再生成一次还是怎么样
每次进文件夹都全有几十个ffmpeg挂在后台卡死了确实无法使用，相当于只考虑了所有媒体都能生成成功的情况，没考虑无法生成的情况，而且每次进出文件夹都会触发，完全无法使用

**Comment by kalcaddle** [comment]
后续优化一下



杭州可道云网络有限公司


------------------ 原始邮件 ------------------
发件人: XiaoXiao ***@***.***&gt;
发送时间: 2023年10月28日 08:46
收件人: kalcaddle/kodbox ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [kalcaddle/kodbox] 苹果手机生成缩略图和封面有一个非常影响性能的BUG (Issue #221)





 
苹果手机的部分MOV视频和HEIC图片，会有一部分播放和生成不了缩略图，这样会导致，每次进入这个文件夹时，后台形成非常多的ffmpeg进程，导致CPU整个拉满，持续很长一段时间
 这个策略也会影响到其他，假如说有视频或者照片损坏的情况下，每次进去都会调用一遍无意义的ffmpeg策略，会非常非常卡，特别是一个很大的文件夹
 是否应该对缩略图做一个生成一次失败以后就不生成了，显示一个其他的图标，等用户点击查看它的时候，再生成一次还是怎么样
 每次进文件夹都全有几十个ffmpeg挂在后台卡死了确实无法使用，相当于只考虑了所有媒体都能生成成功的情况，没考虑无法生成的情况，而且每次进出文件夹都会触发，完全无法使用

**Comment by kalcaddle** [comment]
转换失败目前本来就有记录失败的缓存的. 只是缓存的时间比较短, 60s, 新版已改为30天; 在线升级一下即可.
(如果因为ffmpeg版本等原因导致的转换失败,重新生成需要清空一下缓存后再试)
