### ISSUE TITLE
在线压缩文件BUG

### ISSUE THREAD

**Issue by SDerssd** [kalcaddle/kodbox#222]
每次点击压缩，会在根目录的{io:3}里面找到压缩文件，但是页面提示失败
还有一个问题就是压缩文件的内容，文件名称是乱码的

**Comment by kalcaddle** [comment]
没遇到过该问题，提供一下 操作系统/php/server及版本。从什么地方解压的，描述一下详细操作步骤。



杭州可道云网络有限公司


------------------ 原始邮件 ------------------
发件人: XiaoXiao ***@***.***&gt;
发送时间: 2023年11月2日 10:14
收件人: kalcaddle/kodbox ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [kalcaddle/kodbox] 在线压缩文件BUG (Issue #222)





 
每次点击压缩，会在根目录的{io:3}里面找到压缩文件，但是页面提示失败
 还有一个问题就是压缩文件的内容，文件名称是乱码的

**Comment by SDerssd** [comment]
+ 服务器系统: Linux HK1BOX 5.15.107-flippy-82+o #224 SMP PREEMPT Fri Apr 14 15:48:43 CST 2023 aarch64
+ 服务器软件: nginx/1.21.3PHP版本: PHP/8.2.2
+ KodBox版本: Powered by kodbox [V1.45.06]
+ 操作步骤: 随便找个文件夹右键，创建压缩包，会提示创建失败，实际根目录有个文件夹里面有压缩包

**Comment by kalcaddle** [comment]
没有复现，可能是服务器兼容问题，方便的话提供个站点url和临时管理员账号我们看看，邮件发送到 warlee#kodcloud.com


内网的话，插件中心安装一下内网穿透。



杭州可道云网络有限公司


------------------ 原始邮件 ------------------
发件人: XiaoXiao ***@***.***&gt;
发送时间: 2023年11月2日 13:14
收件人: kalcaddle/kodbox ***@***.***&gt;
抄送: warlee ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [kalcaddle/kodbox] 在线压缩文件BUG (Issue #222)





  
服务器系统: Linux HK1BOX 5.15.107-flippy-82+o #224 SMP PREEMPT Fri Apr 14 15:48:43 CST 2023 aarch64
 
服务器软件: nginx/1.21.3PHP版本: PHP/8.2.2
 
KodBox版本: Powered by kodbox [V1.45.06]
 
操作步骤: 随便找个文件夹右键，创建压缩包，会提示创建失败，实际根目录有个文件夹里面有压缩包

**Comment by kalcaddle** [comment]
> * 服务器系统: Linux HK1BOX 5.15.107-flippy-82+o #224 SMP PREEMPT Fri Apr 14 15:48:43 CST 2023 aarch64
> * 服务器软件: nginx/1.21.3PHP版本: PHP/8.2.2
> * KodBox版本: Powered by kodbox [V1.45.06]
> * 操作步骤: 随便找个文件夹右键，创建压缩包，会提示创建失败，实际根目录有个文件夹里面有压缩包

方便提供个站点url和临时管理员吗, 我们看看做一下兼容.

**Comment by kalcaddle** [comment]
排查了下, 是你把后台--基础设置--安全设置 "外链分享打包下载"关闭了引起.开启即可.
后面版本优化一下,该开关仅影响外链分享.
