### ISSUE TITLE
右下角分页显示问题

### ISSUE THREAD

**Issue by wuhu717373250** [kalcaddle/kodbox#223]
右下角分页显示,被挤下来了,谷歌浏览器 版本 118.0.5993.120
全屏的时候也会被挤下来

![image](https://github.com/kalcaddle/kodbox/assets/148927976/6648b4c8-bb01-4a4a-879f-c28092af9c19)

**Comment by kalcaddle** [comment]
浏览器兼容问题, 部分版本渲染差异,下个版本优化.
