### ISSUE TITLE
移动端显示问题

### ISSUE THREAD

**Issue by wuhu717373250** [kalcaddle/kodbox#225]
**系统:  鸿蒙 4.0 ,鸿蒙 3.0 (跟安卓一样)
软件版本: 2.2
型号: 华为 p30p 华为 mate 40pro ,
如图,底部空隙过大,**
![image](https://github.com/kalcaddle/kodbox/assets/148927976/e244481c-66c7-489e-a3ac-d1f863d4d0bb)

**还有就是,点击图片,进入大图的时候,不能进行删除等操作,希望能增加删除重命名等常用操作

删除的话会出现丢失滚动条位置的情况,希望删除后能无感刷新,不要再调接口

下拉下一页,会出现数据错误的情况,比如我的最后一张图片是一只猫,我下拉,加载出了数据,划到最下面,最后一张还是那只猫**

**也就是 第 200 项 和  第 300 项 的最后面的数据是一样的,仔细对比下**

![11d40990ca5f2f577b1600d252ed44b](https://github.com/kalcaddle/kodbox/assets/148927976/724f973b-7f59-4f11-beb1-7ce5890bae8f)

![2d3e6bec32b8c4683a38f7e14a36201](https://github.com/kalcaddle/kodbox/assets/148927976/dd479dfa-856b-4b1f-b42e-7c562b05fec8)

**Comment by kalcaddle** [comment]
属于开发计划中的优化功能,开发中.后续版本支持.
