### ISSUE TITLE
ffmpeg生成封面的性能问题

### ISSUE THREAD

**Issue by SDerssd** [kalcaddle/kodbox#226]
起初每次上传几个视频以后ffmpeg开始运行时，页面几乎处于卡死状态，我以为是服务器性能问题。
但是我后来把ffmpeg限制为一个线程，其他三个线程处于空闲时，页面依然处于卡死状态。
这难道不是异步的吗，还是说必须等ffmpeg全部生成完了才能做其他操作？

**Comment by SDerssd** [comment]
换了很多方式测了一下，php确实是在等待ffmpeg返回，这体验太不好了

**Comment by kalcaddle** [comment]
文件列表展示时,根据是否在屏幕内,文件自动获取缩略图封面(页面懒加载). 
首次访问缩略图封面图片,会调用shell 调用ffmpeg命令行进行生成,生成后进行缓存. 该过程是同步的. 普通pc机器,视频缩略图生成我们测试大概1s 30个文件左右;基本是够用的.

页面卡住要么是服务器性能占满,要么是php进程数太少了(加大进程数限制).  如果服务器配置不高,每个视频生成缩略图耗时较久,建议关闭封面图插件. 改为异步比较复杂,有需要可以自行修改  plugins/fileThumb 插件.

**Comment by kalcaddle** [comment]
插件已升级，改为异步队列处理了，可以升级下看看
