### ISSUE TITLE
上传和下载大文件出错

### ISSUE THREAD

**Issue by Fvpder** [kalcaddle/kodbox#227]
kodbox1.46.03 docker部署，nginx反代，系统unraid6.12.4，配置了mysql数据库和redis缓存
使用webdav挂载的方式上传超过1gb的文件出错，使用网页上传正常；webdav和网页下载大文件都会出错，在下载到1gb时显示失败

**Comment by Fvpder** [comment]
使用mysql数据库和redis缓存

**Comment by Fvpder** [comment]
下载出错已经解决，是nginx的问题，需要设定nginx config为`porxy_buffering off`，但是使用webdav上传超过1g的依然报错：413 Request Entity Too Large

**Comment by kalcaddle** [comment]
webdav上传大文件需要调整(无法分片,只能整体传输)

1. window默认限制去除4G限制(webdav插件中心,提供了修改注册表的脚本,执行即可)
2. ngingx上需要修改上传最大文件限制.  client_max_body_size
3. php上传文件最大限制.  超时时间建议也改大一些. post_max_size/upload_max_filesize/...

https://doc.kodcloud.com/v2/#/help/options

**Comment by hccz95** [comment]
> webdav上传大文件需要调整(无法分片,只能整体传输)
> 
> 1. window默认限制去除4G限制(webdav插件中心,提供了修改注册表的脚本,执行即可)
> 2. ngingx上需要修改上传最大文件限制.  client_max_body_size
> 3. php上传文件最大限制.  超时时间建议也改大一些. post_max_size/upload_max_filesize/...
> 
> https://doc.kodcloud.com/v2/#/help/options

我是用docker-compose部署的，也遇到了大文件上传的错误，请问在哪里找nginx和php的配置文件？
