### ISSUE TITLE
kodbox和minio存储的上传bug

### ISSUE THREAD

**Issue by leo2430** [kalcaddle/kodbox#229]
后台存储使用minio对象存储，配置如下图（不通过服务器上传）
![image](https://github.com/kalcaddle/kodbox/assets/57786544/e0d7c934-a528-4dfc-bd60-1d731877adec)

在上传 大于50KB并且小于<10MB的文件时不能成功。。报错403错误
![image](https://github.com/kalcaddle/kodbox/assets/57786544/8b3ff653-b966-492d-976f-ffee9c3b86d7)

小于50KB，或者大于10MB的文件可以正常上传成功

**Comment by kalcaddle** [comment]
经测试未发现该问题，可能和服务器配置有关，看报错是minio拒绝了，检查一下配置
<img width="1464" alt="image" src="https://github.com/kalcaddle/kodbox/assets/3761968/ff79ab60-874b-4b37-83da-9615fae29a2c">

方便的话提供下站点和临时管理员账号,我们看看. email to:  warlee#kodcloud.com

**Comment by leo2430** [comment]
我这边测试了几个minio的版本，早期版本和最新版本
![image](https://github.com/kalcaddle/kodbox/assets/57786544/42569a6e-3337-48c6-a8a3-450fdace099e)

早期版本没有问题，，它们的最新的几个版本存在这样的问题。看看你们那里是否可以重现问题？

![image](https://github.com/kalcaddle/kodbox/assets/57786544/9d37cd05-bb33-4afe-a674-4f4e57987d5e)

**Comment by kalcaddle** [comment]
> 我这边测试了几个minio的版本，早期版本和最新版本 ![image](https://user-images.githubusercontent.com/57786544/283303646-42569a6e-3337-48c6-a8a3-450fdace099e.png)
> 
> 早期版本没有问题，，它们的最新的几个版本存在这样的问题。看看你们那里是否可以重现问题？
> 
> ![image](https://user-images.githubusercontent.com/57786544/283304227-9d37cd05-bb33-4afe-a674-4f4e57987d5e.png)

minio 接口api调整了, 后续版本做一下兼容.
