### ISSUE TITLE
没有生成HEIC格式图片的略缩图

### ISSUE THREAD

**Issue by jdysya** [kalcaddle/kodbox#231]
今天发现所有HEIC格式图片的略缩图都不显示了
<img width="552" alt="image" src="https://github.com/kalcaddle/kodbox/assets/73117213/b073f104-cf2e-45ca-955f-554efdeec78a">
<img width="1014" alt="image" src="https://github.com/kalcaddle/kodbox/assets/73117213/3287b947-b8df-439f-87d6-36cd216b8fe9">

打开调试模式，没有相关的日志内容
<img width="799" alt="image" src="https://github.com/kalcaddle/kodbox/assets/73117213/82ee65bc-1972-4e47-8a94-bb42a9a8a073">

在 https://demo.kodcloud.com/#

中上传HEIC格式图片发现问题也存在，并且双击打开该文件，所匹配的图片内容是其他JPG格式图片的
<img width="1139" alt="image" src="https://github.com/kalcaddle/kodbox/assets/73117213/b26535ac-7e40-4513-9848-1a884563ba56">

**Comment by kalcaddle** [comment]
heic默认是不支持的.需要自行编译ImageMagick,及libheif相关库
详情参考: https://docs.kodcloud.com/setup/others/#psd

服务器连接github慢的,可以用gitee镜像.
```
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
yum remove ImageMagick -y
yum install gcc gcc-c++ autoconf automake libtool
yum install -y fftw fftw-devel fftw-devel bzip2-devel freetype-devel libjpeg-devel libpng-devel libtiff-devel giflib-devel zlib-devel ghostscript-devel djvulibre-devel libwmf-devel jasper-devel  libX11-devel libXext-devel libXt-devel lcms-devel libxml2-devel librsvg2-devel OpenEXR-devel openjpeg openjpeg-devel  openjpeg2 openjpeg2-devel openjpeg2-libs  gcc gcc-c++  make automake  libtool   libtool-ltdl-devel lcms2  lcms2-devel LibRaw LibRaw-devel
cd /usr/src/ 
git clone https://gitee.com/mirrors/libde265.git
git clone https://gitee.com/openkylin/libheif.git
git clone --depth 1 --branch 7.1.0-46 https://gitee.com/mirrors/ImageMagick.git
cd libde265/ && ./autogen.sh && ./configure && make && make install 
cd /usr/src/libheif/ && ./autogen.sh && ./configure && make && make install 
cd /usr/src/ImageMagick && ./configure && make -j 8 && make install && ldconfig /usr/local/lib
identify --version
```
