### ISSUE TITLE
HEIC图片太多，加载卡死

### ISSUE THREAD

**Issue by jdysya** [kalcaddle/kodbox#232]
文件列表默认一页显示500图片，当打开一个较多图片的页面，由于全是HEIC格式图片，程序应该会执行转码操作，导致服务器卡死
能否支持后台静默生成文件略缩图，这样在加载时就不会有那么大的工作量，或者调整为上传图片后就立即生成对应的略缩图

主要是后台`convert`进程太多，一下子就会将CPU占用至100%
![image](https://github.com/kalcaddle/kodbox/assets/73117213/056c88cf-5def-4868-8cc8-88e68c3af77f)

这个`convert`进程数应当在哪里配置？我修改了php相关的配置文件，发现对此没有作用

**Comment by kalcaddle** [comment]
文件列表展示时,根据是否在屏幕内,文件自动获取缩略图封面(页面懒加载).
首次访问缩略图封面图片,会调用shell 调用ffmpeg命令行进行生成,生成后进行缓存. 该过程是同步的. 普通pc机器,视频缩略图生成我们测试大概1s 30个文件左右;基本是够用的.

页面卡住要么是服务器性能占满,要么是php进程数太少了(加大进程数限制). 如果服务器配置不高,生成缩略图耗时较久,建议关闭封面图插件.

后面版本优化一下,处理为异步,后台队列生成(损失: 没有生成的会不加载,刷新后会显示已生成的部分)

**Comment by kalcaddle** [comment]
插件已升级，改为异步对接处理了，可以升级下看看
