### ISSUE TITLE
Strategies for Maintaining Directory Structure and Synchronizing with Kodbox without Direct Interaction

### ISSUE THREAD

**Issue by JunioCalu** [kalcaddle/kodbox#234]
I am seeking guidance on how to efficiently manage the synchronization of files and directories between Kodbox and a local file system. There are two main issues I would like to address:

**Maintaining Directory Structure in Uploads to Kodbox:** When I upload a folder to Kodbox, I want to ensure that the organizational directory structure of that folder is preserved in my local file system. This is crucial for maintaining the consistency and organization of my files.

**Synchronization with Existing Local Folder:** Additionally, I have a folder in my local file system where files are generated and modified independently of Kodbox. I need a solution to synchronize this folder with Kodbox, without direct interaction with the Kodbox system. The goal is to ensure that files and directories created or modified locally are reflected in Kodbox automatically.

**Comment by kalcaddle** [comment]
you can use  like  goodsync,freesync ...
local Folder  <==> kodbox webdav.
