### ISSUE TITLE
1.47(02) 版本 Drawio 流程图无法打开

### ISSUE THREAD

**Issue by GalensGan** [kalcaddle/kodbox#235]
kodbox 升级到 1.47(02)  后，发现 Drawio 流程图打不开，打开控制台，显示以下错误：

![image](https://github.com/kalcaddle/kodbox/assets/45629076/95495189-56c6-47b7-8ea4-5a3ff47de0ea)

以前创建的流程图和现在新建的流程图都打不开了。

**Comment by kalcaddle** [comment]
未发现该问题，可以对比测试官网demo
demo.kodcloud.com &nbsp; &nbsp; demo/demo


方便的话给个地址和临时管理员账号我们看看.
email: &nbsp;warlee#kodcloud.com



杭州可道云网络有限公司


------------------ 原始邮件 ------------------
发件人: GALENS ***@***.***&gt;
发送时间: 2023年11月25日 12:21
收件人: kalcaddle/kodbox ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [kalcaddle/kodbox] 1.47(02) 版本 Drawio 流程图无法打开 (Issue #235)





 
kodbox 升级到 1.47(02)  后，发现 Drawio 流程图打不开，打开控制台，显示以下错误：
 
image.png (view on web)
 
以前创建的流程图和现在新建的流程图都打不开了。

**Comment by kalcaddle** [comment]
方便的话给个地址和临时管理员账号我们看看.
email: &nbsp;warlee#kodcloud.com


杭州可道云网络有限公司


------------------ 原始邮件 ------------------
发件人: Douglas, Arlington ***@***.***&gt;
发送时间: 2023年11月25日 17:35
收件人: kalcaddle/kodbox ***@***.***&gt;
抄送: warlee ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [kalcaddle/kodbox] 1.47(02) 版本 Drawio 流程图无法打开 (Issue #235)





 
@kalcaddle 经测试，应该是我的问题，但是具体原因不明。
 当我用有问题的电脑访问时，它是因为无法请求 /js/PreConfig.js 这个文件而报错
 image.png (view on web)
 
但当我用正常的电脑打开流程图时，发现它请求 PreConfig.js 这个文件时的路由不一样，为：/plugins/drawio/static/drawio/js/PreConfig.js。
 
是什么原因导致这个情况呢？请指教一下，谢谢！

**Comment by GalensGan** [comment]
@kalcaddle 只有一台电脑有问题，其它电脑无法复现。
最后找到原因了，是被广告拦截器 Adguard 给拦截了。不好意思，打扰了~
