### ISSUE TITLE
webdav挂载存储后，通过可道云拉取文件速度过慢的问题

### ISSUE THREAD

**Issue by Luolin0826** [kalcaddle/kodbox#236]
您好，

我在尝试通过[这种方法](https://zhuanlan.zhihu.com/p/656214960)在OneDrive上创建WebDAV，并成功将其挂载到由Docker安装的kodbox。在上传文件时，速度表现正常，大约在2-3MB/s。然而，我遇到了一个问题，即从kodbox拉取文件的速度非常慢，仅为20-50KB/s，与此同时通过[Koofr](https://app.koofr.net/app/storage/da336fee-e9fa-40a3-6e1c-ed80855f53b9)拉取文件的速度是正常的，在7-10MB/s。

此问题已在两台服务器上复现，一台搭载Ubuntu 20的服务器位于广州（配置为4核4GB内存8MB带宽），另一台位于德国（配置为2核2GB内存1GB带宽）。我正在使用的kodbox版本是[V1.47.02]。

请问有什么建议或解决方案可以提高文件拉取速度？感谢您的帮助！

祝好

**Comment by kalcaddle** [comment]
kod拉取文件, 就是常规的curl请求; 正常来说速度和从命令行调用curl差不多(如果有差异,检测是否对php进程做了相关网络限制)
其他客户端下载可能使用了多进程, 根据网络环境及服务器相关限速设置,可能会有提升.

这一块后续我们看看优化一下,能做成多进程按多个进程处理,
