### ISSUE TITLE
HEIC格式图片预览

### ISSUE THREAD

**Issue by jdysya** [kalcaddle/kodbox#237]
目前新版本中对于封面生成已经改为了异步生成，不会出现卡死服务器的情况，非常感谢开发组的贡献！

不过现在貌似出现了一个新的问题，那就是对于HEIC格式的图片，无法直接预览，会出现`The image could not be loaded.`，如图所示

<img width="650" alt="image" src="https://github.com/kalcaddle/kodbox/assets/73117213/b4306518-65b5-47e0-b1da-78405a086122">

需要再次双击图片才会正常显示图片内容

**Comment by kalcaddle** [comment]
原因是该图片还未生成完成(在后台任务队列中); 生成后才能正常查看.

新版对这一块做了进一步优化
文件列表拉取时: 未生成封面图的,加入到后台任务队列(计划任务所在进程,按队列优先级依次处理)
文件列表,双击打开,支持立即生成(优先级最高);

新版本预计本周或下周发布.

**Comment by jdysya** [comment]
> 原因是该图片还未生成完成(在后台任务队列中); 生成后才能正常查看.
> 
> 新版对这一块做了进一步优化 文件列表拉取时: 未生成封面图的,加入到后台任务队列(计划任务所在进程,按队列优先级依次处理) 文件列表,双击打开,支持立即生成(优先级最高);
> 
> 新版本预计本周或下周发布.

可是在文件夹页面，已经能显示图片的略缩图了呀

**Comment by kalcaddle** [comment]
> 可是在文件夹页面，已经能显示图片的略缩图了呀，那就期待一下新版本吧

缩略图和预览图是两张图片,对应是两个任务; 缩略图==> N*250;  预览图 N* 1200;

**Comment by jdysya** [comment]
> > 可是在文件夹页面，已经能显示图片的略缩图了呀，那就期待一下新版本吧
> 
> 缩略图和预览图是两张图片,对应是两个任务; 缩略图==> N x 250; 预览图 N x 1200;

懂了懂了，感谢耐心解答
