### ISSUE TITLE
支持自动站内通知和邮件通知

### ISSUE THREAD

**Issue by jdysya** [kalcaddle/kodbox#238]
对于一些站内的活动，例如对企业部门中某文件进行了相关的讨论，能否对其他人进行站内的通知，或者是邮件通知（支持用户自己选择是否开启，类似于github的订阅通知功能）
<img width="339" alt="image" src="https://github.com/kalcaddle/kodbox/assets/73117213/b1cf60d0-bf28-4496-ab98-bb33efe83472">

**Comment by kalcaddle** [comment]
内部聊天模块,通知中心增强,消息推送等.  在开发计划中. 后续支持.
