### ISSUE TITLE
kodbox API中对标签的支持

### ISSUE THREAD

**Issue by jdysya** [kalcaddle/kodbox#239]
看了一下[kodbox API](https://doc.kodcloud.com/v2/#/explorer/file)，其中好像没有和标签相关的接口支持，而且在客户端中查看文件属性，也没有标签这个属性。

对于企业公共标签貌似直接没有入口

**Comment by kalcaddle** [comment]
api文档会滞后一些,  可以直接通过浏览器,查看网络tab, 可以查看所有api接口. 
接口调用,和其他接口类似.


给文件添加标签: /?explorer/tag/filesAddToTag&tagID=xxx&files=xxx,xxx
给文件移除标签: /?explorer/tag/filesRemoveFromTag&tagID=xxx&files=xxx,xxx

部门公共标签,需要先编辑设置好部门公共标签内容,设置后部门下文档才可以设置部门公共标签.
每个部门设置的功能标签是独立的,只能部门管理员或系统管理员才可以设置
<img width="1357" alt="image" src="https://github.com/kalcaddle/kodbox/assets/3761968/27e527af-6089-42e4-8892-a2ad2706af0f">

<img width="1051" alt="image" src="https://github.com/kalcaddle/kodbox/assets/3761968/90162259-16f1-42aa-9082-fe0d14f7a2e7">


给部门下文档添加部门公共标签: /?explorer/tagGroup/filesAddToTag&groupID=xxx&tagID=3&files=xxx,xxx
给部门下文档移除部门公共标签: /?explorer/tagGroup/filesRemoveFromTag&groupID=xxx&tagID=3&files=xxx,xxx
