### ISSUE TITLE
kodbox API中单点登录

### ISSUE THREAD

**Issue by jdysya** [kalcaddle/kodbox#240]
[文档中](https://doc.kodcloud.com/v2/#/user/user?id=a-%e9%80%9a%e8%bf%87%e7%94%a8%e6%88%b7%e5%90%8d%e5%af%86%e7%a0%81%e8%8e%b7%e5%8f%96-accesstoken)是将密码明文包含在GET请求的URL中，这样不太安全。

我在网页控制台发现，网页版中对于该接口调用的是POST请求，且传入的字段并不是明文密码，想问下这个密码是用什么方式进行加密的？
<img width="893" alt="image" src="https://github.com/kalcaddle/kodbox/assets/73117213/d97e731d-e75c-4a3b-a6d1-2c3dfb6d451c">

**Comment by kalcaddle** [comment]
自己实现的一个加密方法,具体逻辑见:
https://github.com/kalcaddle/kodbox/blob/main/app/controller/user/index.class.php#L292C3-L294
https://github.com/kalcaddle/kodbox/blob/main/app/kod/Mcrypt.class.php#L29-L125
