### ISSUE TITLE
视频怎么不能显示缩略图了

### ISSUE THREAD

**Issue by SDerssd** [kalcaddle/kodbox#242]
更新以后视频都不生成缩略图了，图片可以生成

**Comment by kalcaddle** [comment]
正常生成,目前立即生成,优化该为了访问文件列表时,加入到后台任务队列生成.
如果没有生成,确保ffmpeg等依赖正常, 插件和kod是否都是最新版;  可以尝试后台--清除插件缓存,然后重新访问文件列表.会重新生成.
