### ISSUE TITLE
重提 #229 的问题

### ISSUE THREAD

**Issue by leo2430** [kalcaddle/kodbox#243]
关于与minio对象存储的兼容问题。
kod更新到1.48.03版本后
测试了minio的最新版和旧版本

问题：
在关闭    “服务器中转(上传)” 选项后，所有的文件都无法上传

**Comment by kalcaddle** [comment]
我们测试过确认没问题, 如果后端能上传,前端异常,  
可能原因是同源策略或https证书问题引起的.可以查看浏览器控制台,注意:


1. https站点不能发起http请求(浏览器直接拦截; kod为https,但minio配置的是http的情况)
2. minio配置的https证书异常.
