### ISSUE TITLE
【报错咨询】onlyoffice 插件 运行环境检测问题

### ISSUE THREAD

**Issue by BlueNoob** [kalcaddle/kodbox#246]
kcloud 和 onlyoffice 单独都好的状态下，如何配置？
检测逻辑是什么，能不能把检测过程抛出来，方便排查？
或者有没有付费咨询，协助解决当前问题？

## 环境
1panel环境下，docker部署，域名前面有反向代理

- kodcloud:   `https://file.domain.com`
- onlyoffice:  `https://office.domain.com`

 ## 个人排查过程
## 报错
![1704202124928](https://github.com/kalcaddle/kodbox/assets/4169222/70ffcea2-e04f-4c6e-8e34-9e28e2a8c5c1)

## 个人怀疑
会不会是服务器主机名导致的？在系统配置界面，找不到任何地方去指定

![image](https://github.com/kalcaddle/kodbox/assets/4169222/d8af2d58-1b52-41d3-9a31-1e371211454c)

另外，看了下插件app.php代码中有写:8081，会不会是这个问题导致的？
![image](https://github.com/kalcaddle/kodbox/assets/4169222/c9056425-7d52-41a8-89e5-edb38627a28a)

**Comment by BlueNoob** [comment]
![image](https://github.com/kalcaddle/kodbox/assets/4169222/51150d59-58ee-4d46-92fc-820c456a7d22)

**Comment by BlueNoob** [comment]
根据404，进一步发现，官网的 onlyoffice 好像是定制化部署的。。原版没有check
## 官网
![image](https://github.com/kalcaddle/kodbox/assets/4169222/3634c8b0-5f49-4327-9069-832a072247fc)
## 原版
![image](https://github.com/kalcaddle/kodbox/assets/4169222/ff9c3d79-3646-479e-b6ac-4443cc43ba46)

**Comment by kalcaddle** [comment]
官方进行的话,忽略那两个错误即可, 只要docker正常运行,打开编辑文件就都是正常的.

也可以使用我们封装过的版本.https://docs.kodcloud.com/setup/office/
