### ISSUE TITLE
观看 .mkv 视频文件时听不到声音错误 

### ISSUE THREAD

**Issue by Rvspx** [kalcaddle/kodbox#247]
观看 .mkv 视频文件时听不到声音错误 , 使用Dplayer插件观看视频。mkv无法输出声音。

**Comment by kalcaddle** [comment]
目前无解, 浏览器解码不支持. 音乐视频格式是否能正常播放,取决于浏览器内置的播放解码器.
目前浏览器普遍兼容比较好的是, h264的mp4格式
