### ISSUE TITLE
Kod Explorer v4.52 外链下载文件时，文件名全部变成index.php或index.zip

### ISSUE THREAD

**Issue by mazhewei** [kalcaddle/kodbox#248]
印象中近期跳出来过一次安全更新，更新以后出现的，之前是好的。不清楚是否有关联。

**Comment by kalcaddle** [comment]
是有人提,文件预览或外链文件访问时(pdf,office等文件),会被idm下载软件嗅探拦截.所以去除了header中文件名;

如需要,可以自行加入(取消注释改行即可);
https://github.com/kalcaddle/KodExplorer/blob/master/app/function/file.function.php#L1010

**Comment by mazhewei** [comment]
已经尝试，完美解决，谢谢
