### ISSUE TITLE
升级1.49后系统奔溃，无法进入，报错Class "KodUser" not found

### ISSUE THREAD

**Issue by star00138** [kalcaddle/kodbox#249]
如题，升级1.49后系统奔溃，无法进入，报错Class "KodUser" not found
![Screenshot_2024-01-07-19-57-27-943_org mozilla firefox-edit](https://github.com/kalcaddle/kodbox/assets/47956209/25e1d6ba-63c4-417e-a176-91e2ba72cf4e)

**Comment by kalcaddle** [comment]
未遇到过该问题，看报错是缺失了部分程序文件,
应该是升级解压覆盖时有部分文件没有覆盖成功导致，下载更新包手动解压覆盖一下看看。
https://static.kodcloud.com/update/update/update-1.49.zip

检查一下kod目录权限，必须要有读写权限
