### ISSUE TITLE
CSRF_TOKEN error!

### ISSUE THREAD

**Issue by jssycszyj** [kalcaddle/kodbox#25]
开启csrf保护后
后台管理->服务器管理->PHP详情
CSRF_TOKEN error!

**Comment by jssycszyj** [comment]
> 1. token错误,刷新页面即可.  还有问题检查一下服务器是否用了带了服务器,或者header是否做了屏蔽;
> 2. 后续优化
> 3. 目前用的是阿里云cdn.特别地区速度不行的话建议下载后手动安装.

这个链接CSFR有问题`https://XXXXX/index.php?admin/setting/server&action=phpinfo`
如果在后面手动加上`&CSRF_TOKEN=XXXXX`就可以正常访问
其他页面没有任何问题，比如后台服务器页面，心跳包post会携带CSRF_TOKEN这个参数，返回数据都是正常的

**Comment by kalcaddle** [comment]
> > 1. token错误,刷新页面即可.  还有问题检查一下服务器是否用了带了服务器,或者header是否做了屏蔽;
> > 2. 后续优化
> > 3. 目前用的是阿里云cdn.特别地区速度不行的话建议下载后手动安装.
> 
> 这个链接CSFR有问题`https://XXXXX/index.php?admin/setting/server&action=phpinfo` 如果在后面手动加上`&CSRF_TOKEN=XXXXX`就可以正常访问 其他页面没有任何问题，比如后台服务器页面，心跳包post会携带CSRF_TOKEN这个参数，返回数据都是正常的

感谢反馈,下个版本优化一下该问题.
