### ISSUE TITLE
升级后，发现以前的图片无法预览了，只能下载

### ISSUE THREAD

**Issue by GalensGan** [kalcaddle/kodbox#250]
更新到最新版本后，发现以前上传的图片无法预览了，只能下载下来看。
![image](https://github.com/kalcaddle/kodbox/assets/45629076/8dfd783e-fde0-4382-9c12-2ff5505baf01)

系统：windows server 2022
kodbox 版本：v1.49.09
图片插件版本：photoSwipe v1.60

请问要如何解决呢？

**Comment by kalcaddle** [comment]
正在生成缩略图，稍等一会儿就好了，可以直接双击打开预览的



杭州可道云网络有限公司


------------------ 原始邮件 ------------------
发件人: GALENS ***@***.***&gt;
发送时间: 2024年1月8日 12:29
收件人: kalcaddle/kodbox ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [kalcaddle/kodbox] 升级后，发现以前的图片无法预览了，只能下载 (Issue #250)





 
更新到最新版本后，发现以前上传的图片无法预览了，只能下载下来看。
 image.png (view on web)
 
系统：windows server 2022
 kodbox 版本：v1.49.09
 图片插件版本：photoSwipe v1.60
 
请问要如何解决呢？

**Comment by GalensGan** [comment]
双击打开不行，双击后提示 `the image could not be loaded`:

![image](https://github.com/kalcaddle/kodbox/assets/45629076/94791107-a4a4-49e0-930e-cee9f0a15023)

单击图片中的 the image 链接后，显示 `convert error! localFile=DSC_3664.jpg`

![image](https://github.com/kalcaddle/kodbox/assets/45629076/094f3d05-11bc-4841-bc4d-49991c05551e)

我查了下封面生成配置，也是正确的：
![image](https://github.com/kalcaddle/kodbox/assets/45629076/3acfc699-37db-467e-98ae-250bc2cc223f)

这种情况只针对以前的图片有问题，新上传的没这个问题

**Comment by kalcaddle** [comment]
重新生成即可.

**Comment by GalensGan** [comment]
> 重新生成即可.

请问在哪儿触发重新生成呢？
