### ISSUE TITLE
是否可以支持缩略图预生成？

### ISSUE THREAD

**Issue by kavmors** [kalcaddle/kodbox#251]
服务器配置太低，生成缩略图太慢了，而且Convert命令经常导致CPU 100%卡死。关闭缩略图虽然能缓解，但是没有缩略图使用体验很差

是否可以通过脚本 每天凌晨任务来预生成缩略图？或者可以考虑集成到封面插件、支持后台计划任务直接配置

**Comment by kalcaddle** [comment]
已做相关优化.目前最多三个进程同时生成.
