### ISSUE TITLE
Title on Dialog embedded iframes

### ISSUE THREAD

**Issue by abd3-13** [kalcaddle/kodbox#254]
Hi, Really like kodbox and been using it for a while as a remote gateway, thanks for the app

OK, the issue is i open a lot of webs in a dialog view but i can't differentiate which dialog is which because i open form a dashboard and the title is all was the first web to be opened.

can the Dialog viewer change the title of the dialog viewer to the title of the web that is currently being viewed?

below is a screenshot of my issue
![kodbox_iframe_title](https://github.com/kalcaddle/kodbox/assets/112805391/eeed8bf0-2def-4a16-a92b-648e3cd194e0)

**Comment by kalcaddle** [comment]
You need to set a name for the application yourself, as the browser cannot retrieve title data from other iframes due to cross domain reasons
