### ISSUE TITLE
数据库无法自动备份

### ISSUE THREAD

**Issue by lthwk** [kalcaddle/kodbox#255]
https://github.com/kalcaddle/kodbox/assets/125235014/be57ba38-ed2e-4a53-9d36-053513df8920

可以手动备份数据库，也可以通过点击计划任务的运行进行备份，但就是不根据设置自动运行备份操作。

程序版本：V1.47.02
服务器环境：windows10+nginx1.23.3+php7.4.33+mariadb10.9.5+redis

**Comment by kalcaddle** [comment]
检查服务器是否设置了php运行超时时间.
