### ISSUE TITLE
CSRF_TOKEN error报错

### ISSUE THREAD

**Issue by gabrielpondc** [kalcaddle/kodbox#258]
无法直接在设置把CSRF保护里面关闭，在setting.php里面把csrfProtect设置为0也无效
<img width="822" alt="image" src="https://github.com/kalcaddle/kodbox/assets/26787778/788ff79c-74eb-4d51-8b19-924ee9579ef7">

**Comment by kalcaddle** [comment]
服务器配置问题,服务器需要允许自定义header  (CSRF_TOKEN)
