### ISSUE TITLE
手机上传视频无法播放

### ISSUE THREAD

**Issue by jdysya** [kalcaddle/kodbox#260]
链接: https://pan.baidu.com/s/1owW-3T1UHEuB0KZ8L-GP2g?pwd=ny9m 提取码: ny9m 
相关文件我已上传到云盘，一个是`VID_20240413_165505.mp4`是正常文件，`VID_20240413_165505 (1).mp4`是手机端通过网页上传的视频，经测试手机端上传的视频无法播放，就算下载到本地也无法播放，但是从电脑端上传视频则可正常播放。
<img width="878" alt="image" src="https://github.com/kalcaddle/kodbox/assets/73117213/b86a60e1-a505-4213-8cd8-cf6e5379db64">

后续测试发现：
- 手机拍摄的视频超过几秒钟就会出现这样的情况（较短的视频如1秒则正常），损坏的视频要比正常的视频大一些字节
- 测试几个手机浏览器都是如此，但是使用可道云手机客户端上传的视频是正常的
- 同一个视频，在手机浏览器中上传到可道云会损坏，但是上传到其他网盘（如alist）却是可以正常加载的
- 偏大的图片也会出现类似的问题，怀疑其他类型的文件也会如此
<img width="546" alt="image" src="https://github.com/kalcaddle/kodbox/assets/73117213/a1826806-574f-47fc-8164-3803a4ba20eb">

**Comment by kalcaddle** [comment]
未发现该问题,麻烦提供一下详细操作步骤, 手机操作系统及版本, 使用的浏览器及版本.我们测试下看看.

**Comment by jdysya** [comment]
> 未发现该问题,麻烦提供一下详细操作步骤, 手机操作系统及版本, 使用的浏览器及版本.我们测试下看看.

我试了几个手机都是这样啊，分别是Redmi k70 pro,Honor x10 max，用的自带的浏览器、谷歌浏览器、Edge浏览器都会这样

**Comment by jdysya** [comment]
> 未发现该问题,麻烦提供一下详细操作步骤, 手机操作系统及版本, 使用的浏览器及版本.我们测试下看看.

刚刚又测试了一下，同样的一个视频文件，在官方演示网站(https://demo.kodcloud.com/#user/login)是正常的，但是在我服务器上部署的就不行，不知道是什么原因

**Comment by kalcaddle** [comment]
可能是服务器配置问题引起，升级到最新版看下，方便的话提供个站点和账号我们看看，内网的话安装开启一下内网穿透插件。
email:   warlee#kodcloud.com

**Comment by jdysya** [comment]
> 可能是服务器配置问题引起，升级到最新版看下，方便的话提供个站点和账号我们看看，内网的话安装开启一下内网穿透插件。 email: warlee#kodcloud.com

好的，稍等

**Comment by kalcaddle** [comment]
是存储设置为腾讯cos对象存储时,上传方式为直传时,Android手机浏览器上传时兼容问题(可以设置存储开启中转)
1.50.02  已修复兼容.
