### ISSUE TITLE
图片的缩略图生成是否有bug

### ISSUE THREAD

**Issue by SilenceHS** [kalcaddle/kodbox#261]
目前版本是v1.50.01
上传完图片后，停留在图片文件夹下图片无法自动生成缩略图，只能点入第一张图片等待大图加载完，才会将下方5张图片进行生成缩略图，其余的图片还是不会自动生成

**Comment by jdysya** [comment]
异步进行的，刷新一下试试

**Comment by kalcaddle** [comment]
缩略图生成确实是异步进行的(1.45之后)

之前版本: 进入文件夹,在可视区的需展示缩略图的文件, 直接请求缩略图(已生成直接加载,未生成则进行生成)
优化版本: 进入文件夹,有需要生成缩略图的文件,会全部加入到待生成队列, 后台自动生成;已生成的在可视区的需展示缩略图的文件则拉取缩略图.

**Comment by SilenceHS** [comment]
再次测试，还是觉得进入文件夹后，图片并没能成功加入到生成缩略图队列。操作如下，图一是进入文件夹后的样子，此时并没有缩略图，页面无任何操作，等待20分钟后，再次刷新，无法生成缩略图。当双击打开第一张图片后，刷新页面，如图二，此时加载出6张，但后续图片无法生成缩略图
![1715772372211](https://github.com/kalcaddle/kodbox/assets/33441768/1178e607-38d6-4287-b4e8-f7990d1ab7f0)
![1715772427234](https://github.com/kalcaddle/kodbox/assets/33441768/db2920dd-55f4-4628-9a01-0a0b0a3daf83)

**Comment by zhanghaotian2018** [comment]
同样的问题。Powered by kodbox [V1.56.02](https://doc.kodcloud.com/v2/#/help/changeLog)

**Comment by zhanghaotian2018** [comment]
> 再次测试，还是觉得进入文件夹后，图片并没能成功加入到生成缩略图队列。操作如下，图一是进入文件夹后的样子，此时并没有缩略图，页面无任何操作，等待20分钟后，再次刷新，无法生成缩略图。当双击打开第一张图片后，刷新页面，如图二，此时加载出6张，但后续图片无法生成缩略图 ![1715772372211](https://github.com/kalcaddle/kodbox/assets/33441768/1178e607-38d6-4287-b4e8-f7990d1ab7f0) ![1715772427234](https://github.com/kalcaddle/kodbox/assets/33441768/db2920dd-55f4-4628-9a01-0a0b0a3daf83)

佬友 你的问题解决了吗

**Comment by SilenceHS** [comment]
> > 再次测试，还是觉得进入文件夹后，图片并没能成功加入到生成缩略图队列。操作如下，图一是进入文件夹后的样子，此时并没有缩略图，页面无任何操作，等待20分钟后，再次刷新，无法生成缩略图。当双击打开第一张图片后，刷新页面，如图二，此时加载出6张，但后续图片无法生成缩略图 ![1715772372211](https://github.com/kalcaddle/kodbox/assets/33441768/1178e607-38d6-4287-b4e8-f7990d1ab7f0) ![1715772427234](https://private-user-images.githubusercontent.com/33441768/330785101-db2920dd-55f4-4628-9a01-0a0b0a3daf83.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA4MzczNjIsIm5iZiI6MTc0MDgzNzA2MiwicGF0aCI6Ii8zMzQ0MTc2OC8zMzA3ODUxMDEtZGIyOTIwZGQtNTVmNC00NjI4LTlhMDEtMGEwYjBhM2RhZjgzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzAxVDEzNTEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNTQwY2U5NDFkZmY4Mzk3MThhNDM2YWE2ZDQ5OTNlMGUxYjc1YWViMjIzMTMxMmU1OGQyOTFjODdkMzJjMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2nNFgXwmZfFx_IvFzE3PkoUWl2YQ065WMz6PVaTEd5k)
> 
> 佬友 你的问题解决了吗

我已经解决，目测是某个版本引起的bug，更新也会随版本更新带上来，我的解决办法是推荐改成docker完全重新部署，干净也稳定，目前版本v1.56.02正常了

**Comment by zhanghaotian2018** [comment]
> > > 再次测试，还是觉得进入文件夹后，图片并没能成功加入到生成缩略图队列。操作如下，图一是进入文件夹后的样子，此时并没有缩略图，页面无任何操作，等待20分钟后，再次刷新，无法生成缩略图。当双击打开第一张图片后，刷新页面，如图二，此时加载出6张，但后续图片无法生成缩略图 ![1715772372211](https://github.com/kalcaddle/kodbox/assets/33441768/1178e607-38d6-4287-b4e8-f7990d1ab7f0) ![1715772427234](https://private-user-images.githubusercontent.com/33441768/330785101-db2920dd-55f4-4628-9a01-0a0b0a3daf83.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA4MzczNjIsIm5iZiI6MTc0MDgzNzA2MiwicGF0aCI6Ii8zMzQ0MTc2OC8zMzA3ODUxMDEtZGIyOTIwZGQtNTVmNC00NjI4LTlhMDEtMGEwYjBhM2RhZjgzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzAxVDEzNTEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNTQwY2U5NDFkZmY4Mzk3MThhNDM2YWE2ZDQ5OTNlMGUxYjc1YWViMjIzMTMxMmU1OGQyOTFjODdkMzJjMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2nNFgXwmZfFx_IvFzE3PkoUWl2YQ065WMz6PVaTEd5k)
> > 
> > 
> > 佬友 你的问题解决了吗
> 
> 我已经解决，目测是某个版本引起的bug，更新也会随版本更新带上来，我的解决办法是推荐改成docker完全重新部署，干净也稳定，目前版本v1.56.02正常了

好的  感谢！
