### ISSUE TITLE
可否加入两步验证?

### ISSUE THREAD

**Issue by hudingwen** [kalcaddle/kodbox#264]
例如Google Authenticator,这样即使密码泄露了也不会被盗登入

**Comment by xuzuxing** [comment]
建议自己写插件，然后PR给他们

**Comment by hudingwen** [comment]
php不熟悉，只是想来提个feature，我写vue的时候突然想到，平时也都在用可道云做日常记录，还是很不错的一款管理软件。

**Comment by hudingwen** [comment]
现在是每个网站都有一个密码，大多都是一样的，一单泄露就会出现其他网站被爆破，所以加上双因子认证我觉得还是有必要，现在我的每个网站都基本上加上了。说个说活生生的例子，之前网易云密码泄露导致我其他平台被爆破登录了。。。然后东西被盗了。

**Comment by kalcaddle** [comment]
目前支持邮箱验证码,短信验证码. 二次登录验证.
<img width="926" alt="image" src="https://github.com/kalcaddle/kodbox/assets/3761968/4138f41d-8c21-49be-b993-a4b88dc7f19a">


其他验证方式,有兴趣可以自行扩展一下.
