### ISSUE TITLE
1.49升1.5 手动升级失败文件消失 自动会弹出nginx

### ISSUE THREAD

**Issue by Chickenbi24** [kalcaddle/kodbox#265]
自动升级会弹出ajax error 502 Bad Gateway

手动升级 解压包放到config  点自动更新后 解压包消失  然后变成自己下载 然后弹出ajax error 502 Bad Gateway死循环

**Comment by kalcaddle** [comment]
没遇到过该问题. 可能和服务器配置有关. 一般是解压失败或解压覆盖失败(权限等问题)
可以下载升级包,手动解压覆盖. 完成后重置一下程序目录权限.
