### ISSUE TITLE
V1.50.02 收藏夾捷徑失效

### ISSUE THREAD

**Issue by poikladevv88** [kalcaddle/kodbox#269]
V1.50.02 收藏夾捷徑失效
點擊修復看到的路徑是正確的 {userFav}/

![image](https://github.com/kalcaddle/kodbox/assets/30821211/9a655e65-b1e9-413a-8b5c-32f19e644c8c)
![image](https://github.com/kalcaddle/kodbox/assets/30821211/900afa58-05c7-42e6-8d6f-543ba1614e43)

**Comment by kalcaddle** [comment]
这是新增自动检测添加收藏的内容,是否存在做的功能.
屏蔽了收藏夹继续收藏收藏夹的功能; 下个版本将该特性加回来.
