### ISSUE TITLE
docker 方式在Ubuntu 22.04 中部署，上传文件，大于4M一律失败

### ISSUE THREAD

**Issue by GiveMeSunShine** [kalcaddle/kodbox#271]
文档地址：https://docs.kodcloud.com/setup/dockerOffline/
上传下载配置：
<img width="1343" alt="image" src="https://github.com/kalcaddle/kodbox/assets/19524490/7d5127a6-0a73-48c5-b99c-b4879d432df9">
docker 内的配置也修改了
<img width="795" alt="image" src="https://github.com/kalcaddle/kodbox/assets/19524490/f92718b9-aa73-4389-9c1d-b0e7e2a25335">
但是依然上传不上去

**Comment by kalcaddle** [comment]
没遇到过该问题, 可能是php.ini 修改的不对,或者没有生效.
如果服务器别的地方有网络拦截, 修改php.ini也是没用的. 可以将上传分片大小调小
