### ISSUE TITLE
PDF文件分片加载

### ISSUE THREAD

**Issue by jdysya** [kalcaddle/kodbox#274]
目前在线预览PDF是将整个文件下载到本地，再进行加载的，能否支持分片加载，这样可以提高加载速度
可参考[前端pdf文件预览以及大文件处理](https://juejin.cn/post/7081255849888645156)，该功能需要后端支持

**Comment by kalcaddle** [comment]
目前就支持 range，可以看浏览器控制台的网络请求



杭州可道云网络有限公司


------------------ 原始邮件 ------------------
发件人: jdysya ***@***.***&gt;
发送时间: 2024年6月22日 11:06
收件人: kalcaddle/kodbox ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [kalcaddle/kodbox] PDF文件分片加载 (Issue #274)





 
目前在线预览PDF是将整个文件下载到本地，再进行加载的，能否支持分片加载，这样可以提高加载速度
 可参考前端pdf文件预览以及大文件处理，该功能需要后端支持

**Comment by jdysya** [comment]
> 目前就支持 range，可以看浏览器控制台的网络请求
> 
> 
> 
> 杭州可道云网络有限公司
> 
> 
> ------------------ 原始邮件 ------------------
> 发件人: jdysya ***@***.***&gt;
> 发送时间: 2024年6月22日 11:06
> 收件人: kalcaddle/kodbox ***@***.***&gt;
> 抄送: Subscribed ***@***.***&gt;
> 主题: Re: [kalcaddle/kodbox] PDF文件分片加载 (Issue #274)
> 
> 
> 
> 
> 
>  
> 目前在线预览PDF是将整个文件下载到本地，再进行加载的，能否支持分片加载，这样可以提高加载速度
>  可参考前端pdf文件预览以及大文件处理，该功能需要后端支持
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

那是前端没有适配吗。为什么我加载pdf需要等待进度条结束才能显示内容

**Comment by kalcaddle** [comment]
range分片获取下载是支持的, pdfjs前端还判断了Access-Control-Expose-Headers这个header;
已加入兼容, 下个版本更新到.
