### ISSUE TITLE
插件配置中pluginAuth字段无效

### ISSUE THREAD

**Issue by jdysya** [kalcaddle/kodbox#278]
如图是在后台插件中心配置选项

<img width="616" alt="image" src="https://github.com/kalcaddle/kodbox/assets/73117213/2b26e20f-0587-4641-9d70-02850f360cff">
该配置经调试发现是有效的

![image](https://github.com/kalcaddle/kodbox/assets/73117213/a21e13e8-442a-48e9-9f93-1e5828f9a892)

-----

但是若根据[文档-插件配置参考](https://doc.kodcloud.com/v2/#/plugins/package)中的描述，将插件目录下的`package.json`中内容修改如下：
```json
{
  "id": "pluginTest",
  "name": "test",
  "title": "测试 test",
  "version": "1.12",
  "category": "tools",
  "source": {
    "className": "font-icon ri-time-line bg-blue-6"
  },
  "description": "测试插件",
  "auther": {
    "copyright": "jdysya.",
    "homePage": "http://kodbox.test"
  },
  "configItem": {
    "pluginAuth": {
      "type": "userSelect",
      "value": "all:0;user:1;group:1;role:1",
      "display": "使用权限",
      "desc": "指定权限组、用户组、用户的用户可以访问",
      "info": "",
      "require": 1
    }
  }
}
```
在后台插件中心中则没有变化
<img width="616" alt="image" src="https://github.com/kalcaddle/kodbox/assets/73117213/84190aea-8d82-4899-ba14-22c79439b6d3">

调试发现，代码中获取到的配置内容也并非`package.json`中的内容
<img width="891" alt="image" src="https://github.com/kalcaddle/kodbox/assets/73117213/e8b00c7c-882e-40d8-befd-b3acac65c664">
<img width="718" alt="image" src="https://github.com/kalcaddle/kodbox/assets/73117213/de216d12-198c-4c21-89f4-235a651db285">

**Comment by kalcaddle** [comment]
数据格式改为了json格式,文档未更新,目前已更新.

另外package.json中的配置默认值,是在安装时更新到数据库的,后续修改插件配置后会是修改后的值.
默认值都不再有效.
