### ISSUE TITLE
Adminer not working

### ISSUE THREAD

**Issue by RallyTuning** [kalcaddle/kodbox#28]
### Update 1.22 to 1.23 = Adminer not work

![Immagine 2021-10-20 180404](https://user-images.githubusercontent.com/50233545/138129648-b563209d-21d6-4c1b-b8a9-824a402b9691.png)

**Comment by kalcaddle** [comment]
this version of adminer not support php8 .
you can download the last version; https://www.adminer.org/  
path: plugins/adminer/adminer/adminer.php.txt    (rename to adminer.php.txt )


we will update this soon.
