### ISSUE TITLE
插件配置中pluginAuth字段不会同步到前端界面

### ISSUE THREAD

**Issue by jdysya** [kalcaddle/kodbox#280]
`packages.json`内容如下：
```json
{
	"id": "pluginTest",
	"name": "test",
	"title": "测试",
	"version": "1.12",
	"category": "tools",
	"source": {
		"className": "font-icon ri-time-line bg-blue-6"
	},
	"description": "测试插件",
	"auther": {
		"copyright": "kodcloud.",
		"homePage": "http://kodbox.test"
	},
	"configItem": {
		"pluginAuth": {
			"type": "userSelect",
			"value": {
				"all": "0",
				"user": "",
				"group": "",
				"role": "1"
			},
			"display": "{{LNG['admin.plugin.auth']}}",
			"desc": "{{LNG['admin.plugin.authDesc']}}",
			"require": 1
		}
	}
}
```
根据[#278](https://github.com/kalcaddle/kodbox/issues/278)中的回复，了解到
> package.json中的配置默认值,是在安装时更新到数据库的,后续修改插件配置后会是修改后的值.
默认值都不再有效.

因此将插件重新安装，再打开后台管理界面插件面板查看结果如下
![image](https://github.com/kalcaddle/kodbox/assets/73117213/76a20178-15c5-4776-9872-e77e372aa3ca)
理论上应当显示选中`普通用户`
<img width="448" alt="image" src="https://github.com/kalcaddle/kodbox/assets/73117213/6e90874c-7608-48d2-9b58-d4ac24c6655b">

TIP: 其他配置项暂未测试

**Comment by kalcaddle** [comment]
看起来像是id可能不存在
不推荐在权限分配的默认值中直接指定用户,权限组; 因为id可能在不同用户表现的不一样
