### ISSUE TITLE
升级到1.51.02上传文件失败

### ISSUE THREAD

**Issue by geteshi** [kalcaddle/kodbox#281]
失败原因：
```
Fatal error: Allowed memory size of 4194304000 bytes exhausted (tried to allocate 262144 bytes) in
```
![image](https://github.com/kalcaddle/kodbox/assets/62454093/ed3ad7fd-8a41-4b6c-86e8-adfe8de4fa23)
php配置：
![image](https://github.com/kalcaddle/kodbox/assets/62454093/b7aded9c-172e-46b3-8f3b-98b917144cee)
nginx配置：
![image](https://github.com/kalcaddle/kodbox/assets/62454093/2c830e27-8da1-4bc0-a177-ed502422bfb2)

**Comment by kalcaddle** [comment]
未测试出该情况. 方便的话提供个地址和账号(内网的话,安装一下内网穿透插件并开启)
email: warlee#kodcloud.com

**Comment by geteshi** [comment]
已发送

**Comment by geteshi** [comment]
非常耐心的帮忙解决了，非常感谢！
