### ISSUE TITLE
思绪思维导图导出图片或者PDB BUG

### ISSUE THREAD

**Issue by sleikang** [kalcaddle/kodbox#282]
![image](https://github.com/kalcaddle/kodbox/assets/23020770/ba5af78d-edd7-4dac-969a-285e1b071400)
思绪思维导图是否每次升级只是合并了官方的某些功能，因为我使用官方思绪思维导图是没有这个BUG的，而在kodbox里面最近连续升级2个新版本了 都一直存在这个历史BUG

**Comment by kalcaddle** [comment]
包含演示站所有功能,代码库来源: https://github.com/wanglin2/mind-map/tree/main/dist. 
效果基本和演示站一致.https://wanglin2.github.io/mind-map/#/  只增加了文件获取保存相关逻辑.

可以查看代码文件部分.

**Comment by sleikang** [comment]
但是同样的思维导图 就只有kodbox里面导出文本过长自动换行的那种显示不全，你可以操作试试，新建一个思维导图 文本内容长一点 只要有自动换行的 最下面换行的都显示不全，而官方demo并没有这个问题

**Comment by kalcaddle** [comment]
看看导图主界面配置是否一致
提供个文件我们看一下，描述一下详细操作步骤





杭州可道云网络有限公司


------------------ 原始邮件 ------------------
发件人: xiaojun lei ***@***.***&gt;
发送时间: 2024年7月5日 19:13
收件人: kalcaddle/kodbox ***@***.***&gt;
抄送: warlee ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [kalcaddle/kodbox] 思绪思维导图导出图片或者PDB BUG (Issue #282)





 
但是同样的思维导图 就只有kodbox里面导出文本过长自动换行的那种显示不全，你可以操作试试，新建一个思维导图 文本内容长一点 只要有自动换行的 最下面换行的都显示不全，而官方demo并没有这个问题

**Comment by sleikang** [comment]
[思维导图.zip](https://github.com/user-attachments/files/16110439/default.zip)
![image](https://github.com/kalcaddle/kodbox/assets/23020770/73a9ef1b-389d-416c-b72f-e5dec5ad16e0)
![image](https://github.com/kalcaddle/kodbox/assets/23020770/5c73afd9-90e0-409b-bf5d-d800aded01cd)
![image](https://github.com/kalcaddle/kodbox/assets/23020770/0f0dd5bb-cab9-4020-9e91-4b2e9e47e3c3)

**Comment by sleikang** [comment]
就用上面的附件.smm在kodbox打开然后导出pdf 在官方里面打开导出pdf

**Comment by kalcaddle** [comment]
ok
后面版本优化一下

**Comment by kalcaddle** [comment]
查询到页面样式指定了body的font-size时引起的.目前去除了.
插件已更新,在线升级即可.

**Comment by sleikang** [comment]
> 查询到页面样式指定了body的font-size时引起的.目前去除了. 插件已更新,在线升级即可.

最新版本1.55.04又出现这个BUG 离谱啊 修复了后面又会还原回去吗

**Comment by kalcaddle** [comment]
修改其他地方影响到了这里, 
已优化处理.在线升级即可.
