### ISSUE TITLE
Call to undefined function disk_total_space()

### ISSUE THREAD

**Issue by RallyTuning** [kalcaddle/kodbox#283]
This message appear at every login or refresh. Some free webhosts doesn't allow that function, so if KodBox can't determinate the total space, just set it to unlimited without notice more than one time, please!

![image](https://github.com/kalcaddle/kodbox/assets/50233545/7e446969-735f-498b-ad8e-2b111d8b1b76)

Instead, this come in the settings menu:

![image](https://github.com/kalcaddle/kodbox/assets/50233545/a276aefe-c61c-46c2-b820-49303a5147ed)

Anyway, the app works "good" without these 2 functions, so just make this message show one time only to let who dont have a paid hosting to enjoy at least the half of the app, (upload and download works).
Thank you

**Comment by kalcaddle** [comment]
It is compatible with this situation and can be upgraded to the latest version.
