### ISSUE TITLE
如何使用NGINX反代

### ISSUE THREAD

**Issue by bin862324915** [kalcaddle/kodbox#284]
我的网站是使用NGINX反代的，其他目录都是可以正常访问的，唯独访问kodbox目录的时候无法正常使用，控制台提示如下内容
Uncaught (in promise) DOMException: Failed to register a ServiceWorker: The origin of the provided scriptURL ('https://test.test.com:62081') does not match the current origin ('https://test.test.com').
希望能得到您的帮助，非常感谢

**Comment by kalcaddle** [comment]
参考 
https://github.com/kalcaddle/kodbox/issues/279

**Comment by bin862324915** [comment]
很抱歉，根据您发的参考，我试了一下，好像并没有效果，我的设置如下
<?php
define('APP_HOST','https://cloud.eric008.us.kg/');

NGINX
        location / {
            proxy_pass   http://127.0.0.1:65081/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            client_max_body_size 500000M;
        }
kodbox目录https://cloud.eric008.us.kg/pan/
无法正常打开
其他应用目录https://cloud.eric008.us.kg/music/
可以正常打开
希望可以得到您进一步的帮助

**Comment by kalcaddle** [comment]
需要带上子目录

**Comment by bin862324915** [comment]
非常感谢您解决了我这个问题，我想再请问一下，怎么添加多个自定义域名呢，我尝试了一下下面这个配置，网页访问起来似乎还是有问题
```
<?php
define('APP_HOST','https://cloud.eric008.us.kg/pan/');
define('APP_HOST','https://cloud.zzzwb.com:60082/pan/');
```

**Comment by kalcaddle** [comment]
手动指定只能一个站点

**Comment by bin862324915** [comment]
是否有其他方法可以实现多个域名指向kodbox这个应用呢

**Comment by kalcaddle** [comment]
> 是否有其他方法可以实现多个域名指向kodbox这个应用呢
手动指定只能一个站点.

程序本身是支持域名自适应的,多个的话需要移除手动指定的内容.
(如果有没正确获取站点域名的情况,就是上述说明的原因,header没有正确设置,需要自行配置.    也可以将kodbox升级到最新版再试)

**Comment by bin862324915** [comment]
好的，感谢您的耐心解答，同时也谢谢您的付出创造这么好的项目
