### ISSUE TITLE
升级到最新1.51版本之后通过域名访问无响应

### ISSUE THREAD

**Issue by larriti** [kalcaddle/kodbox#285]
1.50版本通过局域网和域名访问都是OK的，升级到最新版本之后无法访问，可以局域网访问
1.先是通过Nginx静态代理，可以通过8081端口访问
2.然后通过openresty反代到8081，这个没法访问了，通过chrome浏览器查看为第一次域名是https://kod.dreamflytech.com返回200，第二次就是https://kod.dreamflytech.com:8081，这个肯定就是访问不了了，这个需要怎么解决
![image](https://github.com/kalcaddle/kodbox/assets/14367631/6ebec9a3-5625-445a-a9f7-1f99283fb491)
![image](https://github.com/kalcaddle/kodbox/assets/14367631/1c3e737f-3738-406c-a295-c38aaaae21a6)

**Comment by kalcaddle** [comment]
参考
https://github.com/kalcaddle/kodbox/issues/284

**Comment by larriti** [comment]
照着改了还是一样，我想问下为啥之前的版本可以现在不行了，就是升级了一下，其它配置都没动的

**Comment by larriti** [comment]
可以了，文件中忘了加<?php ，现在是必须要在文件中加这个了吗，之前的不用加这个文件也是可以的

**Comment by kalcaddle** [comment]
多次反向代理需要 header 带入对应域名及端口，1.51版本兼容了部分服务器配置反向代理  https 带自定义端口的情况，但和你这种类似情况导致互斥。看来没法通过代码来兼容所有情况了，后面版本考虑别的方式再看下吧。

**Comment by larriti** [comment]
好的，感谢
