### ISSUE TITLE
通过docker-compose部署服务后 无法进行安装向导

### ISSUE THREAD

**Issue by hahaha5610** [kalcaddle/kodbox#286]
通过docker-compose能够成功部署服务但是访问页面时无法正常进行安装向导，会直接到账号设置这一步。并没有设置MySQL连接信息那一步
![image](https://github.com/kalcaddle/kodbox/assets/55316144/d14b7936-5007-4489-87f1-842df312db28)

直接点击账号设置又会报数据库连接错误
![image](https://github.com/kalcaddle/kodbox/assets/55316144/bd916d75-5ead-4070-bdea-de5e727c0d18)

**Comment by d1ngx** [comment]
是参考这个[教程](https://docs.kodcloud.com/setup/docker/)的吗，请检查确认“**需在db.env中设置数据库密码，还有yml中的MYSQL_ROOT_PASSWORD需补充.**”，补充参数后 清除环境重新启动`docker compose down;rm -rf site db;docker compose up -d`
