### ISSUE TITLE
启动备份后计划任务没有任务，备份进度也一直没有加载

### ISSUE THREAD

**Issue by hyxl520** [kalcaddle/kodbox#287]
![image](https://github.com/user-attachments/assets/ce74dc17-7ae9-4349-96e4-e695fb734ddf)
如图所示，我启动备份后，没有相关计划任务，进度也一直为0

**Comment by kalcaddle** [comment]
未遇到过该情况, 可以尝试清空缓存后,在启用看看.

还不行的话, 比较大的可能是php.ini强制设置了超时时间比较短,导致计划任务后台进程被强制结束了.
或者php允许进程数过少,导致后台计划任务无法持续后台运行.

**Comment by hyxl520** [comment]
通过调大超时时间到300秒，并且php允许进程数调大后依然跟原来的情况一样
![image](https://github.com/user-attachments/assets/3074964e-376a-4bac-8782-f17e66c6f9f8)

**Comment by kalcaddle** [comment]
方便的话提供下服务器地址和测试账号我们看看(如果是内网,可以先安装内网插件插件并启用一下.)
email: warlee#kodcloud.com
