### ISSUE TITLE
服务器中转支持详细配置

### ISSUE THREAD

**Issue by jdysya** [kalcaddle/kodbox#288]
<img width="692" alt="image" src="https://github.com/user-attachments/assets/076e5efb-424a-42d7-9d28-13e080aa9130">

目前服务器中转功能开启后，是对所有文件进行中转，由于我的服务器带宽较小，大文件使用服务器中转加载太慢，能否提供更加细致的配置方式，例如
1. 根据文件大小判断是否需要服务器中转
2. 根据文件类型判断是否需要服务器中转
3. 根据当前使用场景（在线预览还是下载）判断是否需要服务器中转

**Comment by kalcaddle** [comment]
目前无法做到. 正常来说像阿里oss对象存储等, 只要外网能直接访问对象存储服务,是不需要启用服务器中转的.
