### ISSUE TITLE
通过1panel应用商店安装。缺少的PHP插件

### ISSUE THREAD

**Issue by 2909109449** [kalcaddle/kodbox#289]
通过1panel应用商店安装。缺少如下PHP插件Mcrypt，Sockets，Swoole,求大佬指导指导如何补上
![屏幕截图 2024-07-19 100017](https://github.com/user-attachments/assets/8de0b608-f0b6-4ffb-a172-077aa994c927)

**Comment by kalcaddle** [comment]
目前不是必须的,可以忽略.
安装的话类似宝塔面板, 安装上对应扩展即可.
