### ISSUE TITLE
New wallpapers bug

### ISSUE THREAD

**Issue by RallyTuning** [kalcaddle/kodbox#29]
We can't use custom uploaded new wallpapers in the personal menu without renaming them "10", "11", "12"... If we leave the original name ("my custom wallppaper.jpg") and we select them, the background of the app will be empty.

**Comment by kalcaddle** [comment]
![image](https://user-images.githubusercontent.com/3761968/140492102-991330e3-ccac-4a52-967e-8c802e40c16e.png)
![image](https://user-images.githubusercontent.com/3761968/140492160-7b6e1960-c719-4cb4-8612-a9b0a2f07ecf.png)


I can't find this problem
