### ISSUE TITLE
思绪思维导图编辑时丢失快捷键活动

### ISSUE THREAD

**Issue by sleikang** [kalcaddle/kodbox#290]
复现流程
1.打开思绪思维导图，编辑中按Enter 或者Tab 添加节点都正常，然后点击小化窗口
2.随便打开一个word文档, 加载完成后直接点击小化窗口
3.点击任务栏思绪思维导图窗口，开始编辑，这个时候发现按Enter 或者Tab 无法添加节点，快捷键的活动权限留在了kodbox主页面，比如我的思绪思维导图和word文档都放在我的文档文件夹下面，激活思绪思维导图窗口 按Enter的时候如果我的文档文件夹下有文件选中直接打开了那个文件

按照上面流程发现切换活动窗口时快捷键活动没有释放重新激活给打开的窗口

**Comment by kalcaddle** [comment]
思维导图库没有自动捕获焦点引起的(drawio,svgeditor等没有该问题)
优化了一下插件,鼠标点击后自动捕获焦点. 在线升级即可.
