### ISSUE TITLE
Bug: operation failed!mkfile error

### ISSUE THREAD

**Issue by gingerbeardman** [kalcaddle/kodbox#291]
Hi,

I am moving to kodbox from [filebrowser](https://github.com/filebrowser/filebrowser). 
And I'm using docker version.

My server contains many websites, managed by [EasyEngine](https://github.com/EasyEngine/easyengine):
- some are plain html
- some are php

I can add the mapped directories as "Network Driver" storage locations in kodbox
- plain html sites are added just fine
- some php sites fail "operation failed!mkfile error"

<img width="300" alt="Screen shot 2024-07-25 at 16 57 48" src="https://github.com/user-attachments/assets/cd64f91b-b033-442c-8766-6df66e267bdf">

## Debug
- Unix file/dir permissions are fine.
- All sites work OK with my filebrowser install.

How can I troubleshoot further?

## Screenshot
<img width="892" alt="Screen shot 2024-07-25 at 17 21 16" src="https://github.com/user-attachments/assets/8b050fd8-5ca6-48d2-9d7f-b41c0ff8e464">

**Comment by kalcaddle** [comment]
The mounted directory must have read and write permissions.
Error: Directory check failed.
It may be that the directory address is wrong or there is no write permission. In addition, the directory needs to end with /.
You can try to enter the corresponding directory address in the file management address bar to check.


<img width="1149" alt="image" src="https://github.com/user-attachments/assets/8eef1756-3776-49fb-8be5-2339a6cf4427">

**Comment by gingerbeardman** [comment]
Sadly, all of those things were OK... so I eventually gave up.

Best of luck!
