### ISSUE TITLE
可道云的计划任务不能启动

### ISSUE THREAD

**Issue by hyxl520** [kalcaddle/kodbox#292]
很多计划任务，如备份、告警都似乎不能启动，线程数也一直都是0，请问有什么解决办法吗，目前的PHP的最大执行时间是3000
![image](https://github.com/user-attachments/assets/2d6b289d-ac57-4691-b5e1-88b56f35699c)

**Comment by kalcaddle** [comment]
https://github.com/kalcaddle/kodbox/issues/287
重复问题.

基本上是服务器做了什么限制, php配置问题,或者其他监控或安全程序,
自动将长任务后台进程定期强制结束了.
