### ISSUE TITLE
插件中心无法更新

### ISSUE THREAD

**Issue by Hi-Peanut** [kalcaddle/kodbox#293]
最近更新了最新版本V1.52.02，发现插件中心无法更新、无法新装插件。但是检查了服务器是可以ping通api.kodcloud.com。
![360截图20240730000615827](https://github.com/user-attachments/assets/bc4556f0-b0d2-4d4d-89c4-3549ae5aaca5)

**Comment by kalcaddle** [comment]
提示的信息已经给出了,服务器缺少网络请求相关库, 安装一下即可.

**Comment by Hi-Peanut** [comment]
> 提示的信息已经给出了,服务器缺少网络请求相关库, 安装一下即可.

你好，服务器是PHP8.1，检查了curl、openssl都是正常的。但是很奇怪的是，虽然无法更新插件，但是能获取哪些插件有更新
![360截图20240831012759730](https://github.com/user-attachments/assets/10923d44-8c87-4dd3-954a-4da0b7aa59ff)
![360截图20240831012825284](https://github.com/user-attachments/assets/d1e966ce-c5fa-4419-98d1-06cb0600017f)
