### ISSUE TITLE
预览ppt文件一直处于数据转换中，查看web后台请求，转换出错

### ISSUE THREAD

**Issue by LifeIsBinary** [kalcaddle/kodbox#296]
#### 问题截图
![image](https://github.com/user-attachments/assets/ef78ee8f-39d2-47ec-9d74-e99bac113940)

#### 环境
* 系统：Win10企业版 19045.4780
* kodbox版本： docker部署免费版

#### 问题复现步骤
1. 上传后管理员第一次预览无问题
2. 之后使用Ubuntu18.04系统预览显示数据转换中
3. 再使用管理员预览也显示数据转换中。
该文件为网络上下载测试的ppt文件，自己新建ppt，上传各账号预览无问题。

#### 原始ppt文件附件
[8016.pptx](https://github.com/user-attachments/files/16632150/8016.pptx)

#### 感谢
感谢你们的工作，很不错的项目，很刚需

**Comment by kalcaddle** [comment]
推荐安装onlyoffice或本地office预览解析组件, 

没有本地组件时,会尝试上传到永中office服务器进行解析预览调用(文件涉及安全的不推荐此设置), 需要服务器上传,等待等操作,网络影响情况比较大,或永中服务器也可能做限速丢弃等情况影响.
