### ISSUE TITLE
下载大量文件后RAM中的缓存爆满且下载速度缓慢

### ISSUE THREAD

**Issue by NyankoSong** [kalcaddle/kodbox#297]
你好！
我在使用过程中，不论上传还是下载都会增加RAM中的cached大小，且不会自动回收，一旦爆满（传输量到达可用RAM上限）就会导致下载速度奇低。
想请问如何排障，谢谢！

**Comment by kalcaddle** [comment]
没遇到过该情况,可能和服务器配置有关.

上传下载过程中内存增加是正常的,但也不会很多(上传分片,下载流的方式, 单个进程大概也就占用50M左右, 并发高内存不大的情况下可以修改php配置,调小最大进程数),请求完成后fpm终止后,会自动释放对应内存.

**Comment by NyankoSong** [comment]
> 没遇到过该情况,可能和服务器配置有关.
> 
> 上传下载过程中内存增加是正常的,但也不会很多(上传分片,下载流的方式, 单个进程大概也就占用50M左右, 并发高内存不大的情况下可以修改php配置,调小最大进程数),请求完成后fpm终止后,会自动释放对应内存.
> 

我检查了我的php-fpm.conf，max_spare_servers指定为24。下载文件时，占用的内存cached内容和文件大小相同，远大于50M，与此同时服务器内存为256G，最后会全部吃满。
我检查了下服务器内存占用情况，数日前占用的cached内容仍然没有被回收，这也是我不解的地方。。

**Comment by kalcaddle** [comment]
下载都是流式的,内存占用基本上不会超过2M(win/linux各种系统都测试过;)
官网demo,阿里云非常普通的服务器,内存2G,并发100以内基本上内存都跑不满.
看一下内存是被那些进程占用的. 是否开起了什么特殊机制或配置.


可以测试安装其他php版本,或者换用宝塔面板等环境测试对比一下看看.
