### ISSUE TITLE
剪贴板粘贴多个文件无法上传

### ISSUE THREAD

**Issue by jdysya** [kalcaddle/kodbox#299]
当粘贴板存在多个文件时，粘贴上传控制台会报错（单个文件没有问题）
![image](https://github.com/user-attachments/assets/7fbfad20-d236-4bbc-867e-eac0bc1dc406)

**Comment by kalcaddle** [comment]
未测试出该情况, 在官网demo上测试一下看看/或换不同浏览器对比测试看看.
麻烦提供一下浏览器及版本/操作系统及版本;

**Comment by jdysya** [comment]
> 未测试出该情况, 在官网demo上测试一下看看/或换不同浏览器对比测试看看. 麻烦提供一下浏览器及版本/操作系统及版本;

官网demo没有这个问题，我又测试了下，在不同浏览器也是一样的，在手机上有时候也没法上传，发现是部分文件上传就会出现那个报错，就会导致所有文件都无法上传

**Comment by kalcaddle** [comment]
官网demo未出现, 先升级到最新版看看.
这种报错可能是前端浏览器兼容问题, 和后端无关. 

具体描述一下如何复现, 提供下浏览器及版本.
