### ISSUE TITLE
Request: Beautify main.css

### ISSUE THREAD

**Issue by RallyTuning** [kalcaddle/kodbox#30]
### Some languages such as italian (my), german and french, can have long terms (words) and they will not fit in the CSS box, as these examples:

![Screenshot_2](https://user-images.githubusercontent.com/50233545/138131247-6adafbab-aeb0-497e-82e9-01bdb6d2b2bb.png)
![Screenshot_3](https://user-images.githubusercontent.com/50233545/138131443-16bcc2c3-4574-4f1f-b5bf-57728e46c31c.png)

-----
### So, if you can change the CSS in multilines instead of one single line, we can help you fix these. in this way:

![Screenshot_4](https://user-images.githubusercontent.com/50233545/138131853-899f54b3-b177-4764-b08a-24038ee9de4a.png)
![Screenshot_5](https://user-images.githubusercontent.com/50233545/138132358-a3b8550e-bfea-4b42-a57a-7bdce64ae9e9.png)

**Comment by kalcaddle** [comment]
We will fixed it next version.
