### ISSUE TITLE
流程图点保存界面会错位

### ISSUE THREAD

**Issue by sleikang** [kalcaddle/kodbox#301]
![image](https://github.com/user-attachments/assets/d5eb716f-048a-4876-8e59-a27b070c570f)

**Comment by kalcaddle** [comment]
浏览器兼容问题,升级到最新版.

**Comment by sleikang** [comment]
> 浏览器兼容问题,升级到最新版.

用的Microsoft Edge 版本 129.0.2792.52 (正式版本) (64 位)，一直都是最新版还是有这个问题
![image](https://github.com/user-attachments/assets/b338b8a9-3018-4d15-b02d-bec51c1ca4be)

**Comment by kalcaddle** [comment]
没测试出来, 访问官网demo对比看看.
描述一下具体操作步骤.

**Comment by sleikang** [comment]
> 没测试出来, 访问官网demo对比看看. 描述一下具体操作步骤.

官网demo一样啊，我在官网新建一个流程图 随便拖几个框框点保存就这样了
![image](https://github.com/user-attachments/assets/5534800d-0e14-4cc4-b82e-bb8f78b4d2f0)
[新建文件.zip](https://github.com/user-attachments/files/17146271/default.zip)

**Comment by sleikang** [comment]
![image](https://github.com/user-attachments/assets/92939698-d33f-437e-b275-1dff28bdfb59)
文件还在demo可以试试

**Comment by kalcaddle** [comment]
![Uploading image.png…]()
保存正常, 依然没测试出这种情况.

**Comment by kalcaddle** [comment]
<img width="1493" alt="image" src="https://github.com/user-attachments/assets/9da9b518-9a2e-42e7-b0f8-eeacc35c2f6e">
保存正常, 依然没测试出这种情况.

**Comment by sleikang** [comment]
> <img alt="image" width="1493" src="https://private-user-images.githubusercontent.com/3761968/371080476-9da9b518-9a2e-42e7-b0f8-eeacc35c2f6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDQzNzcsIm5iZiI6MTcyNzM0NDA3NywicGF0aCI6Ii8zNzYxOTY4LzM3MTA4MDQ3Ni05ZGE5YjUxOC05YTJlLTQyZTctYjBmOC1lZWFjYzM1YzJmNmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMDk0NzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWM4NzE3NDkwYzcyMWFkZWU2NzY5YjMxNTAyYjZiMzZmNDlmMWRkYWU4ODA4YTZiNjUzNjBjNWMxMWUwNGQxMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.BYhGL1_rNx_wOpGbNNX0KgF7IFziQesckJxChHJQ_yw"> 保存正常, 依然没测试出这种情况.

破案了 你没用深色模式 就是深色模式下会这样

**Comment by kalcaddle** [comment]
测试出来了,确实如此.
貌似和浏览器渲染有关
```
.geDarkMode { filter: invert(93%) hue-rotate(180deg);}
// 这行样式导致页面有绝对定位的内容时错位了
```



以优化兼容,下个版本更新.
