### ISSUE TITLE
webdav设置成默认存储问题

### ISSUE THREAD

**Issue by Sika-Liu** [kalcaddle/kodbox#302]
webdav设置成默认存储后，上传的视频，图片和文档都无法打开，要怎么办呢

**Comment by Sika-Liu** [comment]
挂载的是AList中的阿里云盘

**Comment by kalcaddle** [comment]
已兼容优化: 插件中心更新一下webdav插件即可. 
aliist挂载阿里云盘,再挂载到kod中,文件无法打开问题兼容(阿里云盘文件访问url做了referer校验)
