### ISSUE TITLE
51LA统计代码和灵雀应用监控代码兼容问题

### ISSUE THREAD

**Issue by JsaRut** [kalcaddle/kodbox#303]
Kodbox似乎对于51LA的统计代码、灵雀应用监控代码存在兼容问题
Kodbox版本：1.52
统计代码：51LA V6，开启功能：事件统计，单页面(SPA)应用支持
加载方式：同步安装
弹窗错误1：ReferenceError: LA is not defined
弹窗错误2：TypeError: Cannot read properties of null (reading 'indexOf')

灵雀应用监控
加载方式：同步安装<script>，开启功能：程序异常、接口请求异常、资源异常、性能上报、卡顿监测、外链监控、可疑脚本/iframe检测、单页面(SPA)应用上报
弹窗错误：ReferenceError: LingQue is not defined

**Comment by kalcaddle** [comment]
由于是页面加载后插入html内容, 所以script引入内容,需要是异步的
将统计代码引入, 使用异步的方式即可.


对应不同平台:
51LA中: 配置--配置参数--统计代码--手动安装(选择复制 异步安装 的代码即可)


如果是其他平台或自己的js代码, 有依赖时,将同步改一下成异步即可,类似于:
```
<script>
requireAsync('//sdk.51.la/js-sdk-pro.min.js',function(){
    console.log(444,window.LA);
    LA.init({id:"xxx",ck:"xxx"});
});
</script>
```
