### ISSUE TITLE
GitHub 登录

### ISSUE THREAD

**Issue by Saberwolf915-YT** [kalcaddle/kodbox#304]
我试了很多次了，都说需要绑定 git hub。请修复此问题！

**Comment by kalcaddle** [comment]
不是问题,理解可能有误.

使用第三方登录的前提是, 自己的账号先绑定过对应登录方式
比如说想要能QQ登录, 先登录自己的账号--个人中心--账号设置--第三方账号(绑定QQ);
绑定后,就可以通过QQ登录自己的账号了.  其他微信登录,GitHub登录同理.
