### ISSUE TITLE
请问 io_file 表中 path 字段的 {io:1} 对应的设置在哪儿？

### ISSUE THREAD

**Issue by GalensGan** [kalcaddle/kodbox#305]
起因：
原来在 windows 中部署的 kodbox，里面的文件存储在 `D:\kodbox\data` 中，现在改成 Docker 部署，将数据库导入后，kodbox 自动在程序根目录下生成了目录 `D:\kodbox\data`，也无法上传文件。

我怀疑是 `{io:1}` 设置还是 windows 上的路径的缘故，但是找不到在哪儿修改，请问如何修改 `{io:1}` 对应的位置呢？

**Comment by GalensGan** [comment]
关于无法上传问题，找到原因了，是因为 `data` 目录权限问题。
但 `D:/kodbox/data/.history_7eFhIStin` 这个目录还是会自动生成，不知道什么原因

**Comment by kalcaddle** [comment]
io后面跟的是自增id,不需要调整.

迁移服务器的,需要将程序/数据库迁移过去;
只是自带的初始默认存储的话(默认存储物理路径在 ./data/files/) , 相对路径保持不变,就无需做任何调整
如果添加了其他物理存储, 迁移服务器后, 添加的物理存储文件夹迁移到新的服务器,
文件夹路径发生变化时, 需要修改一下对应存储的路径即可
管理员后台---存储文件---存储管理(找到要调整的存储,菜单)--修改配置(勾选强制修改)--- 将存储目录修改成新的路径即可.

**Comment by GalensGan** [comment]
请问为什么会自动生成这个 `D:/ProgramFiles/...` 目录呢，这个目录是我 windows 上的目录，现在我用 docker 部署，它总会自动创建
![image](https://github.com/user-attachments/assets/74a8c134-2b00-4299-bf4d-70f3271b5c30)

**Comment by kalcaddle** [comment]
看样子是手动指定了DATA_PATH目录, 去除手动指定的内容即可(config/define.php 中)
