### ISSUE TITLE
macos下载失败

### ISSUE THREAD

**Issue by SkywardSky** [kalcaddle/kodbox#309]
在macos系统上下载云盘中的内容会卡99%，比如zip、txt、pdf等，但是jpg又可以正常下载
![image](https://github.com/user-attachments/assets/4eb9ef9b-c491-4a62-aa29-641812765875)
![image](https://github.com/user-attachments/assets/9a60d998-7494-4668-a82f-e36e923287e5)

这种情况有点像golang在输出http文件流时，当文件输出完后，没有强制刷新缓冲区，而导致的结果一致，也是在macos系统上下载卡99%，但是windows又是正常的。鉴于不会php，所以只能提供其他语言处理类似情况的结果

**Comment by kalcaddle** [comment]
没遇到过该情况,可能是服务器配置问题, 对比测试下官网demo看看.
