### ISSUE TITLE
Office plugins not working properly

### ISSUE THREAD

**Issue by RallyTuning** [kalcaddle/kodbox#31]
I don't know why but some files can't be open with the office plugin, so i was trying to edit the this plugin but the window for settings customization don't work neither.
Where you see the `red arrow`, mean that i cannot scroll down. `Yellow arrows` mean these buttons dosen't work if i press them.

![Screenshot_4](https://user-images.githubusercontent.com/50233545/138568821-9aa9e8ed-0e15-4f07-be9f-0b393fb254e1.png)

**Comment by kalcaddle** [comment]
The plug-in is under development and will be re released after subsequent improvement
