### ISSUE TITLE
Is there a way to view all comments/chats centrally in one place?

### ISSUE THREAD

**Issue by fivestones** [kalcaddle/kodbox#310]
I'm sorry, I don't read Chinese so it's a bit hard for me to use the documentation. I used google translate but didn't find what I was looking for.
Is there some way to see all the comments/chats made that are connected to any file, all in one place? For example, if there is a file `docuement.txt` and it has some comments in the chat, and another file `song.mp3` has some comments in its chat, is there a place I can see all the comments from both of those files, ordered by most recent?
Without this, the only way to discover new comments seems to be to open the file info. If it exists, how do I see it? And if it doesn't exist, consider this a feature request.
Thanks!

**Comment by kalcaddle** [comment]
This function is not supported yet, we will consider adding support later
