### ISSUE TITLE
更新后不显示 下载按钮

### ISSUE THREAD

**Issue by ztdesk1** [kalcaddle/kodbox#312]
![Uploading image.png…]()
![Snipaste_2024-10-22_23-07-01](https://github.com/user-attachments/assets/f276df57-d97a-416f-b92a-175c2f627688)

**Comment by idmanage** [comment]
我这边也是一样，试了官方demo也是这样子

**Comment by kalcaddle** [comment]
已更新优化.在线升级即可.
