### ISSUE TITLE
docker版部署的可道云，pdf，ai，psd等无法生成缩略图

### ISSUE THREAD

**Issue by idmanage** [kalcaddle/kodbox#314]
后台检查过插件一切正常

![Screenshot_2024-10-25-09-27-56-304_mark.via.jpg](https://github.com/user-attachments/assets/23216bc7-607e-4c1d-b5ff-2c57a1609dd6)

**Comment by Zmz-c** [comment]
买个企业版试试

**Comment by kalcaddle** [comment]
检查服务器运行环境, 对应组件是否正确安装,并运行正常
详情参考: https://docs.kodcloud.com/setup/others/#psd
