### ISSUE TITLE
插件中心看不到未安装插件

### ISSUE THREAD

**Issue by Turing-China** [kalcaddle/kodbox#318]
网络正常，使用激活码激活团队版后看不到所有未安装插件，没激活的时候可以正常看到，使用最新版本（ V1.53.07）DOCKER安装，前两个版本也一样
API接口返回 ：抱歉,您已经过了服务期限!暂不提供云端服务,如有需要请续年服务费.

**Comment by kalcaddle** [comment]
已处理.
