### ISSUE TITLE
支持智能文件夹

### ISSUE THREAD

**Issue by jdysya** [kalcaddle/kodbox#319]
类似macos系统中的智能文件夹，能够将筛选的结果保存作为一个文件夹，包括标签筛选。
具体实现就是将筛选条件保存，当访问该智能文件夹时根据保存的筛选条件进行筛选，可能的话最好能有缓存功能，避免重新查找时间过长。

**Comment by kalcaddle** [comment]
目前就支持，通过添加到收藏夹实现，任何地址栏都可以添加到收藏夹，包括复杂的复合搜索条件。


可以发送到桌面快捷方式，将智能文件夹作为快捷方式文件放置在不同地方。
也可以通过复制地址栏内容，然后新建“文件快捷方式”来实现。



杭州可道云网络有限公司


------------------ 原始邮件 ------------------
发件人: jdysya ***@***.***&gt;
发送时间: 2024年11月3日 08:31
收件人: kalcaddle/kodbox ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [kalcaddle/kodbox] 支持智能文件夹 (Issue #319)





 
类似macos系统中的智能文件夹，能够将筛选的结果保存作为一个文件夹，包括标签筛选。
 具体实现就是将筛选条件保存，当访问该智能文件夹时根据保存的筛选条件进行筛选，可能的话最好能有缓存功能，避免重新查找时间过长。

**Comment by jdysya** [comment]
> 目前就支持，通过添加到收藏夹实现，任何地址栏都可以添加到收藏夹，包括复杂的复合搜索条件。 可以发送到桌面快捷方式，将智能文件夹作为快捷方式文件放置在不同地方。 也可以通过复制地址栏内容，然后新建“文件快捷方式”来实现。 杭州可道云网络有限公司
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: jdysya ***@***.***&gt; 发送时间: 2024年11月3日 08:31 收件人: kalcaddle/kodbox ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [kalcaddle/kodbox] 支持智能文件夹 (Issue #319) 类似macos系统中的智能文件夹，能够将筛选的结果保存作为一个文件夹，包括标签筛选。 具体实现就是将筛选条件保存，当访问该智能文件夹时根据保存的筛选条件进行筛选，可能的话最好能有缓存功能，避免重新查找时间过长。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

目前貌似没法将标签筛选和高级搜索功能联用，还有一个问题，如果我想筛选出所有置顶的文件，目前能否做到

**Comment by kalcaddle** [comment]
筛选的标签,也可以添加到收藏 (保存为快捷方式, 等价于智能文件夹)
筛选出所有置顶的文件: 暂不支持.
