### ISSUE TITLE
消息增强，订阅通知

### ISSUE THREAD

**Issue by jdysya** [kalcaddle/kodbox#321]
目前整体功能很完备了，但是对应的消息通知模块约等于没有，希望能够推出通知功能，订阅一些动态信息，例如某文件夹下的文件动态、某文件的讨论，用户能够订阅自己感兴趣的动态，当发生变动能够为用户发送通知，例如邮件、webhook、gotify

或者是否有相关的接口支持一些生命周期回调函数，例如当文件动态更新时，能够自动执行用户拓展的代码（将当前的动态信息传递给这个模块）

---

相关issue:https://github.com/kalcaddle/kodbox/issues/238

**Comment by kalcaddle** [comment]
目前集成了到了企业微信, 钉钉插件中,  有需要可以购买对应插件.
也可以针对自己需要的功能,通过插件开发实现.
