### ISSUE TITLE
App icon is a bit big ( macOS client ) 

### ISSUE THREAD

**Issue by dsf1995cn** [kalcaddle/kodbox#322]
macOS可道云客户端（v0.5.4），app图标略大，很违和，需要微调一下。

<img width="164" alt="Snipaste_2024-11-12_15-50-45" src="https://github.com/user-attachments/assets/2bfb1746-9233-48f4-a8e7-5b954525183a">

**Comment by kalcaddle** [comment]
后续版本会优化处理.
