### ISSUE TITLE
feat request 图片查看器默认查看原图

### ISSUE THREAD

**Issue by shenmo7192** [kalcaddle/kodbox#325]
我是从KodExplorer转过来的

原来打开图片是直接查看原图，kodbox现在默认是压缩过的版本，需要手动点一下查看原图

能否加一个设置，可以直接看原图？

**Comment by kalcaddle** [comment]
插件配置新增了一项配置, 可以设置为打开图片为原图打开.
更新一下photoSwipe 图片预览插件即可.
