### ISSUE TITLE
Some strings bug

### ISSUE THREAD

**Issue by RallyTuning** [kalcaddle/kodbox#33]
### They won't follow the selected language **_and are not available to be translated in the language file_** like other strings.

![Screenshot_8](https://user-images.githubusercontent.com/50233545/138135224-8e522bdc-d8b6-40d5-ba4a-59547331baec.png)
![Screenshot_9](https://user-images.githubusercontent.com/50233545/138135245-b6b4433f-dd39-435f-b0b9-37051629f8c9.jpg)
![Screenshot](https://user-images.githubusercontent.com/50233545/138932805-ce052826-c4f3-49a8-991d-c7cb05bce99d.png)

---

### Also, some strings are attached (no spaces) as these examples:

![Screenshot_3](https://user-images.githubusercontent.com/50233545/138568905-e26065cc-885b-4125-8cba-57b470f9e1af.png)
![Screenshot_5](https://user-images.githubusercontent.com/50233545/138569144-7f189b0d-2eee-488c-9b7a-12c47a6a777d.png)
![Screenshot_3](https://user-images.githubusercontent.com/50233545/138600838-025568a5-e06b-432f-8e2d-3b7d41269ddd.png)

**Comment by kalcaddle** [comment]
Thanks. 
we will fixed it next version.
