### ISSUE TITLE
Chrome + Too many dedicated workers

### ISSUE THREAD

**Issue by P2T** [kalcaddle/kodbox#39]
I'm working on Chrome 96 beta, since a few days, kod editor is completely crashing after a while using it (about 5-10 minutes), but not if it stays idle.

I've checked Chrome tasks (SHIFT+ESC) and I've seen that Kod editor is creating dozens of workers that never stop/close to a point it crashes (Chrome tab gray crash screen).

It may be related to autocompletion, as the number of workers increases when autocomplete pops up.

**Comment by kalcaddle** [comment]
Closing the label will release normally,
However, when closing the dialog box, some labels may not be released.
This problem has been fixed, and the next version will be updated.
