### ISSUE TITLE
Quick scrolling/goto in folder tree

### ISSUE THREAD

**Issue by P2T** [kalcaddle/kodbox#40]
Is it possible to get a fast search bar (as when searching in a file, with CTRL+F) that searches current *developed* folder.

I have a tree with hundreds of folders at the root. If I want to go to 'temp' , I need to manually scroll down to letter 'T'.

I would expect to type CTRL+F "temp" and it would scroll down to the first folder containing "temp", exactly like Browser "Search in page" would do.

I do not expect this functionality to find a subfolder that is not already loaded (as the current CTRL+F popup implementation does).

Thank you in advance

**Comment by kalcaddle** [comment]
Editor support search now
