### ISSUE TITLE
Can't connect to FTP storage

### ISSUE THREAD

**Issue by RallyTuning** [kalcaddle/kodbox#43]
As last issue, also the version 1.24 build 1111 can't connect to an FTP server. This is the server log with `passive` mode:
```
(000001)11/11/2021 18:24:12 - (not logged in) (x.x.x.x)> USER test
(000001)11/11/2021 18:24:12 - (not logged in) (x.x.x.x)> 331 Password required for test
(000001)11/11/2021 18:24:12 - (not logged in) (x.x.x.x)> PASS ****
(000001)11/11/2021 18:24:12 - test (x.x.x.x)> 230 Logged on
(000001)11/11/2021 18:24:12 - test (x.x.x.x)> PASV
(000001)11/11/2021 18:24:12 - test (x.x.x.x)> 227 Entering Passive Mode (192,168,1,100,210,76)
(000001)11/11/2021 18:24:12 - test (x.x.x.x)> CWD /
(000001)11/11/2021 18:24:12 - test (x.x.x.x)> 250 CWD successful. "/" is current directory.
(000001)11/11/2021 18:24:12 - test (x.x.x.x)> TYPE I
(000001)11/11/2021 18:24:12 - test (x.x.x.x)> 200 Type set to I
(000001)11/11/2021 18:24:12 - test (x.x.x.x)> SIZE /
(000001)11/11/2021 18:24:12 - test (x.x.x.x)> 550 File not found
(000001)11/11/2021 18:24:12 - test (x.x.x.x)> CWD /
(000001)11/11/2021 18:24:12 - test (x.x.x.x)> 250 CWD successful. "/" is current directory.
(000001)11/11/2021 18:24:17 - test (x.x.x.x)> QUIT
(000001)11/11/2021 18:24:17 - test (x.x.x.x)> 221 Goodbye
(000001)11/11/2021 18:24:17 - test (x.x.x.x)> disconnected.
```

And this is with `active` mode:

```
(000002)11/11/2021 18:24:30 - (not logged in) (x.x.x.x)> USER test
(000002)11/11/2021 18:24:30 - (not logged in) (x.x.x.x)> 331 Password required for test
(000002)11/11/2021 18:24:30 - (not logged in) (x.x.x.x)> PASS ****
(000002)11/11/2021 18:24:30 - test (x.x.x.x)> 230 Logged on
(000002)11/11/2021 18:24:30 - test (x.x.x.x)> CWD /
(000002)11/11/2021 18:24:30 - test (x.x.x.x)> 250 CWD successful. "/" is current directory.
(000002)11/11/2021 18:24:30 - test (x.x.x.x)> TYPE I
(000002)11/11/2021 18:24:30 - test (x.x.x.x)> 200 Type set to I
(000002)11/11/2021 18:24:30 - test (x.x.x.x)> SIZE /
(000002)11/11/2021 18:24:30 - test (x.x.x.x)> 550 File not found
(000002)11/11/2021 18:24:30 - test (x.x.x.x)> CWD /
(000002)11/11/2021 18:24:30 - test (x.x.x.x)> 250 CWD successful. "/" is current directory.
(000002)11/11/2021 18:24:30 - test (x.x.x.x)> PORT 10,6,20,190,149,255
(000002)11/11/2021 18:24:30 - test (x.x.x.x)> 200 Port command successful
(000002)11/11/2021 18:24:30 - test (x.x.x.x)> STOR /index.html
(000002)11/11/2021 18:24:30 - test (x.x.x.x)> 150 Opening data channel for file transfer.
(000002)11/11/2021 18:24:35 - test (x.x.x.x)> QUIT
(000002)11/11/2021 18:24:40 - test (x.x.x.x)> disconnected.
```

In both cases, the connection and login is successful done, but after the `QUIT`, Kodbox say it's unable to connect and can't add the storage.

**Comment by kalcaddle** [comment]
We have tested FTP built on Linux and windows. We have not encountered this problem,
Please provide the FTP server details,

Operating system and version:
FTP server software and version:
Kodbox server operating system and version:
Web server software webserver and PHP version:

**Comment by RallyTuning** [comment]
Tested from 2 different online hosts and kodbox 1.24 (1111) PHP 7.4.24 (64bit) Linx hosting + a local host on my PC with PHP 7 64bit Windows 10 Pro)

I have tried all 3 installations to connect to these FTP servers: 
- Local FileZilla server 0.9.41 64 bit on Windows 10 Pro
- Remote FileZilla server 0.9.41 64 bit on Windows Server 2019
- Remote FTP from the same host as where kodbox is installed. (i mean, i also tried to connect and add the same hosting as kodbox is installed)

So, 3 different installations and 3 different FTP server for a total 9 different tests... no one work sadly.

If you know some test server, i would like to try it. Or maybe if there is a log of kodbox connections status

**Comment by nemohsia** [comment]
Try to set the write permission for the shared directory on the FileZilla server.

**Comment by RallyTuning** [comment]
They are already set to 777

**Comment by nemohsia** [comment]
Instead of setting permissions on the directory directly through the command line, check the settings through the FileZilla server. I tried to build an FTP service with FileZilla. After checking the writable option on the FileZilla server, it can work normally.

**Comment by RallyTuning** [comment]
I did in both cases. Same FTP server works good with other FTP clients (desktop)

**Comment by nemohsia** [comment]
The ability of the desktop client to connect only means that the FTP service is normal, but it does not mean that other methods (PHP) can connect normally and have the right to operate files. When adding FTP storage in the KodBox, its running process is to connect to FTP, log in, and create new folders and files. Therefore, even if you can connect and log in, if you don't have permission to create new folders and files, the storage will still fail to add.
We have built FTP services in different ways, including the FileZilla, and the tests are all normal. If it's convenient, you can send us the account information of the FTP server that can reproduce this abnormality by email (kalcaddle@qq.com), and we will conduct a debugging test to find specific problems.

This is about the configuration of the FileZilla server:
![WechatIMG28193](https://user-images.githubusercontent.com/40481257/142981091-81b6641c-d1ea-4f60-b024-7e4244262684.png)

**Comment by RallyTuning** [comment]
Thanks for your reply.
So, permissions are ok, either "777" and "write, read, access, edit, append". As you can see in the log above, it actually connect to the server, but no other commands are given... just disconnect right after the connection successful.
