### ISSUE TITLE
Folder listing takes ages

### ISSUE THREAD

**Issue by P2T** [kalcaddle/kodbox#5]
Issue : In the editor tree, when opening a folder having lots of files, the listing is way too long.

Solution : prevent file*time() functions from being fired on folders with more than 100 files.

Complementary solution : do not check parents for subfolders in this case.

**Comment by kalcaddle** [comment]
Optimized, update next version

Optimization method: the tree directory list can display 1000 items at most. When the detection time exceeds 1.5 seconds, the number of file folder contents will no longer be obtained

**Comment by P2T** [comment]
OK, it's faster, but now, it's completely broken.

Problem 1 : when opening a folder with 100+ folders, nearly all of them appears empty in the editor.
Problem 2 : impossible to expand/collapse them (they are empty).
Problem 3 : Right click refresh, tries to refresh the parent folder

Solution : make folders appear full (use has_children boolean) by default.

**Comment by kalcaddle** [comment]
we will&nbsp;optimization next version



发自我的iPhone


------------------ Original ------------------
From: P2T ***@***.***&gt;
Date: Mon,May 31,2021 4:35 PM
To: kalcaddle/kodbox ***@***.***&gt;
Cc: warlee ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [kalcaddle/kodbox] Folder listing takes ages (#5)





 
OK, it's faster, but now, it's completely broken.
 
Problem 1 : when opening a folder with 100+ folders, nearly all of them appears empty in the editor.
 Problem 2 : impossible to expand/collapse them (they are empty).
 Problem 3 : Right click refresh, tries to refresh the parent folder
 
Solution : make folders appear full (use has_children boolean) by default.
