### ISSUE TITLE
Cannot load the app (on infinityfree hoster)

### ISSUE THREAD

**Issue by MoTastisch** [kalcaddle/kodbox#52]
When I try to load the webpage it wont load and just throw this error:
Fatal error: Uncaught Error: Class 'Application' not found in /home/vol8_1/epizy.com/epiz_30586518/htdocs/index.php:4 Stack trace: #0 {main} thrown in /home/vol8_1/epizy.com/epiz_30586518/htdocs/index.php on line 4

**Comment by kalcaddle** [comment]
Through the error prompt, the program file may be missing. 
It is recommended to decompress and overwrite it with the update package
