### ISSUE TITLE
Split files/folders name by words not by chars

### ISSUE THREAD

**Issue by RallyTuning** [kalcaddle/kodbox#53]
Would be nice to split long names by words, as other software do. Instead of by "char max length". Then will be NOT hard to understand the file/folder name.

![image](https://user-images.githubusercontent.com/50233545/146239865-4461ee9a-ac7a-47a7-a41d-243efb829e87.png)

**Comment by kalcaddle** [comment]
We will optimize this feature in the next release

**Comment by RallyTuning** [comment]
> It's optimize on version 1.25.

1.28 still split in wrong way.
Split names by " " (space) and not by lenght 🙂

**Comment by kalcaddle** [comment]
The layout of multiline text wrapping depends on the rendering logic of the browser,We have no good way.

version 1.25 changed:      word-break: break-all;  =>  word-break: break-word;
