### ISSUE TITLE
php 8.x support / php 8.x 支持

### ISSUE THREAD

**Issue by Yang161941** [kalcaddle/kodbox#54]
Due to environmental problems, you can only use ` php8 1+apache2. 4 ` this set of configuration, can you support php8 as soon as possible?
```
Fatal error: Cannot acquire reference to $GLOBALS in /data/data/com.termux/files/usr/share/apache2/cloud/htdocs/app/function/web.function.php on line 824
```
---
>由于环境问题，只能使用`php8.1+apache2.4`这套配置，请问能不能尽快支持php8？
>```
>Fatal error: Cannot acquire reference to $GLOBALS in >/data/data/com.termux/files/usr/share/apache2/cloud/htdocs/app/function/web.function.php on line 824
>```

**Comment by kalcaddle** [comment]
now support php 5.3~php 8.0; 
We will support 8.1 in the next release
