### ISSUE TITLE
挂载minio后，打开包含图片文件夹时，无法加载缩略图

### ISSUE THREAD

**Issue by GalensGan** [kalcaddle/kodbox#58]
我挂载了 Minio 当作为文件存储，遇到如下问题：
1. 如果在设置中关闭 【服务器中转（下载）】功能，则打开包含图片的文件夹，会无法加载缩略图，加载请求被重定向到 minio 了。所以图片多了后，很影响使用体验
2. 如果在设置中打开 【服务器中转（下载）】功能，则下载文件的速度非常慢，本人猜测是由于中转导致的

请问针对情况1，是否可以优化下呢？
针对情况2，有什么配置方案可以解决吗？
谢谢！

**Comment by kalcaddle** [comment]
建议关闭中转,极大减轻服务器压力. 
直接管理Minio的话目前是不支持加载缩略图的;  (比较耗性能)
一般是将挂载的存储作为kod的默认存储使用的. 这时候是有缩略图的.

**Comment by GalensGan** [comment]
@kalcaddle 我是将挂载的存储作为默认的，如图：
![](https://s2.loli.net/2021/12/27/vshJokq7lD6XOmF.png)
然后我重新上传了一些新照片，清理掉本地缓存后，再次打开包含这些照片的文件夹，其请求如下图：
![](https://s2.loli.net/2021/12/27/Li9nZl6s2eFYjVt.png)
从上图可以看到，请求图片的请求被重定向了（cloud.xxx域名），然后去加载了minio上的原图（obs.xx域名）。
> kodbox 版本：1.26 1227

**Comment by kalcaddle** [comment]
确认了一下,minio 目前确实不支持图片缩略图生成;(像阿里oss,腾讯cos等是对象存储服务器是支持生成缩略图的)
后续版本做一下优化兼容, 缩略图在kod应用服务器生成(首次访问时服务器压力会比较大一点)

**Comment by kalcaddle** [comment]
目前版本,已加入自动生成缩略图逻辑.
在线升级一下即可. 大于50kb,且服务器支持gd库才会自动生成.

**Comment by GalensGan** [comment]
十分感谢！更新到`1.126 1228`版本后，成功加载缩略图，用着真舒服啊~
