### ISSUE TITLE
手机App无法连接带端口号的站点地址

### ISSUE THREAD

**Issue by tonylee-61** [kalcaddle/kodbox#62]
![微信图片_20211231160904](https://user-images.githubusercontent.com/71868423/147811458-1a45299a-099f-4726-878d-0b3b5b90eb23.jpg)

由于家用宽带内的服务器端口80被屏蔽，网页版只能通过替代端口连接
但App版提示“抱歉，App不支持地址跳转！请使用目标地址。”，删除端口号则连接超时。
请问是否有途径可以解决？谢谢！

**Comment by kalcaddle** [comment]
支持带端口的地址的
不支持服务器跳转; 填写目标服务器路径即可,不要填写一个301地址; 
APP各种接口请求都是带参数的,301跳转后导致参数丢失无法登录
