### ISSUE TITLE
GPL license violation

### ISSUE THREAD

**Issue by grupoastian** [kalcaddle/kodbox#63]
You cannot publish an open source project and give an answer like the one in the issue #60.

There are projects like Linux that is completely free of the GPL and is used by millions of users and companies and they do not excuse themselves on the pretext of protecting security.

Projects like Nextcloud/OwnCloud AGPL used by millions of completely free companies do not excuse themselves on the pretext of protecting security.

This project is totally violating the license by obfuscating a code that should not be obfuscated, what are they hiding?

**Comment by RallyTuning** [comment]
You are right, i'm not comfortable to store my private files on this app anymore. I'm not sure who access them, where they gonne be copied, what they will use for. I'm not hiding top secret things, ok, but they are still private.

**Comment by grupoastian** [comment]
> You are right, i'm not comfortable to store my private files on this app anymore. I'm not sure who access them, where they gonne be copied, what they will use for. I'm not hiding top secret things, ok, but they are still private. So, i will now use only for **_NOT sensitive files_**. I suggest you to do same, although this should be the first rule on internet.
> 
> Anyway, if you are curious about autoload, just copy the content here https://www.unphp.net/ it will deobfuscate the file, but considering is big, you must split it.

OK then please change the licensing of the project as it is not totally free, and you are showing something misleading saying that it is open source.

**Comment by grupoastian** [comment]
I go back and repeat, projects like Linux, KDE, Gnome, Nextcloud, LibreOffice, Owncloud are projects used by millions of people and they do not excuse themselves or look for the pretext of "protecting security" and are totally free software and open source projects, **This project is blowing up the GPL license** then, or they release all the code without obfuscating anything, or they change licenses. We don't know what the autoload file is hiding, Please there is no reason to obfuscate a code file that is apparently important

**Comment by grupoastian** [comment]
Your attitude of not wanting to release the code of a file says more than your words, if you are not hiding anything please release the complete, totally transparent code

**Comment by RallyTuning** [comment]
I am not the owner of the repository. Let's wait what @kalcaddle will answer about

**Comment by kalcaddle** [comment]
it's a dist version on github (Partial packaging and compilation optimization of PHP and JS files).
The purpose is to facilitate users to use it after downloading, rather than compiling, packaging or optimizing themselves

As we all know, encryption obfuscation is basically a very simple code protection It's easier to get the source code.
autoload.php is a packed and compressed file. The src file before compilation is currently in our private git. 
If you need it, you can email us and we will send the source code to you. 

email: warlee#kodcloud.com

**Comment by grupoastian** [comment]
please send the code file to email

**Comment by grupoastian** [comment]
and please no closed the issue

**Comment by kalcaddle** [comment]
Please clearly send the source code requirements and purpose description to our email,
Personal information required: name / email / mobile number;
email to: warlee#kodcloud.com.

At present, it is not allowed to use the source code for commercial purposes to rewrite, package and sell
We will to send it after confirmation.

**Comment by grupoastian** [comment]
@kalcaddle please reopen issue #63 and #64  until the situation is resolved

**Comment by martinbean** [comment]
> it's a dist version on github (Partial packaging and compilation optimization of PHP and JS files).

> The purpose is to facilitate users to use it after downloading, rather than compiling, packaging or optimizing themselves

@kalcaddle PHP is an interpreted language. If you upload a PHP script to a server running PHP, it’s interpreted. It does not need to be “compiled” or “packaged”. And I seriously doubt the obfuscating is optimising the script. I’d wager it’s doing the exact _opposite_ if the server needs to de-obfuscate it on each invocation.

> As we all know, encryption obfuscation is basically a very simple code protection It's easier to get the source code.
> autoload.php is a packed and compressed file. The src file before compilation is currently in our private git.
> If you need it, you can email us and we will send the source code to you.
email: warlee#kodcloud.com

Why? There’s absolutely no guarantee that the “source code” you send back is the same file that is obfuscated and distributed in this repository.

If there’s nothing to hide, then abide by the GPL license you’ve adopted and publish the source code as is. If you’re unwilling to do that then this is _not_ open source and goes against the spirit of open source. Especially when [people are reporting suspicious activity][1] based around this library.

[1]: https://stackoverflow.com/questions/70615796/deobfuscating-a-php-file
