### ISSUE TITLE
Request for KodBox to be completely free under the GPL

### ISSUE THREAD

**Issue by grupoastian** [kalcaddle/kodbox#64]
It is a small request, a very important small request for free software and open source, remove the obfuscation that the project has in the autoload file and all files or projects that revolve around KodBox.

Thank you.

**Comment by kalcaddle** [comment]
autoload.php  is a packed and compressed file. 
The src file before compilation is currently in our private git. If you need it, you can email us and we will send the source code to you.   warlee#kodcloud.com
