### ISSUE TITLE
free  to use

### ISSUE THREAD

**Issue by kalcaddle** [kalcaddle/kodbox#65]
Everyone  can use  this project for free
remove the  GPL licence now.

**Comment by kalcaddle** [comment]
In fact, we have opened kodbox for everyone free to use. So far, we have not obtained any revenue from this free project.

About compressed file autoload.php,It just hides the limit of users, and no other unsafe functions. You can view it by yourself through the decompression tool, You can also use nextcloud, filerun and other tools. This is your freedom.

**Comment by grupoastian** [comment]
really? is really? They mean deleting the license than releasing the code completely and after the fact they eliminate the issues, how can they convey trust? I have the record, that cannot be possible

**Comment by grupoastian** [comment]
@RallyTuning Please help me to make this viral, they eliminate the GPL license they say that the project can be used for free but they do not release the code, this is incredible, besides this there are also obfuscated files in KodExplorer no, it is not right

**Comment by RallyTuning** [comment]
@grupoastian I suggest you to ask them the source code of autoload.php and check yourself if there is something wrong. But, as you and other say, they can send a different source, so we will not know the truth. In this case, i suggest to use other cloud app. Or use it, but do not upload your sensitive data/files.

@kalcaddle I understand that you protect autoload just for hides the limit of users, but this really worth the fact that people force you to remove the License on the project and worth the fact they open these issues? Ruining the project. I don't think so. I suggest you to set back the license AND use a clean repository, without obfuscate anything. Setting the project to max 10 users AND offer payed features as a EXTERNAL plugin. And then you can obfuscate THIS plugin. So people will be free to use the standard 10 users repository and if they want, they can download the "premium pluing" to add infinite users or extra premium features. But keep these in a **_DIFFERENT_** repository.
Also, in this one (the free and clean) add a "donate system" so people can donate you if they just want to keep the free 10 users version. As me, i use exactly 9 users and i don't need more, but i want to donate you something for the work you did without pay for something that i will never use (the infinite users version).

**Comment by grupoastian** [comment]
@RallyTuning I propose you to create an alternative, completely free and from scratch with the characteristics, end-to-end encryption, document editing and more

**Comment by grupoastian** [comment]
> @grupoastian I suggest you to ask them the source code of autoload.php and check yourself if there is something wrong. But, as you and other say, they can send a different source, so we will not know the truth. In this case, i suggest to use other cloud app. Or use it, but do not upload your sensitive data/files.
> 
> @kalcaddle I understand that you protect autoload just for hides the limit of users, but this really worth the fact that people force you to remove the License on the project and worth the fact they open these issues? Ruining the project. I don't think so. I suggest you to set back the license AND use a clean repository, without obfuscate anything. Setting the project to max 10 users AND offer payed features as a EXTERNAL plugin. And then you can obfuscate THIS plugin. So people will be free to use the standard 10 users repository and if they want, they can download the "premium pluing" to add infinite users or extra premium features. But keep these in a **_DIFFERENT_** repository. Also, in this one (the free and clean) add a "donate system" so people can donate you if they just want to keep the free 10 users version. As me, i use exactly 9 users and i don't need more, but i want to donate you something for the work you did without pay for something that i will never use (the infinite users version).

@kalcaddle WordPress, Nextcloud, Owncloud offer SaaS alternatives, and they are completely free, they offer premium documentation, premium plugins because for you it is difficult to be completely free and transparent? Remove the license? It is something absurd is to make the problem bigger and close the door to the project

**Comment by kalcaddle** [comment]
> @RallyTuning 

you can use others  tools. and also you can write a project by yourself.

**Comment by RallyTuning** [comment]
@kalcaddle there is no need to be so drastic. Also, please read what i wrote, may be a good solution?

**Comment by kalcaddle** [comment]
> @kalcaddle there is no need to be so drastic. Also, please read what i wrote, may be a good solution?

thanks  for your suggestion. we also do this before.  but it's too easy to change  the user count.

**Comment by grupoastian** [comment]
> > @RallyTuning
> 
> thanks for your suggestion. we also do this before. but it's too easy to change the user count.
> 
> the source code： https://demo.kodcloud.com/#s/7uHKhChg

In a way they apply a kind of tracking
