### ISSUE TITLE
Backups dosen't works

### ISSUE THREAD

**Issue by RallyTuning** [kalcaddle/kodbox#68]
When i click to perform a "manual backup", the timer just go on long time until the action just stop without do any backups. Solutions? Where i cans see the log?
(automatic backup didn't work neither)

**Comment by kalcaddle** [comment]
try to restart the sheduled tasks
at: Server---sheduled tasks---button: restart sheduled tasks

**Comment by RallyTuning** [comment]
Schedule task and manual backup just going forward without do anything for 10 min. Then they just stop with an error.
![image](https://user-images.githubusercontent.com/50233545/149040270-72ec6105-f768-49e8-b523-86fe0df32806.png)
The time just pass until the error. But no info or log.

(also, please move buttons an progressbar a little bit more right. Now they are too much close to the text)

**Comment by kalcaddle** [comment]
Later versions will optimize this feature
