### ISSUE TITLE
Duplicate button

### ISSUE THREAD

**Issue by P2T** [kalcaddle/kodbox#7]
Hi,

Duplicate option on right click in the tree has been removed (it was in kodexplorer)
Re-add it in "More..." ?

Thanks

**Comment by kalcaddle** [comment]
Hi:
Yes,it in "More..." 


 原始邮件 
发件人: ***@***.***>
收件人: ***@***.***>
抄送: ***@***.***>
发送时间: 2021年4月22日(周四) 16:42
主题: [kalcaddle/kodbox] Duplicate button (#7)


Hi,
Duplicate option on right click in the tree has been removed (it was in kodexplorer)
 Re-add it in "More..." ?
Thanks

**Comment by P2T** [comment]
OK, my bad, it has been renamed "create a copy", it's OK

**Comment by kalcaddle** [comment]
Yes.


 原始邮件 
发件人: ***@***.***>
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
发送时间: 2021年4月22日(周四) 17:21
主题: Re: [kalcaddle/kodbox] Duplicate button (#7)


OK, my bad, it has been renamed "create a copy", it's OK
