### ISSUE TITLE
kodbox/app/autoload.php 被识别为 webshell 上传文件？

### ISSUE THREAD

**Issue by coder-xsj** [kalcaddle/kodbox#70]
kodbox/app/autoload.php 被阿里云识别为 webshell 上传文件？
![](https://s2.loli.net/2022/01/14/QUosVMYGRB5hCxD.png)
请问下是不是被误报了

**Comment by kalcaddle** [comment]
误报了



杭州可道云网络有限公司


------------------ 原始邮件 ------------------
发件人: coder-xsj ***@***.***&gt;
发送时间: 2022年1月14日 09:09
收件人: kalcaddle/kodbox ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [kalcaddle/kodbox] kodbox/app/autoload.php 被识别为 webshell 上传文件？ (Issue #70)





 
kodbox/app/autoload.php 被阿里云识别为 webshell 上传文件？
 
 请问下是不是被误报了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by coder-xsj** [comment]
> 

谢谢，明白了。
