### ISSUE TITLE
two bug

### ISSUE THREAD

**Issue by WarlockFish** [kalcaddle/kodbox#72]
bug1 ：更新的功能
```
鼠标前进后退键: 文件管理前进后退文件夹处理;
鼠标前进后退键: 编辑器光标位置前进后退支持
```
firefox浏览器不支持，edge浏览器支持，chrome支持。

bug2 后台英语字体错位
![屏幕截图 2022-02-02 230907](https://user-images.githubusercontent.com/30708115/152180787-67ebf08d-d825-42aa-a9bd-bfefb0efc8c7.png)

**Comment by kalcaddle** [comment]
感谢反馈

1. firfox 强制拦截了该事件,导致js无法捕获,所以无法做兼容支持,只能反馈到firefox官方了; 参考问题: https://qa.1r1g.com/sf/ask/4262698051/
2. 屏幕宽度自适应,后台不常用功能目前主要确保: 屏幕宽度足够时时正常即可.
3.
