### ISSUE TITLE
反向代理无法打开登陆页面

### ISSUE THREAD

**Issue by willie91** [kalcaddle/kodbox#73]
作者新年好，不知道为什么，我用nginx反向代理了可道云，但是没办法打开登录页面，同样用nginx反向代理的其他服务没有问题
https://kd.qaq.ee:6/ 这是我的地址
客户端也无法登陆，http打开和登陆都正常

**Comment by ding113** [comment]
建议参考 https://bbs.kodcloud.com/d/2105/2

**Comment by willie91** [comment]
> 建议参考 https://bbs.kodcloud.com/d/2105/2

感谢，已经正常了
