### ISSUE TITLE
在线 zip 出现不存在， 操作失败

### ISSUE THREAD

**Issue by rsonghuster** [kalcaddle/kodbox#75]
![image](https://user-images.githubusercontent.com/10919599/153559562-307d47c5-ae01-4b9a-bcab-1933064e9981.png)

![image](https://user-images.githubusercontent.com/10919599/153559611-72cbd228-5b35-4bd3-b55e-5a2e3feb5901.png)

**Comment by rsonghuster** [comment]
作者， 您好， 请问这个是 bug 吗？ 是哪些配置没有正确？

**Comment by GalensGan** [comment]
@rsonghuster 你后台是用的什么存储？我今天发现我所有的压缩包都是这个情况，我存储用的 minio。

**Comment by rsonghuster** [comment]
> @rsonghuster 你后台是用的什么存储？我今天发现我所有的压缩包都是这个情况，我存储用的 minio。

就是本地磁盘， 新建了一个本地存储， 然后填写的是本地磁盘的一个目录

**Comment by GalensGan** [comment]
@rsonghuster 我试了下，我的本地存储也有同样的问题，静等作者回复了

**Comment by kalcaddle** [comment]
没遇到过该情况, 可能和文件读写权限有关. 
方便的话提供一下站点url和一个账号,我们测试一下看看.
邮件发送到: warlee@kodcloud.com

**Comment by rsonghuster** [comment]
> 
已经发邮件了， 谢谢！

**Comment by kalcaddle** [comment]
已确定问题:

出现情况: 挂载本地物理路径, 此时选中压缩里面内容会出现不存在的情况. 
原因: 挂载本地文件夹主要用于给kodbox提供内部默认存储而使用的, 考虑到直接管理情况比较少,而且本身就可以通过地址栏输入路径直接管理. 所以未考虑到压缩的情况. 以兼容处理,下个版本更新.
解决方法: 上述也说明了, 可以直接通过地址栏输入文件夹路径进入后管理; 不会出现该问题. 为后续方便使用可以将路径添加到收藏夹.
