### ISSUE TITLE
Minio用作存储后，无法上传压缩文件，提示上传失败，在存储中可以找到文件，但是可道云中没有

### ISSUE THREAD

**Issue by GalensGan** [kalcaddle/kodbox#76]
尊敬的作者：
您好！
我将 Minio 作为 Kodbox 存储，当向个人空间中上传压缩文件（.7z，.zip等后缀，文件必须大于100K左右）时，显示上传失败，但是在 Minio 中却找到了该文件。

> kodbox 版本：v1.26 build05

**Comment by kalcaddle** [comment]
没遇到过该情况, 看一下php超时时间设置, 也可能和minio配置有关.
方便的话提供一下站点url和一个账号,我们测试一下看看.
邮件发送到: warlee#kodcloud.com; 或者在官网bbs上交流, 反馈会及时一些

**Comment by GalensGan** [comment]
我来结个题：
首先，谢谢 kodbox 的技术人员提供技术支持。
原来由于测试不够，以为是不能上传压缩文件，最后发现是不能上传所有超过100K左右的文件。但是，我原来的 minio 存储都可以，所以，我不断回忆自己的操作，发现只可能是自己修改了 nginx 中的配置导致的。
最后，通过在 nginx 中添加 `proxy_cache_convert_head off;`，终于解决了。

其原文如下：

> I think the problem is caused by the proxy converting HEAD requests to GET requests.
> I ran into this problem when using nginx as a reverse proxy and solved it by adding the following configuration:

地址：https://github.com/minio/minio-js/issues/842#issuecomment-810282099
