### ISSUE TITLE
微信无法登录

### ISSUE THREAD

**Issue by ancct** [kalcaddle/kodbox#8]
后台无法绑定微信，微信无法登录

**Comment by nemohsia** [comment]
经测试没有发现这一问题。
可能为网络问题，或服务器dns异常，无法识别并请求到可道云服务器（api.kodcloud.com）。可修改hosts，或重启web服务以刷新dns列表。
如确认网络和dns无误，请提供更详细的提示信息。

**Comment by ancct** [comment]
客户端没问题，WEB在绑定的环节，手机点击登录后，无反应。

**Comment by ancct** [comment]
已通过重启服务器解决
