### ISSUE TITLE
String problems

### ISSUE THREAD

**Issue by RallyTuning** [kalcaddle/kodbox#80]
# Image 1
Red arrow: Some string are too long and overflow the buttons.
Pink arrow: The "`<code>`" tag now is full-width, so the text that is next to it is going to the new line.

<img width="584" alt="Immagine 2022-03-04 135532" src="https://user-images.githubusercontent.com/50233545/156767518-b3228c6a-f5c8-4910-8ac0-6e5d7825f4f0.png">

# Image 2
Green arrow: String not present in language files
Blue box: It is possible to increase the width of this box to avoid the caption going to 2 lines as is for "Condivisioni pubbliche" (blue circle)

<img width="338" alt="Immagine 2022-03-04 135657" src="https://user-images.githubusercontent.com/50233545/156768130-fbbfb3a7-aaad-4a01-bc76-dfe0b8247c80.png">

**Comment by kalcaddle** [comment]
We will optimize this feature in future versions
