### ISSUE TITLE
ftp挂载局域网服务器异常

### ISSUE THREAD

**Issue by ppamoy** [kalcaddle/kodbox#82]
之前挂载omv的ftp正常，现在挂载[PDCN Padavan]老毛子路由的ftp就异常。

问题1：挂载ftp下movie硬盘根目录，kodbox 报错，路由日志如下：

vsftpd[2292]: [test] FAIL UPLOAD: Client "192.168.1.24", "/movie/index.html", 0.00Kbyte/sec

问题2：挂载ftp下movie硬盘key目录，kodbox 不报错，但是kodbox无法显示目录文件，路由日志如下：

vsftpd[2737]: [test] OK UPLOAD: Client "192.168.1.24", "/movie/key/index.html", 0.00Kbyte/sec

点击kodbox网络挂载的ftp目录，显示为空，路由日志如下：

vsftpd[3442]: [test] OK LOGIN: Client "192.168.1.24"

**Comment by kalcaddle** [comment]
基本是网络通路问题.
