### ISSUE TITLE
在 kodbox 中编辑 markdown 文件保存后，后台不会覆盖原文件，而是新增加一个文件

### ISSUE THREAD

**Issue by uyoufu** [kalcaddle/kodbox#83]
**描述：**
本人使用 minio 作为存储，当我在 kodbox 网页中编辑了 markdown 文件，然后点击保存，在 minio 的存储中发现其并没有覆盖原来的文件，而是新增了一个。
![](https://s2.loli.net/2022/03/07/xEcHiMCSDuIRevb.png)

**Comment by GalensGan** [comment]
@kalcaddle 那这个不经济呀，比如我对一个 50 M的文档编辑几次后，占用空间就蹭蹭地上涨了，都不敢去编辑它了。如果我不需要历史版本，是否可以实现覆盖呢？

**Comment by kalcaddle** [comment]
kod存储落地是cow机制, 文件元数据是引用计数模式; 
例如1个1G文件在kod内复制1000份,依然只占1G真正的存储空间;

上传时秒传则引用+1; 复制文件夹同理对应引用计数处理; 删除某个文件并清空回收站后引用会-1; 当引用为0则会删除初始文件.
历史版本同理, 默认3个历史版本, 超出3个的历史版本会被删除; 如果没有其他文件引用则会被从真正存储删除.

**Comment by GalensGan** [comment]
谢谢，这机制太棒了！
