### ISSUE TITLE
在 webdav 中编辑文件时，会不断频繁上传 .~xxx 临时文件

### ISSUE THREAD

**Issue by GalensGan** [kalcaddle/kodbox#88]
当我挂载 webdav 后，直接在挂载盘里编辑文件时，发现 kodbox 会不断地频繁地上传编辑时产生的临时文件，比如我编辑 `学习总结.md` 时，会上传 `.~学习总结.md`，然后在保存的时候，再删掉它。
![](https://s2.loli.net/2022/03/10/ly4tcjrKDxNTUJ5.png)
这有点影响编辑文件的体验，感觉有点卡。特别是保存文件(大小 100k 左右) 的时候，需要等十几秒。

**Comment by kalcaddle** [comment]
这个和本地软件写入逻辑有关, 这个临时文件是本地你用的编辑软件创建的. 不是可道云自动创建的.
你可以对比用记事本编辑一个txt保存, 和用office编辑保存一个文件.

1. txt保存只有一个put请求,就没有临时文件;(类似于本地io, fopen/fwrite)
2. office保存就有一堆操作(可能十几个步骤)  (将原文件重命名, 新建~tmp..., 上传tmp,锁定,写入,解锁等等等等);

速度问题也和这一块有关.
