### ISSUE TITLE
Date problems

### ISSUE THREAD

**Issue by RallyTuning** [kalcaddle/kodbox#89]
Date format ignore the settings. If i choose "DD/MM/YYYY" i still see the wrong "M-DD" in the file properties and in other views.

**Comment by kalcaddle** [comment]
Thank you for your feedback
Currently, DD/MM/YYYY is supported ,  DD/MM is not supported(if is current year.)

We will optimize this feature in the next release.

**Comment by RallyTuning** [comment]
In Italy (and many other EU countries) we use `DD/MM/YYYY` if is a different year. But for the current year we use `DD MMM`.
For example:
`10/06/2022`
`10 Jun`
And not `10-06` or `06-10`. This is confusing for us.

Will you add this feature too please?

**Comment by kalcaddle** [comment]
ok
