### ISSUE TITLE
all Files in random in kodbox

### ISSUE THREAD

**Issue by vadlike** [kalcaddle/kodbox#9]
I installed kodbox on the hosting. but when I want to access the "path" public_html/mysite/data/files/202105/21_efbf567d I see that all the files are in random order. In KodeExplorer, all files are in the normal order as on the web page.
how can I access the files in the normal order?

**Comment by kalcaddle** [comment]
Kodbox redesigns the underlying storage layer, which can be used for multi - user or cluster deployment

At the same time, it can achieve second transfer, automatic de duplication of the same file, copy 1000 copies of the same file in kodbox, and only occupy one copy of storage space.So the original directory structure is no longer used, and the directory structure is stored in the database

At the same time, kodbox still retains the management of physical folder path,
Just input the folder address in the address bar to manage directly

**Comment by vadlike** [comment]
Oh thank you. But its not comfortably for me. Can you add new function use old path like KodeExplorer do? i want to use sftp directly and integrate my files with many services

**Comment by kalcaddle** [comment]
kodbox still retains the management of physical folder path like kodexplorer,
Just input the folder address in the address bar to manage directly


![image](https://user-images.githubusercontent.com/3761968/119472488-df025b00-bd7c-11eb-8ab0-9bc34506ee47.png)
