### ISSUE TITLE
PhotoSwipe can't open big images

### ISSUE THREAD

**Issue by RallyTuning** [kalcaddle/kodbox#90]
PhotoSwipe plugin can't open image of 80+ MB.
`Fatal error: Allowed memory size of 524288000 bytes exhausted (tried to allocate 40960 bytes)`

**Comment by kalcaddle** [comment]
The memory used by PHP during thumbnail generation exceeds the limit
If you need to generate thumbnails of large files, you can set php.ini, 'memory_ limit'
