### ISSUE TITLE
Share link box low width

### ISSUE THREAD

**Issue by RallyTuning** [kalcaddle/kodbox#91]
Please increase the width of the share link box:

<img width="386" alt="image" src="https://user-images.githubusercontent.com/50233545/157765864-72f966ef-21f4-4c06-821f-4119779d48df.png">

**Comment by kalcaddle** [comment]
This is only a read-only input box, and the content length is uncertain,
There is a copy button behind it to copy the URL content

**Comment by kalcaddle** [comment]
You can customize css to modify the interface style.
