### ISSUE TITLE
[Request] New hash + GitHub isues labs

### ISSUE THREAD

**Issue by RallyTuning** [kalcaddle/kodbox#93]
1. Please let us use the GitHub labs to better identify issues: https://github.com/kalcaddle/kodbox/labels
2. Since PHP 7, there is a good (and fast) hash function, instead of only `MD5`, please add also `SHA1`, `SHA256`, and `SHA3 family`!
🙂

**Comment by kalcaddle** [comment]
The main reason is that the file hash has used MD5, which is not very backward compatible
