### ISSUE TITLE
[new feature request]: support to scroll to the bottom when edit the markdown file in kodbox

### ISSUE THREAD

**Issue by GalensGan** [kalcaddle/kodbox#95]
when I edit a large size file in kodbox, I couldn't scroll to the bottom directly. it takes me a lot of time to slide to the bottom on my phone。

**Comment by kalcaddle** [comment]
Because the mobile terminal scroll bar is generally not easy to operate (the scroll bar needs to be rewritten)
You can quickly locate the position you want by jumping to the specified line

editor--- right-bottom toolbar  --- click the line number
