### ISSUE TITLE
Unknown error while connecting

### ISSUE THREAD

**Issue by jay763190097** [kalcaddle/kodbox#96]
这个是什么问题呢？
![image](https://user-images.githubusercontent.com/16317178/161079628-611293bd-b03e-4b57-bafe-d01575f5b1b5.png)
哪里可以看到更详细的日志呀

**Comment by jay763190097** [comment]
[22:28:27.805]  DbMysqli->connect(); ;Unknown error while connecting
{
    "0": "index.php[6] {694}#Application->run()",
    "1": "app/autoload.php[2] {694}#Application->autorun()",
    "2": "app/autoload.php[2] {694}#Application->appRun("user.index.init")",
    "3": "app/autoload.php[2] ActionCall("user.index.init")",
    "4": "app/autoload.php[2] ActionApply("user.index.init",[])",
    "5": "app/autoload.php[2] {315}#userIndex->init()",
    "6": "app/controller/user/index.class.php[23] ActionCall("install.index.check")",
    "7": "app/autoload.php[2] ActionApply("install.index.check",[])",
    "8": "app/autoload.php[2] {cba}#installIndex->check()",
    "9": "app/controller/install/index.class.php[68] ActionCall("install.index.save")",
    "10": "app/autoload.php[2] ActionApply("install.index.save",[])",
    "11": "app/autoload.php[2] {cba}#installIndex->save()",
    "12": "app/controller/install/index.class.php[220] {cba}#installIndex->saveDb()",
    "13": "app/controller/install/index.class.php[246] {214}#DbMysqli->execute("show databases like 'kodbox'")",
    "14": "app/autoload.php[2] {214}#DbMysqli->initConnect(true)",
    "15": "app/autoload.php[2] {214}#DbMysqli->connect()",
    "16": "app/autoload.php[2] think_exception("Unknown error while connecting")",
    "memory": "7.135M"
}

**Comment by jay763190097** [comment]
sqlite也报错
[23:52:45.971]  think_trace(); ;no such table: user[ SQL语句 ] :SELECT * FROM `user` WHERE ( id = 1 ) LIMIT 1  
{
    "0": "index.php[6] {c19}#Application->run()",
    "1": "app/autoload.php[2] {c19}#Application->autorun()",
    "2": "app/autoload.php[2] {c19}#Application->appRun("user.index.init")",
    "3": "app/autoload.php[2] ActionCall("user.index.init")",
    "4": "app/autoload.php[2] ActionApply("user.index.init",[])",
    "5": "app/autoload.php[2] {ec6}#userIndex->init()",
    "6": "app/controller/user/index.class.php[23] ActionCall("install.index.check")",
    "7": "app/autoload.php[2] ActionApply("install.index.check",[])",
    "8": "app/autoload.php[2] {86f}#installIndex->check()",
    "9": "app/controller/install/index.class.php[68] ActionCall("install.index.save")",
    "10": "app/autoload.php[2] ActionApply("install.index.save",[])",
    "11": "app/autoload.php[2] {86f}#installIndex->save()",
    "12": "app/controller/install/index.class.php[220] {86f}#installIndex->saveUser()",
    "13": "app/controller/install/index.class.php[470] {269}#UserModel->find({"where":{"id":1},"limit":1,"table":"user","model":"User"})",
    "14": "app/autoload.php[2] {1b3}#DbSqlite3->select({"where":{"id":1},"limit":1,"table":"user","model":"User"})",
    "15": "app/autoload.php[2] {1b3}#DbSqlite3->query("SELECT * FROM `user` WHERE ( id = 1 ) LIMIT 1  ",[])",
    "16": "app/autoload.php[2] {1b3}#DbSqlite3->query("SELECT * FROM `user` WHERE ( id = 1 ) LIMIT 1  ")",
    "17": "app/autoload.php[2] {1b3}#DbSqlite3->error()",
    "18": "app/autoload.php[2] think_trace(args)",
    "19": "app/function/think.function.php[325] think_exception("no such table: user[ SQL\\u8bed\\u53e5 ] :SELECT * FROM `user` WHERE ( id = 1 ) LIMIT 1  ")",
    "memory": "7.135M"
}

**Comment by kalcaddle** [comment]
提示的很明显了,数据库链接错误; 检查一下数据库连接网络
后面的: no such table: user;  数据库表都没有.

**Comment by jay763190097** [comment]
第一个错误用的mysql。试了好多次，实在不行，换成sqlite没想到报没有表的错误！表都是安装程序去初始化的呀
