### ISSUE TITLE
kodbox V1.29 客户端搜索框搜索时报错

### ISSUE THREAD

**Issue by CDdickey** [kalcaddle/kodbox#97]
![image](https://user-images.githubusercontent.com/86156113/162677971-8676e4f0-6de8-42af-910a-abf5d08dc786.png)
在上述搜索框搜索时报错，PHP版本8.0
出错了! (warning!)
../app/autoload.php[2]; strtoupper();
strtoupper(): Argument #1 ($string) must be of type string, array given

**Comment by kalcaddle** [comment]
已确定: php8下,多个关键词搜索时会出现该问题(单个关键词正常,搜索加空格会按多个关键词and匹配).
已修复近期更新;  也可以暂时切换为php7.x
